from scripts.unit1_story_common import zone,cast
META={
'palace_id':'Z4','palace_name':'Carbon Workshop','story_title':'The Carbon Shape-Shifter’s Workshop',
'tagline':'One carbon frame keeps changing shape. Follow the molecular architect and see why carbon can build so many different molecules.',
'guide':{'name':'Caro Venn','role':'molecular architect','visual':'charcoal apron, four silver drafting pens clipped to one glove, amber safety glasses','story_job':'turns one carbon framework through multiple structures while keeping each chemical change visible'},
'premise':'A client has delivered a blank molecular blueprint that must be turned into a useful organic molecule before the workshop closes. The only starting piece is carbon.',
'mission':'Follow Caro from the organic signboard to the carbon workbench and functional-group wall. Watch carbon’s bonding capacity create diverse skeletons, then see how functional groups change what those skeletons can do.',
'finale':'The blank blueprint leaves the workshop as a recognizable organic molecule with a carbon skeleton and functional groups. You can now separate the carbon framework from the chemical groups that give the molecule much of its behavior.',
'estimated_minutes':7,'checkpoint_indices':[1],
'route_orientation':'The workshop is one rectangular room divided into three stations from front to back: the entrance signboard, the central carbon workbench, and the illuminated functional-group pegboard on the rear wall.',
'route':[{'scene_index':0,'locus':'Organic Signboard','short':'Organic','floor':'Entrance','symbol':'C'}, {'scene_index':1,'locus':'Carbon Workbench','short':'Carbon','floor':'Center bay','symbol':'✣'}, {'scene_index':2,'locus':'Functional-Group Pegboard','short':'Groups','floor':'Rear wall','symbol':'⚙'}]
}
SCENES=[
{'locus':'Organic Signboard','title':'The Blueprint With a Carbon Spine','kicker':'The workshop begins by deciding what kind of chemistry this molecule belongs to.','location_description':'You enter through a steel door into a warm workshop that smells faintly of machine oil. A black signboard stands directly ahead, divided into a carbon-compound side and a general-chemistry side.','orientation':'The entrance is behind you. The carbon-compound sign fills the center. Caro stands to its right with the blank blueprint, and the main workbench is visible beyond it.','zones':[zone('left','General chemistry shelf','⚗','Holds substances that are not classified simply by being carbon compounds.'),zone('center','Organic signboard','C','Directs carbon-compound work toward the organic chemistry bay.'),zone('right','Blueprint stand','▱','Holds the unfinished molecule that will move through the workshop.')],
'cast':[cast('Organic chemistry sign','field marker','a black sign with a glowing carbon skeleton','identifies organic chemistry as the study of carbon compounds'),cast('Organic compound blueprint','molecular plan','a page containing a carbon framework with open attachment points','represents a carbon-containing compound without imposing the overly narrow rule that every organic compound must contain both carbon and hydrogen')],
'paragraphs':['Caro Venn lays a blank molecular blueprint on the stand. A single black carbon atom is printed in the center, with empty lines waiting to become bonds. “This bench handles **organic chemistry**,” she says, tapping the sign. Organic chemistry is the study of carbon compounds.', 'The sign does not say CARBON + HYDROGEN ONLY. **Organic compounds** are carbon-containing compounds, and defining the entire category by requiring both carbon and hydrogen would be too narrow. Hydrocarbons will appear in the next bay, but they are one important subset, not the definition of all organic molecules.', 'Caro clips the blueprint to a rolling frame and pushes it toward the central workbench. Four silver bond arms unfold around the carbon atom.']},
{'locus':'Carbon Workbench','title':'Four Hands, Endless Skeletons','kicker':'Carbon becomes versatile because four bonding positions can be used in many combinations.','location_description':'The center bay contains a circular workbench with a large carbon model fixed at its center. Four mechanical bond arms extend from it. Rails around the table can turn into straight chains, branches, double-bond sections, or closed rings.','orientation':'The four-arm carbon model is centered. A chain-building rail is left, a bond-multiplicity control is in front, and a branching/ring former is on the right.','zones':[zone('left','Chain rail','C–C–C','Links carbon atoms into long covalent skeletons.'),zone('center','Four-arm carbon hub','4','Shows carbon’s four valence electrons and capacity for up to four covalent bonds.'),zone('right','Shape former','⌬','Bends and branches carbon skeletons and closes them into rings.')],
'cast':[cast('Carbon hub','central atom','black sphere with four silver bonding arms','uses four valence electrons to form as many as four covalent bonds'),cast('Hydrocarbon strip','carbon-hydrogen framework','a flexible chain made only of black carbon and white hydrogen pieces','represents a hydrocarbon, a molecule consisting only of carbon and hydrogen'),cast('Skeleton former','diversity machine','rails that lengthen, branch, shift double bonds, and close into rings','demonstrates the structural diversity possible in carbon skeletons')],
'paragraphs':['Caro locks one carbon atom into the center hub. Its **four valence electrons** give it the capacity to form as many as four covalent bonds. Four bonding positions are enough to connect carbon to hydrogen, oxygen, nitrogen, other carbons, and many other partners in different arrangements.', 'She changes the bond control. One carbon pair can share a single bond, double bond, or triple bond. Then the chain rail starts feeding carbon into carbon: C–C–C–C. Carbon atoms can covalently bond to one another to form **carbon chains**, creating the skeletons of many organic molecules.', 'Caro snaps white hydrogen pieces onto every open position. Now the framework contains only carbon and hydrogen. That is a **hydrocarbon**. She bends the same skeleton into a branch, slides a double bond to a new position, lengthens the chain, then closes the end into a ring.', 'This is **carbon versatility** made visible. Four bonding positions plus carbon–carbon bonding allow skeletons to differ in length, branching, multiple-bond location, and ring formation. The blueprint can therefore support an enormous variety of molecules without changing the identity of carbon itself.', 'Caro removes the hydrocarbon from the table. “The skeleton gives us shape. The next wall gives it chemistry.” She carries the frame to seven glowing hooks on the rear pegboard.'],
'checkpoint_object_id':'MO-APBIO-U1-CA006','checkpoint_prompt':'What term describes a molecule made only of carbon and hydrogen?'
},
{'locus':'Functional-Group Pegboard','title':'The Attachments That Change Behavior','kicker':'A carbon skeleton is only the frame; attached chemical groups change how the whole molecule behaves.','location_description':'The rear wall is covered by seven illuminated hooks. Each hook holds a different attachment: hydroxyl, carbonyl, carboxyl, amino, phosphate, sulfhydryl, or methyl. A carbon skeleton lies on the bench below them.','orientation':'Reactive oxygen-containing groups occupy the left hooks, nitrogen/phosphate/sulfur groups fill the center, methyl is on the right, and the carbon skeleton waits below the row.','zones':[zone('left','Oxygen-group hooks','O','Hold hydroxyl, carbonyl, and carboxyl groups.'),zone('center','N/P/S hooks','N/P/S','Hold amino, phosphate, and sulfhydryl groups.'),zone('right','Methyl hook','CH₃','Holds a nonpolar carbon-hydrogen attachment that can alter molecular shape and behavior.')],
'cast':[cast('Functional groups','chemical attachments','seven distinct molecular attachments hanging from labeled hooks','participate in characteristic reactions and alter properties of the carbon skeleton they are attached to'),cast('Carbon skeleton','molecular framework','the same black carbon framework from the previous bench','provides the backbone onto which functional groups are attached')],
'paragraphs':['Caro hangs the carbon skeleton beneath the pegboard. “The frame is not the whole molecule.” She takes down a hydroxyl group and clips it to the skeleton. The new attachment changes how that region can interact with water and other molecules.', 'A **functional group** is a chemical group attached to a carbon skeleton that participates in chemical reactions and influences the behavior of the molecule. Caro lines up the seven groups you should be able to recognize here: **hydroxyl, carbonyl, carboxyl, amino, phosphate, sulfhydryl, and methyl**.', 'She never asks you to memorize them as floating decorations. Each attachment belongs on a real molecular frame. The useful habit is to see the group, name it, and ask what chemical possibilities it adds to the larger molecule.', 'The completed blueprint glows on the bench: carbon built the versatile skeleton; the functional groups changed its chemistry. Caro rolls the finished plan through the rear doors toward the neighboring Polymer Assembly Hall.']}
]
