from scripts.unit1_story_common import zone,cast
META={
'palace_id':'Z5','palace_name':'Polymer Assembly Hall','story_title':'The Molecular Assembly Line Jam',
'tagline':'A conveyor is clogged with loose building blocks. Help the mechanic join them, cut them apart, and sort the four major biomolecule classes correctly.',
'guide':{'name':'Pip Moreno','role':'assembly-line mechanic','visual':'green coveralls, red wrench, clear water canister clipped to the belt','story_job':'keeps one molecular crate moving through joining, cutting, and classification stations'},
'premise':'The assembly hall has stopped because loose molecular pieces are piling up at the receiving dock. A half-built chain blocks the conveyor and must be completed, disassembled, and sorted correctly.',
'mission':'Follow Pip through four stations to distinguish monomers from polymers, see dehydration synthesis and hydrolysis as opposite covalent-bond processes, and compare the four major classes of biological macromolecules.',
'finale':'At the shipping board, every crate is routed correctly. You leave with one simple mechanical picture: small units can be covalently joined into chains, water chemistry can reverse those links, and the four macromolecule classes do not all use the same architecture.',
'estimated_minutes':8,'checkpoint_indices':[1,2],
'route_orientation':'The assembly hall is a straight conveyor line. You begin at Receiving, move through the hot Dehydration Welder, pass the Hydrolysis Wash Station, and end at the shipping board.',
'route':[{'scene_index':0,'locus':'Macromolecule Receiving Dock','short':'Receiving','floor':'Dock','symbol':'▣'}, {'scene_index':1,'locus':'Dehydration Welder','short':'Join','floor':'Line 1','symbol':'🔥'}, {'scene_index':2,'locus':'Hydrolysis Wash Station','short':'Split','floor':'Line 2','symbol':'💧'}, {'scene_index':3,'locus':'Comparison Shipping Board','short':'Compare','floor':'Shipping','symbol':'⇢'}]
}
SCENES=[
{'locus':'Macromolecule Receiving Dock','title':'Loose Parts at Receiving','kicker':'Before the conveyor can run, you need to know which pieces are building units and which structures are chains.','location_description':'A loading dock is buried under small molecular crates. Three conveyor lanes accept repeating building units; a fourth lipid lane carries irregular hydrophobic packages that do not form true polymers.','orientation':'Loose building units pile up left, a chain-linking conveyor runs through center, and four destination signs—carbohydrates, proteins, nucleic acids, lipids—hang on the right.','zones':[zone('left','Loose-unit bins','•','Contain repeating molecular building units.'),zone('center','Chain conveyor','••••','Links repeating units covalently into chain-like structures.'),zone('right','Four-class signs','C/P/NA/L','Separate carbohydrates, proteins, nucleic acids, and lipids without pretending all four are polymers.')],
'cast':[cast('Monomer','building unit','one small standardized piece waiting beside many copies of itself','can serve as a repeating unit used to build a polymer'),cast('Polymer','chain-like macromolecule','many repeating units covalently linked in a long chain','is a chain-like molecule built from repeating units'),cast('Lipid lane','important exception','oily packages traveling together without a repeating-chain connector','reminds you that lipids are a major biomolecule class but do not form true polymers')],
'paragraphs':['Pip Moreno kicks a jammed wheel and points to a single loose piece. A **monomer** is a building unit that can serve as one repeating part of a larger chain. When many repeating units are covalently connected, the resulting chain-like macromolecule is a **polymer**.', 'Three destination lanes make that pattern easy to see: carbohydrates can contain sugar polymers, proteins are built as amino-acid chains, and nucleic acids are nucleotide polymers. The lipid lane is deliberately different. Lipids are one of the four major biological-molecule classes, but they do **not** form true polymers.', 'Pip lifts a crate containing the four class labels—**carbohydrates, proteins, nucleic acids, and lipids**—and pushes the loose monomers toward a glowing welding station. “Now we join the pieces without losing track of what the chemistry actually does.”']},
{'locus':'Dehydration Welder','title':'Join the Pieces, Release Water','kicker':'The welding station forms covalent connections while components equivalent to water leave the reaction.','location_description':'A hot orange welding machine grips two monomer pieces. One side releases an H tag, the other an OH tag. The tags combine in a small water tray as a new covalent connection locks between the monomers.','orientation':'Unjoined monomers enter from left, the glowing welder occupies center, and a growing polymer exits right beside a collecting water tray.','zones':[zone('left','Monomer feed','• •','Supplies smaller units to be joined.'),zone('center','Dehydration welder','H + OH → H₂O','Forms a covalent connection while water-equivalent components are removed.'),zone('right','Growing chain','••••','Extends as repeated joining reactions continue.')],
'cast':[cast('Dehydration synthesis','joining reaction','a welder that removes H and OH as a water molecule while fastening two units together','forms covalent bonds between smaller units while removing components equivalent to water'),cast('Polymerization','many-unit assembly','a conveyor repeating the same joining operation again and again','builds a polymer by connecting many monomer units')],
'paragraphs':['Two monomers enter the jaws. The welder removes an H from one side and an OH from the other; together those components leave as water while a new covalent bond forms between the units. That joining process is **dehydration synthesis**.', 'The machine repeats the operation down the conveyor. Joining many monomers into a growing chain is **polymerization**. The key image is not “water somehow glues the pieces.” The bond forms as the reactants lose components equivalent to water.', 'Pip hands you the newly built chain. A warning alarm immediately sends it through a blue wash tunnel labeled REVERSE LINE.'] ,'checkpoint_object_id':'MO-APBIO-U1-PA004','checkpoint_prompt':'What reaction joins smaller units covalently while removing components equivalent to water?'},
{'locus':'Hydrolysis Wash Station','title':'Water Cuts the Chain','kicker':'The reverse line uses water to break the covalent connection.','location_description':'A blue wash tunnel surrounds one bond in the polymer chain. A water molecule is split across that connection. The bond opens and the larger chain separates into smaller pieces.','orientation':'The intact polymer enters left, a high-pressure water nozzle targets one bond at center, and smaller molecular pieces exit on the right.','zones':[zone('left','Polymer inlet','••••','Carries the covalently linked chain into the station.'),zone('center','Hydrolysis nozzle','H₂O','Adds water across a covalent bond as that bond is cleaved.'),zone('right','Smaller products','••','Receives the separated molecules after cleavage.')],
'cast':[cast('Hydrolysis','bond-cleaving reaction','a water jet splitting across one covalent link','breaks a covalent bond by adding water across it, producing smaller molecules')],
'paragraphs':['The wash nozzle fires at one covalent connection. Water is added across the bond, and the chain separates. This is **hydrolysis**: water participates in cleaving the covalent bond and breaking the larger molecule into smaller products.', 'Pip places the dehydration welder and hydrolysis nozzle side by side. One joins smaller units while removing water-equivalent components; the other breaks a covalent connection by adding water across it. Holding those opposite motions together makes the names much easier to retrieve.', 'The split pieces roll onto the final shipping board, where four enormous columns are waiting to compare what each biomolecule class is made from.'] ,'checkpoint_object_id':'MO-APBIO-U1-PA006','checkpoint_prompt':'What reaction breaks a covalent bond by adding water across that bond?'},
{'locus':'Comparison Shipping Board','title':'Four Classes, Four Structural Patterns','kicker':'The final board compares the classes without forcing them into the same monomer–polymer template.','location_description':'The shipping wall contains four illuminated columns: carbohydrate, protein, nucleic acid, and lipid. Each column has slots for building units, elements, linkage patterns, and representative roles.','orientation':'Carbohydrate and protein columns stand left, nucleic acid is center, and lipid occupies the rightmost column with a clear NOT A TRUE POLYMER marker.','zones':[zone('left','Carbohydrate / protein columns','C / P','Contrast sugar-based polymers with amino-acid polypeptides.'),zone('center','Nucleic-acid column','NA','Shows nucleotide polymers containing C, H, O, N, and P.'),zone('right','Lipid column','L','Groups fats, phospholipids, and steroids without assigning a repeating monomer/polymer architecture.')],
'cast':[cast('Macromolecule comparison board','synthesis tool','four side-by-side class columns','organizes similarities and differences in building units, elements, structures, and roles without creating false equivalences')],
'paragraphs':['Pip locks the final crate beneath the **macromolecule comparison** board. Carbohydrates are built from monosaccharides and can form polysaccharides. Proteins are built from amino acids and necessarily contain carbon, hydrogen, oxygen, and nitrogen, with sulfur present in some proteins. Nucleic acids are nucleotide polymers containing carbon, hydrogen, oxygen, nitrogen, and phosphorus.', 'The lipid column refuses to accept the POLYMER stamp. Lipids include fats, phospholipids, and steroids, but they do not form true repeating-unit polymers. Their shared chemistry is more strongly associated with hydrophobic character than with a single monomer-to-polymer construction rule.', 'The conveyor restarts. Pip grins as the four crates leave through different doors. The mechanism you carry forward is simple: identify the building unit when one exists, identify the covalent connection, and never force every biomolecule into the same architecture.']}
]
