from scripts.unit1_story_common import zone,cast
META={
'palace_id':'Z6','palace_name':'Carbohydrate Greenhouse','story_title':'The Greenhouse Sugar Trail',
'tagline':'A glowing glucose bead disappears into the greenhouse. Follow it as sugars become transport molecules, storage polymers, structural fibers, and food for microbial partners.',
'guide':{'name':'Suki Han','role':'keeper of the carbohydrate greenhouse','visual':'moss-green coat, seed pouch, round lantern containing a single glowing glucose bead','story_job':'tracks one sugar unit as it is assembled into different carbohydrate structures and follows what those structures do'},
'premise':'A rare glowing glucose bead has slipped out of Suki’s lantern and entered the greenhouse irrigation maze. Wherever it travels, the greenhouse builds a different carbohydrate around it.',
'mission':'Recover the bead by following its transformations from monosaccharide to disaccharide and polysaccharide, through storage and structural forms, then into the digestive systems of cellulose-eating herbivores.',
'finale':'At the Fiber Barn, symbiotic microbes release usable products from cellulose and Suki finally catches the glowing sugar trail. Looking back, the same kind of sugar building block produced radically different functions because its linkages and polymer architecture changed.',
'estimated_minutes':14,'checkpoint_indices':[1,4,5],
'route_orientation':'The greenhouse is a long glass conservatory. You enter at the seedling benches, follow a central vine north through storage and structural alcoves, cross the glycosidic arch and alpha/beta path, and finish in the Fiber Barn.',
'route':[{'scene_index':0,'locus':'Mono-Sugar Seedling','short':'Monosugar','floor':'South bench','symbol':'◇'}, {'scene_index':1,'locus':'Sucrose Trellis','short':'Sucrose','floor':'Trellis','symbol':'◇◇'}, {'scene_index':2,'locus':'Polysaccharide Vine','short':'Polymer','floor':'Central aisle','symbol':'〰'}, {'scene_index':3,'locus':'Storage Pantry Alcove','short':'Storage','floor':'West alcove','symbol':'▣'}, {'scene_index':4,'locus':'Structural Wall Alcove','short':'Structure','floor':'East alcove','symbol':'▥'}, {'scene_index':5,'locus':'Glycosidic Archway','short':'Linkage','floor':'North arch','symbol':'—'}, {'scene_index':6,'locus':'Alpha/Beta Path','short':'α / β','floor':'North path','symbol':'αβ'}, {'scene_index':7,'locus':'Cellulose Fiber Barn','short':'Digestion','floor':'Barn','symbol':'🌾'}]
}
SCENES=[
{'locus':'Mono-Sugar Seedling','title':'The Bead in the Seedling Tray','kicker':'The sugar trail begins with one simple carbohydrate unit.','location_description':'You enter the warm south bench of the greenhouse. Rows of seedling trays sit under glass lamps. In the center tray, Suki’s missing glowing sugar bead has embedded itself in a model with several hydroxyl tags and one carbonyl marker.','orientation':'Seedlings fill the left bench, the glowing sugar model sits center, and formula cards marked CH₂O repeat along the right rail.','zones':[zone('left','Carbohydrate bench','C H O','Shows carbohydrates built primarily from carbon, hydrogen, and oxygen.'),zone('center','Monosugar tray','◇','Holds one simple sugar unit.'),zone('right','Formula rail','(CH₂O)n','Shows a common monosaccharide pattern while leaving room for exceptions.')],
'cast':[cast('Monosaccharide','simple sugar','one glowing sugar ring sitting alone in a seed tray','serves as a simple sugar and as a monomer for larger carbohydrate polymers'),cast('Carbohydrate frame','chemical pattern','a C/H/O framework carrying hydroxyl and carbonyl features','shows common chemical features of carbohydrates')],
'paragraphs':['Suki kneels beside the glowing tray. Carbohydrates are built primarily from **carbon, hydrogen, and oxygen**, and many sugars carry several hydroxyl groups along with a carbonyl group or a form derived from one.', 'The single glowing unit is a **monosaccharide**—a simple sugar. Monosaccharides can be used directly and can also serve as the monomers from which larger carbohydrate structures are built.', 'A row of formula cards repeats CH₂O, CH₂O, CH₂O as n increases. The pattern **(CH₂O)n** is useful for many monosaccharides, but Suki leaves an exception gate open so you do not turn it into an absolute rule.', 'The bead rolls out of the seed tray and climbs a trellis where another sugar is waiting to lock beside it.']},
{'locus':'Sucrose Trellis','title':'Two Sugars Meet on the Trellis','kicker':'One sugar can be fuel; two joined sugars can become a transport molecule.','location_description':'A wooden trellis rises under the glass roof. A glowing glucose ring climbs from the left while a fructose ring hangs from the right. A clasp in the center can join exactly two sugars.','orientation':'The glucose side is left, the joining clasp is center, and fructose with a plant-transport tag is on the right.','zones':[zone('left','Glucose vine','G','Carries a common monosaccharide used as cellular fuel.'),zone('center','Two-sugar clasp','2','Joins two monosaccharides into a disaccharide.'),zone('right','Sucrose transport basket','G+F','Carries the glucose–fructose disaccharide through the plant display.')],
'cast':[cast('Glucose','monosaccharide','a bright six-carbon sugar bead pulsing like a small battery','is a common monosaccharide that cells can use as fuel, including in cellular respiration'),cast('Disaccharide clasp','two-sugar molecule','a clasp holding exactly two sugar rings','represents a disaccharide: two monosaccharides covalently joined'),cast('Sucrose','plant transport sugar','a paired glucose–fructose ornament placed in a moving plant basket','is the disaccharide made from glucose and fructose and is an important transport sugar in plants')],
'paragraphs':['The runaway bead is now unmistakably **glucose**, a common monosaccharide that cells can use as fuel. A nearby seedling display flashes CELLULAR RESPIRATION as the glucose battery feeds energy-releasing pathways.', 'Suki catches another point before the bead escapes: monosaccharides are also **building blocks**. Their carbon skeletons can contribute to other molecules, and their sugar units can be joined into larger carbohydrates.', 'At the center clasp, two monosaccharides lock together. A carbohydrate made from two covalently joined monosaccharides is a **disaccharide**. Here the pair is glucose plus fructose. The plant’s transport basket labels that particular disaccharide **sucrose**.', 'The basket tips. The paired sugars fall into a living vine that begins adding one sugar after another until the two-unit structure becomes a long chain.'] ,'checkpoint_object_id':'MO-APBIO-U1-CG007','checkpoint_prompt':'Which disaccharide is made from glucose and fructose and serves as an important transport sugar in plants?'},
{'locus':'Polysaccharide Vine','title':'When the Sugar Chain Keeps Growing','kicker':'Many sugar monomers can build a carbohydrate polymer with very different possible shapes.','location_description':'A thick vine runs down the central aisle. Sugar rings click into the stem one after another. Some branches fork sideways while other sections remain straight.','orientation':'Loose sugar units enter from the left, the growing polysaccharide vine is center, and branching/straight forms extend toward the right wall.','zones':[zone('left','Sugar-monomer feed','◇','Supplies monosaccharides.'),zone('center','Polysaccharide vine','◇◇◇','Builds a carbohydrate polymer from many sugar monomers.'),zone('right','Linear / branched growth','Y','Shows that complex carbohydrate polymers can be linear or branched.')],
'cast':[cast('Polysaccharide','carbohydrate polymer','a vine made from many repeating sugar units','is a carbohydrate polymer composed of many monosaccharides and may be linear or branched')],
'paragraphs':['The vine no longer contains two sugars. It contains dozens. A **polysaccharide** is a carbohydrate polymer made from many sugar monomers. Suki traces the chain with one finger as it runs the length of the aisle.', 'One section grows straight; another forks into branches. A polysaccharide is therefore not defined by one fixed overall shape. Complex carbohydrate polymers can be **linear or branched**, and that architecture helps determine what the molecule can do.', 'Two doors open beside the vine. The west door is marked STORAGE. The east door is built into the greenhouse wall itself. The runaway sugar trail turns west first.']},
{'locus':'Storage Pantry Alcove','title':'Two Ways to Store Glucose','kicker':'Plants and animals both store glucose in polymers, but they use different storage molecules.','location_description':'The west alcove is a pantry with two enormous jars. The green jar is packed with plant-labeled glucose chains; the red jar contains dense, highly branched animal-labeled chains.','orientation':'The starch jar stands left, a glucose scoop sits center, and the glycogen jar stands right beside liver and muscle icons.','zones':[zone('left','Plant storage jar','STARCH','Stores excess glucose in plant tissues.'),zone('center','Glucose scoop','◇','Shows that both storage polymers are built from glucose.'),zone('right','Animal storage jar','GLYCOGEN','Stores glucose in animals, especially liver and muscle cells.')],
'cast':[cast('Starch','plant storage polysaccharide','a green jar of coiled or branched glucose polymer','stores excess glucose in plants'),cast('Glycogen','animal storage polysaccharide','a red jar packed with densely branched glucose chains','stores glucose in animals, including liver and muscle cells')],
'paragraphs':['Suki opens the green jar. **Starch** is a glucose polymer used by plants for storage of excess glucose. The plant does not keep every glucose molecule loose; it can package many into a storage polysaccharide.', 'The red jar is labeled **glycogen**. Glycogen is also a glucose polymer, but it is the major storage form emphasized for animals, including liver and muscle cells.', 'Both jars contain glucose-based polymers, yet neither is the structural wall holding up the greenhouse. The sugar trail slips under the pantry door and heads across the aisle into the wall itself.']},
{'locus':'Structural Wall Alcove','title':'Sugar Chains Turn Into Armor','kicker':'Carbohydrates can hold structures up, not just store fuel.','location_description':'The east alcove exposes a cutaway of the greenhouse wall. Parallel plant fibers reinforce one panel; beside it hangs a translucent arthropod shell with a tough carbohydrate layer.','orientation':'Cellulose fibers reinforce the left wall, a central support beam separates the examples, and the chitin shell hangs on the right.','zones':[zone('left','Plant cell-wall panel','CELLULOSE','Uses strong carbohydrate fibers for structural support.'),zone('center','Support beam','▥','Makes the storage-versus-structure contrast visible.'),zone('right','Arthropod shell','CHITIN','Shows another structural polysaccharide.')],
'cast':[cast('Cellulose','plant structural polysaccharide','straight sugar chains bundled into wall fibers','forms a major structural component of plant cell walls'),cast('Chitin','structural polysaccharide','a tough translucent layer shaped like an insect exoskeleton','provides structural support in arthropod exoskeletons and fungal cell walls')],
'paragraphs':['The wall itself is woven from **cellulose**, a structural polysaccharide that forms plant cell walls. The straight fibers resist pulling forces and give the plant material strength.', 'Beside it, Suki lifts an arthropod shell. Its structural carbohydrate is **chitin**. Chitin strengthens arthropod exoskeletons and also occurs in fungal cell walls.', 'Storage and structure can therefore both use carbohydrate polymers, but the molecules are not interchangeable. The difference becomes clearer at the next archway, where the actual covalent connections between sugar units are magnified.'] ,'checkpoint_object_id':'MO-APBIO-U1-CG011','checkpoint_prompt':'Which structural polysaccharide forms a major part of plant cell walls?'},
{'locus':'Glycosidic Archway','title':'The Bond Between Sugars','kicker':'The way glucose units connect helps determine the shape of the larger carbohydrate.','location_description':'A stone arch spans the north walkway. Every stone is shaped like a glucose ring. Brass connectors link carbon 1 of one ring to carbon 4 of the next, and two rotating rings show alpha and beta orientations.','orientation':'The 1→4 connector is left, the linked sugar arch is center, and the alpha/beta rotating-glucose display is right.','zones':[zone('left','1→4 connector','1→4','Shows one common carbon-to-carbon numbering relationship across the glycosidic connection.'),zone('center','Glycosidic arch','—','Uses covalent links to join monosaccharides into a larger carbohydrate.'),zone('right','Alpha / beta rings','α β','Shows two ring forms differing in the orientation of the hydroxyl group at carbon 1.')],
'cast':[cast('Glycosidic linkage','covalent sugar connection','a brass connector joining one glucose ring to the next','is the covalent bond joining monosaccharides'),cast('Alpha and beta glucose','two glucose ring forms','two identical glucose rings whose carbon-1 hydroxyl points in different orientations','differ at carbon 1 and can participate in carbohydrate structures with different geometry')],
'paragraphs':['Suki points to the brass connector holding two sugar stones together. A **glycosidic linkage** is the covalent bond that joins monosaccharides. On this model, a common 1→4 connection links carbon 1 of one glucose to carbon 4 of the next.', 'At the right display, two glucose rings are chemically the same sugar but differ in how the hydroxyl group at carbon 1 is oriented. These are **alpha glucose** and **beta glucose**. That small orientation difference changes the geometry of the linkages they can form in larger polymers.', 'The arch splits into two paths. One path curls into a loose coil and branches. The other stays ruler-straight and lines up with neighboring chains. Suki points north. “Now watch what that tiny bond orientation does at the scale of an entire structure.”'] ,'checkpoint_object_id':'MO-APBIO-U1-CG013','checkpoint_prompt':'What is the covalent bond that joins monosaccharides called?'},
{'locus':'Alpha/Beta Path','title':'One Sugar, Two Architectures','kicker':'A small difference at each linkage accumulates into a large difference in polymer shape and function.','location_description':'The north path divides into two glass lanes. The alpha lane bends into coils and branches. The beta lane runs straight, and many straight chains lie parallel like cables.','orientation':'The alpha/starch lane is left, a shared glucose marker stands center, and the beta/cellulose lane is right.','zones':[zone('left','Alpha lane','α','Forms starch-like storage architectures that can coil and, in some forms, branch.'),zone('center','Glucose marker','◇','Reminds you that both paths are constructed from glucose units.'),zone('right','Beta lane','β','Forms straight cellulose chains that can align with neighboring chains.')],
'cast':[cast('Starch architecture','storage structure','alpha-linked glucose chain curling into a helix with branches nearby','shows how alpha-glucose linkages support storage structures'),cast('Cellulose microfibrils','structural bundle','parallel beta-linked chains tied together by many hydrogen bonds','shows how straight cellulose chains align into strong microfibrils')],
'paragraphs':['On the left, alpha-linked glucose chains curl and may branch. These are the structural tendencies associated with **starch**, including coiled regions and branching in amylopectin. On the right, beta-linked glucose chains remain straight and unbranched, the architecture of **cellulose**.', 'Several cellulose chains slide together side by side. Hydrogen bonds form between neighboring chains, bundling them into strong **microfibrils**. A tiny difference repeated at every glucose linkage has become a macroscopic difference between a storage material and a load-bearing fiber.', 'Suki does not ask you to reproduce every molecular drawing from memory. The durable idea is the relationship: linkage geometry changes polymer architecture, and architecture changes function.', 'The straight cellulose path disappears beneath a barn door. Inside, a cow and a horse are both eating the same fibrous hay—but their digestive maps light up in completely different places.']},
{'locus':'Cellulose Fiber Barn','title':'The Animals That Need Microbial Partners','kicker':'Herbivores gain access to cellulose energy through microorganisms that possess the missing chemistry.','location_description':'The final barn contains two life-size digestive models. A cow model stands left with four labeled stomach chambers. A horse model stands right with an enlarged cecum and large intestine. A glowing community of microbes occupies the fermentation chambers.','orientation':'The cow digestive model is left, a bale of cellulose-rich hay and microbe projector are center, and the horse hindgut model is right.','zones':[zone('left','Cow ruminant model','🐄','Shows rumen, reticulum, omasum, and abomasum in order.'),zone('center','Cellulose / microbes','🌾','Microbial cellulase and fermentation unlock energy from cellulose that the animal cannot hydrolyze by itself.'),zone('right','Horse hindgut model','🐎','Places major cellulose fermentation in the cecum and large intestine rather than a ruminant stomach.')],
'cast':[cast('Cellulose-digesting microbes','mutualistic partners','glowing microorganisms clustered around cellulose fibers','produce enzymes and carry out fermentation that give herbivores access to energy from cellulose'),cast('Ruminant stomach','cow digestive system','four connected chambers: rumen, reticulum, omasum, abomasum','houses microbial fermentation early in digestion and then passes material through water removal and acid/enzyme digestion'),cast('Horse hindgut','hindgut-fermentation system','an enlarged cecum and large intestine behind a single stomach','houses much of the horse’s cellulose-digesting microbial community after the small intestine')],
'paragraphs':['Suki drops cellulose-rich hay into both models. The animals themselves do not produce the cellulase needed to hydrolyze cellulose. Their solution is ecological: **mutualistic microorganisms** perform cellulose digestion and fermentation, allowing the host to gain access to energy from otherwise resistant plant fiber.', 'The cow is a ruminant. Its four stomach chambers appear in sequence: **rumen, reticulum, omasum, abomasum**. Microbial cellulose digestion occurs especially in the rumen and reticulum. The omasum removes water and other materials, and the abomasum carries out acidic, enzyme-driven digestion using the cow’s own secretions.', 'The horse takes a different route. It is **not** a ruminant. It is a hindgut fermenter, with cellulose-digesting microorganisms concentrated mainly in an enlarged **cecum** and large intestine.', 'A final glow travels from the cellulose fiber into the microbial chamber, then into the animal’s nutrient stream. Suki catches the original sugar bead as it rolls from the display. “Same class of molecule,” she says, closing the lantern, “but the linkage, architecture, and biological partner decide what that carbohydrate can do.”']}
]
