from scripts.unit1_story_common import zone,cast
META={
'palace_id':'Z9','palace_name':'Lipid Membrane Wing','story_title':'The Membrane Rescue Wing',
'tagline':'A cell membrane has become unstable as temperature changes. Follow the lipid technician from fat components to phospholipid bilayers and cholesterol’s buffering role.',
'guide':{'name':'Lena Ortiz','role':'membrane systems technician','visual':'slate-gray jumpsuit, transparent tablet showing a live bilayer, orange molecular clamp','story_job':'keeps one damaged membrane model on screen while each station contributes a lipid feature needed to repair it'},
'premise':'A membrane-testing wing has lost temperature control. The model cell membrane becomes too fluid when warm and packs too tightly when cold. Lena must rebuild the lipid architecture before the chamber cycles again.',
'mission':'Follow Lena through eight stations. Distinguish fats, phospholipids, and steroids; build fats from glycerol and fatty acids; compare saturated and unsaturated tails; assemble a phospholipid bilayer; and use cholesterol to buffer membrane fluidity.',
'finale':'The repaired bilayer survives both warm and cold tests. Looking back through the wing, you can see why different lipid structures serve storage, membrane, and signaling roles—and why cholesterol does not simply make a membrane rigid.',
'estimated_minutes':14,'checkpoint_indices':[2,3,5,7],
'route_orientation':'The wing runs as one semicircular membrane-repair lab. You enter through the Lipid Lobby, move through fat-building and fatty-acid stations, cross the membrane pool, visit the steroid gallery, and finish at the temperature gate.',
'route':[{'scene_index':0,'locus':'Lipid Lobby','short':'Lipids','floor':'Lobby','symbol':'◐'},{'scene_index':1,'locus':'Glycerol Hook Rack','short':'Fat parts','floor':'Build bay','symbol':'Y'},{'scene_index':2,'locus':'Ester-Linkage Bench','short':'Ester','floor':'Build bay','symbol':'—'},{'scene_index':3,'locus':'Fatty-Acid Tail Runway','short':'Tails','floor':'Runway','symbol':'〰'},{'scene_index':4,'locus':'Fat Storage Vault','short':'Fat roles','floor':'Vault','symbol':'▣'},{'scene_index':5,'locus':'Phospholipid Pool Wall','short':'Bilayer','floor':'Membrane pool','symbol':'◉'},{'scene_index':6,'locus':'Steroid Ring Gallery','short':'Steroids','floor':'Gallery','symbol':'⬡'},{'scene_index':7,'locus':'Cholesterol Thermostat Gate','short':'Cholesterol','floor':'Test gate','symbol':'🌡'}]
}
SCENES=[
{'locus':'Lipid Lobby','title':'The Molecules That Refuse the Fountain','kicker':'Lipids share substantial hydrophobic character, but the class contains several very different structures.','location_description':'The lobby floor surrounds a circular water fountain. Oily droplets bead away from the water. Three illuminated doors lead to FAT, PHOSPHOLIPID, and STEROID sections. Lena’s membrane tablet flashes red.','orientation':'The water fountain is left, oily lipid samples and Lena’s tablet are center, and the three lipid-class doors are right.','zones':[zone('left','Water fountain','💧','Makes hydrophobic behavior visible.'),zone('center','Lipid samples','◐','Shows molecules with substantial hydrocarbon-rich hydrophobic regions.'),zone('right','Three class doors','F/P/S','Lead to fats, phospholipids, and steroids; cholesterol belongs in the steroid family.')],
'cast':[cast('Lipid','molecular class','oily molecules that bead away from water, plus an amphipathic phospholipid model','is a diverse class with substantial hydrophobic character; phospholipids also contain a hydrophilic region'),cast('Lipid directory','class map','three doors labeled fat, phospholipid, steroid','organizes the major lipid types emphasized here without pretending lipids are true polymers')],
'paragraphs':['A droplet rolls into the fountain and immediately beads away. **Lipids** are diverse molecules with substantial hydrophobic character because much of their structure is hydrocarbon-rich. Many are largely nonpolar, although phospholipids are amphipathic rather than simply “nonpolar.”', 'Lena points to the three doors: **fats, phospholipids, and steroids**. Cholesterol will appear later as a steroid lipid. None of these should be forced into a true repeating-unit polymer model.', 'Her membrane tablet flashes again. “We need the building logic first.” She pushes open the fat door, where a three-hook glycerol rack is waiting.']},
{'locus':'Glycerol Hook Rack','title':'One Glycerol, Three Fatty-Acid Tails','kicker':'A fat has a three-carbon alcohol framework joined to three fatty acids.','location_description':'A rack shaped like a three-pronged Y stands under bright lights. The central glycerol model has three hydroxyl-bearing positions. Three long fatty-acid tails hang beside it, each ending in a carboxyl group.','orientation':'Glycerol rack is center, fatty-acid tails hang right, and a completed three-tail fat model is displayed left.','zones':[zone('left','Completed fat','3 tails','Shows glycerol joined to three fatty acids.'),zone('center','Glycerol rack','Y','Provides the three-carbon alcohol framework.'),zone('right','Fatty-acid hooks','~~~~COOH','Show long hydrocarbon chains ending in a carboxyl group.')],
'cast':[cast('Glycerol','fat framework','a three-carbon alcohol with three hydroxyl-bearing positions','provides the central framework that can be joined to three fatty acids in a fat'),cast('Fatty acid','lipid component','a long hydrocarbon chain ending in a carboxyl group','provides the hydrophobic tail component of fats and phospholipids'),cast('Fat','storage lipid','one glycerol framework carrying three fatty-acid tails','is composed of glycerol joined to three fatty acids')],
'paragraphs':['Lena lifts the central frame. **Glycerol** is a three-carbon alcohol with hydroxyl groups that provide attachment positions. Beside it hang three **fatty acids**, each with a long hydrocarbon chain and a carboxyl group at one end.', 'When one glycerol is joined to three fatty acids, the result is a **fat**. The model already hints at why the molecule has strong hydrophobic character: most of its structure consists of long hydrocarbon tails.', 'The pieces are still separate. Lena carries them to an orange clamp where the actual covalent connections will be formed.']},
{'locus':'Ester-Linkage Bench','title':'The Covalent Clasp in a Fat','kicker':'Dehydration reactions join fatty acids to glycerol through ester linkages.','location_description':'An orange molecular clamp aligns one fatty-acid carboxyl end with a glycerol hydroxyl position. A water indicator flashes as the new covalent connection closes.','orientation':'Glycerol is left, the ester-forming clamp is center, and the attached fatty-acid tail extends right.','zones':[zone('left','Glycerol hydroxyl','OH','Provides one side of the joining reaction.'),zone('center','Ester clamp','—','Forms the covalent ester linkage through dehydration chemistry.'),zone('right','Fatty-acid carboxyl','COOH','Provides the fatty-acid side of the linkage.')],
'cast':[cast('Ester linkage','fat covalent connection','a bright clasp between glycerol and a fatty acid','covalently joins fatty acids to glycerol in fats through dehydration reactions')],
'paragraphs':['The clamp closes. The covalent connection between the fatty acid and glycerol is an **ester linkage**. In fat synthesis, ester linkages form through dehydration reactions.', 'Lena repeats the connection until all three fatty-acid tails are attached. She does not ask you to memorize an exact structural drawing; the durable relationship is glycerol + fatty acids connected by ester linkages.', 'The finished tails drag across the floor toward a runway where some lie straight and others bend sharply.'] ,'checkpoint_object_id':'MO-APBIO-U1-LIP006','checkpoint_prompt':'What covalent linkage joins fatty acids to glycerol in a fat?'},
{'locus':'Fatty-Acid Tail Runway','title':'Straight Tails and Kinked Tails','kicker':'Carbon-carbon double bonds change tail shape, unsaturation, and packing behavior.','location_description':'A long runway displays fatty-acid tails side by side. Straight tails contain only carbon-carbon single bonds. Other tails kink at glowing C=C double-bond hinges. A packing tray compares how tightly each group can stack.','orientation':'Straight saturated tails line the left lane, C=C hinge display is center, and kinked unsaturated tails with a fluidity tray occupy the right lane.','zones':[zone('left','Saturated lane','────','Contains no C=C double bonds and packs relatively tightly.'),zone('center','Double-bond hinge','C=C','Introduces a rigid bend in common cis-unsaturated tails.'),zone('right','Unsaturated lane','──⌁─','Contains one or more C=C double bonds and packs less tightly as kinks accumulate.')],
'cast':[cast('Saturated fatty acid','fatty-acid type','a straight hydrocarbon tail with only carbon-carbon single bonds','contains no C=C double bonds'),cast('Unsaturated fatty acid','fatty-acid type','a tail containing at least one C=C double bond','contains one or more carbon-carbon double bonds'),cast('Double-bond kink','shape change','a visible bend at a C=C hinge','makes the tail less straight and interferes with tight packing')],
'paragraphs':['The left tails are **saturated fatty acids**: their carbon chains contain only carbon-carbon single bonds and no C=C double bonds. They can line up relatively straight.', 'The right tails are **unsaturated fatty acids** because each contains at least one C=C double bond. In the common cis configuration emphasized here, that double bond creates a **kink** in the hydrocarbon chain.', 'Lena adds more double-bond hinges. More double bonds mean greater **unsaturation**, and more kinks interfere with close packing. As a result, greater unsaturation is generally associated with greater **liquidity at room temperature**.', 'The runway sends the completed fats into a heavy vault labeled LONG-TERM STORAGE.'] ,'checkpoint_object_id':'MO-APBIO-U1-LIP008','checkpoint_prompt':'What type of fatty acid contains at least one carbon-carbon double bond?'},
{'locus':'Fat Storage Vault','title':'Dense Energy for Later','kicker':'Fats are built for long-term energy storage and can also support cushioning and insulation.','location_description':'The vault contains compact energy barrels stacked behind thick padded walls. A body silhouette shows adipose tissue around organs and a subcutaneous layer under the skin.','orientation':'Energy barrels fill left, an organ-cushion model sits center, and the subcutaneous insulation layer is right.','zones':[zone('left','Energy storage','⚡','Stores large amounts of chemical energy for long-term use.'),zone('center','Organ cushion','◉','Adipose tissue can physically cushion organs.'),zone('right','Insulation layer','▱','Subcutaneous fat can reduce heat transfer.')],
'cast':[cast('Stored fat','long-term reserve','dense lipid barrels marked FOR LATER','serves as an important long-term energy store'),cast('Adipose tissue','fat-containing tissue','padded tissue surrounding organs and under skin','can cushion organs and contribute to thermal insulation')],
'paragraphs':['Inside the vault, **fat** is treated as long-term storage. Energy-rich hydrocarbon chains make fats effective reservoirs of chemical energy for later use.', 'The body model adds two additional roles. **Adipose tissue** can cushion organs, and subcutaneous fat can provide **thermal insulation**. Fats therefore participate in cellular and organismal function beyond serving as an immediate fuel molecule.', 'Lena leaves the storage vault and returns to the membrane emergency. A round pool ahead is filling with phospholipids whose heads and tails are orienting themselves without being told where to go.']},
{'locus':'Phospholipid Pool Wall','title':'The Molecules That Build a Wall in Water','kicker':'A phospholipid carries two chemical personalities, so many of them self-organize into a bilayer.','location_description':'A clear pool fills the center of the room. Each phospholipid model has a round phosphate-containing head and two hydrocarbon tails. As the models enter water, heads face the water while tails hide together inside a growing double layer.','orientation':'Individual phospholipid parts are left, the assembling bilayer is center, and the completed membrane wall spans the right side.','zones':[zone('left','Phospholipid model','○〰〰','Shows glycerol, two fatty-acid tails, and a phosphate-containing head region.'),zone('center','Bilayer assembly','○〰〰|〰〰○','Heads face water on both sides while tails gather inward.'),zone('right','Membrane wall','║','The completed phospholipid bilayer forms the basic lipid barrier of the membrane.')],
'cast':[cast('Phospholipid','amphipathic lipid','a molecule with a hydrophilic phosphate-containing head and two hydrophobic fatty-acid tails','forms the major structural lipid pattern of cell membranes'),cast('Hydrophilic head','water-interacting region','a charged/polar round head facing the surrounding water','interacts favorably with aqueous environments'),cast('Hydrophobic tails','water-avoiding region','two hydrocarbon tails tucked into the membrane interior','avoid water and cluster with other hydrophobic tails'),cast('Phospholipid bilayer','membrane structure','two sheets of phospholipids tail-to-tail','forms a stable membrane barrier in water')],
'paragraphs':['Lena holds up one **phospholipid**: glycerol connected to two fatty acids and a phosphate-containing head region. Unlike a fat, it has only two fatty-acid tails and a strongly polar/charged head region.', 'The head is **hydrophilic** and interacts with water. The fatty-acid tails are **hydrophobic**. When many phospholipids enter water, those two tendencies drive organization: heads remain exposed to water while tails cluster away from it.', 'Two layers meet tail-to-tail. The result is a **phospholipid bilayer**, the basic lipid architecture of plasma and other cell membranes. The membrane repair on Lena’s tablet finally has a wall—but it still fails the temperature test.', 'She points to a gallery of four-ring molecules. “The final adjustment comes from a different kind of lipid.”'] ,'checkpoint_object_id':'MO-APBIO-U1-LIP013','checkpoint_prompt':'What amphipathic lipid has a phosphate-containing hydrophilic head and two hydrophobic fatty-acid tails?'},
{'locus':'Steroid Ring Gallery','title':'Four Fused Rings, Different Signals','kicker':'Steroids share a ring framework even when their attached groups and biological roles differ.','location_description':'A gallery displays molecular sculptures built around four fused carbon rings. Different side groups decorate each sculpture. One case is labeled TESTOSTERONE; several others are labeled hormone or membrane precursor.','orientation':'The four-ring framework is left, testosterone display is center, and diverse steroid derivatives fill the right wall.','zones':[zone('left','Four-ring skeleton','⬡⬡','Shows the characteristic fused-ring framework of steroids.'),zone('center','Testosterone case','T','Displays one specific steroid hormone.'),zone('right','Steroid variants','R','Shows that attached groups create different steroid molecules and functions.')],
'cast':[cast('Steroid','lipid class','a rigid framework of four fused carbon rings','is defined by the characteristic four-ring carbon framework'),cast('Testosterone','steroid hormone','one four-ring molecule in a labeled display case','is an example of a steroid that functions as a hormone'),cast('Steroid hormones','signaling molecules','selected steroid models carrying signal badges','can regulate growth, development, metabolism, and homeostasis; not every steroid is a hormone')],
'paragraphs':['The common feature across the gallery is the rigid framework of **four fused carbon rings**. Lipids built on this framework are **steroids**. Different attached groups distinguish one steroid molecule from another.', 'The center case contains **testosterone**, one example of a steroid hormone. Some steroids function as hormones that regulate processes such as growth, development, metabolism, and homeostasis.', 'Lena leaves several four-ring models without hormone badges. “Do not turn the example into the definition,” she says. Not every steroid is a hormone.', 'At the far end, one steroid is already embedded between phospholipid tails on the membrane tablet. Its name is cholesterol, and the temperature chamber is waiting.']},
{'locus':'Cholesterol Thermostat Gate','title':'The Membrane Fluidity Buffer','kicker':'Cholesterol restrains excessive movement when warm and interferes with tight packing when cold.','location_description':'The final gate is a temperature tunnel containing the repaired bilayer. Cholesterol molecules sit between phospholipid tails. The tunnel alternates between warm red light and cold blue light while a fluidity meter records membrane behavior.','orientation':'Warm test is left, cholesterol-filled bilayer is center, and cold test is right.','zones':[zone('left','Warm chamber','HOT','Phospholipid motion increases; cholesterol restrains excessive movement.'),zone('center','Cholesterol in bilayer','CHOL','Sits among phospholipid tails as a membrane component.'),zone('right','Cold chamber','COLD','Cholesterol interferes with tight phospholipid packing as temperature falls.')],
'cast':[cast('Cholesterol','steroid membrane lipid','a small four-ring molecule wedged between phospholipid tails','acts as a membrane-fluidity buffer in animal cell membranes across changing temperatures')],
'paragraphs':['Lena inserts **cholesterol** between the phospholipid tails. Cholesterol is a steroid and a common component of animal cell membranes.', 'The tunnel warms. Phospholipid motion increases, but cholesterol restrains some of that movement. The tunnel then turns cold. As phospholipids tend to pack more tightly, cholesterol interferes with that close packing.', 'That two-direction effect is why cholesterol is best remembered as a **membrane-fluidity buffer**, not as a molecule that simply “makes membranes rigid.” It helps maintain membrane properties across temperature changes.', 'The fluidity meter settles in the safe range. Lena rotates the tablet toward you: fat storage, fatty-acid saturation, phospholipid amphipathic structure, bilayer assembly, steroid rings, and cholesterol now belong to one connected membrane story.'] ,'checkpoint_object_id':'MO-APBIO-U1-LIP019','checkpoint_prompt':'Which steroid lipid in animal membranes buffers fluidity by restraining movement when warm and interfering with tight packing when cold?'}
]
