from __future__ import annotations
import json, hashlib, re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
U4=ROOT/'content'/'ap-biology'/'unit-4'
F3=json.loads((U4/'briefs'/'scene-briefs-f3.json').read_text(encoding='utf-8'))['scene_briefs']
JBRIEFS=json.loads((U4/'briefs'/'journey-briefs-f3.json').read_text(encoding='utf-8'))['journeys']
J7=next(j for j in JBRIEFS if j['journey_id']=='U4-J7')
B={b['locus_id']:b for b in F3 if b['journey_id']=='U4-J7'}

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

LOCK_F=json.loads((U4/'content-lock-f4f.json').read_text(encoding='utf-8'))
PREV=[]
for jid in ('U4-J1','U4-J2','U4-J3','U4-J4','U4-J5','U4-J6'):
    rel=f'journeys/{jid}.json'; p=U4/rel
    if not p.exists(): raise RuntimeError(f'F4G requires locked predecessor {rel}')
    expected=LOCK_F['files'][rel]
    if p.stat().st_size!=expected['bytes'] or sha(p)!=expected['sha256']:
        raise RuntimeError(f'F4G refuses to proceed because locked predecessor changed: {rel}')
    PREV.append(json.loads(p.read_text(encoding='utf-8')))
J1,J2,J3,J4,J5,J6=PREV

GUIDE={
 'name':'Dr. Mira Chen','role':'cellular-systems investigator',
 'visual':'charcoal field jacket, clear protective glasses, and a compact white tablet clipped beside a thick model-cell security file whose tabs show DNA status, spindle attachment, external growth cues, cyclin/CDK state, and the current cell-fate decision',
 'story_job':'Mira treats every checkpoint and proliferation decision as an evidence-based security decision. She keeps the file visible so the learner can see which information entered a control system and why the cell was allowed to proceed, pause, repair, exit, die, or progress abnormally.'
}
FILE_CAST={
 'name':'Model-cell security file','kind':'continuity record',
 'visual':'a thick transparent case file with five fixed tabs—DNA STATUS, SPINDLE ATTACHMENT, GROWTH CUES, CYCLIN/CDK STATE, and DECISION—and a large stamp window that can display PROCEED, PAUSE, REPAIR, EXIT, APOPTOSIS, or ABNORMAL PROGRESSION',
 'job':'carries the evidence and decision state from one security station to the next so checkpoint control, apoptosis, proliferation signals, and cancer-control failure remain causally connected'
}

route=[
 {'scene_index':0,'locus':'Checkpoint Command Map','short':'Checkpoint map','floor':'Security atrium','symbol':'✓'},
 {'scene_index':1,'locus':'G1 Commitment Gate','short':'G1 gate','floor':'Commitment corridor','symbol':'G1'},
 {'scene_index':2,'locus':'G2 DNA-Integrity Gate','short':'G2 gate','floor':'Integrity corridor','symbol':'G2'},
 {'scene_index':3,'locus':'Spindle-Assembly Checkpoint','short':'Spindle checkpoint','floor':'Attachment control','symbol':'SAC'},
 {'scene_index':4,'locus':'Apoptosis Safety Exit','short':'Apoptosis','floor':'Safety exit','symbol':'×'},
 {'scene_index':5,'locus':'Cyclin–CDK Control Rack','short':'Cyclin–CDK','floor':'Molecular control room','symbol':'CDK'},
 {'scene_index':6,'locus':'Growth and Attachment Signals Bay','short':'External growth cues','floor':'Environmental signals bay','symbol':'↗'},
 {'scene_index':7,'locus':'Cancer Control-Failure Board','short':'Cancer control failure','floor':'Failure-analysis room','symbol':'!'},
 {'scene_index':8,'locus':'Tumor Progression Corridor','short':'Tumor progression','floor':'Progression corridor','symbol':'⇢'},
 {'scene_index':9,'locus':'Carcinogen Risk Bay','short':'Carcinogen risk','floor':'Risk bay','symbol':'UV'},
]

NARR={
'U4-L42':{
 'title':'The Headquarters That Stamped PROCEED on Everything','kicker':'A checkpoint is a decision point, not another phase of the cell cycle.',
 'paragraphs':[
  "The doors from Mitosis Transit Hall open into the circular atrium of **Checkpoint Command Map**, and the first thing you hear is the hard thump of a rubber stamp. On your **left**, a conveyor delivers cellular reports: DNA status cards, growth-signal receipts, nutrient conditions, and spindle-attachment notices. Directly **ahead**, a tall decision console sits under a ring of branching arrows. On your **right**, five doors are labeled PROCEED, PAUSE, EXIT, REPAIR, and CELL REMOVAL. A model-cell security file slides onto the center console. Its DNA tab is flashing amber and its spindle tab is incomplete, yet a mechanical arm stamps PROCEED across the cover. Mira catches the file before it reaches the right-hand door. The headquarters has not lost information. It has lost the ability to use information when making a division decision.",
  "Mira resets the console and feeds the reports through one at a time. A favorable report can open a progression route. A problem can hold the file in place, direct it toward repair, divert it out of the active cycle, or activate another safety response. These regulatory decision points are **cell-cycle checkpoints**. The broader control system does not behave like a rigid row of extra cell-cycle phases. A **checkpoint** is a regulatory control point where internal and external information influences what the cell does next. Mira places a bright border around the center console and then places the G1, G2, and spindle-related decision gates farther along a map. Their jobs overlap in the general sense that they regulate progression, but they inspect different kinds of information at different times.",
  "To make the distinction harder to blur, Mira sends three copies of the file icon toward three different right-hand outcomes. One stops temporarily under PAUSE. One routes toward a repair desk. One is sent toward the safety-removal corridor. She circles the words on the file and points to the physical paths. A checkpoint is the decision control. **Cell-cycle arrest** will later mean a pause in progression. **Apoptosis** will mean a regulated programmed cell-death response. They are related parts of a safety system, yet they are not interchangeable names for the same event. The file now records not just the decision but the evidence that produced it.",
  "The command map darkens except for the first major branch, G1. On the left wall, a cell fresh from division is shown growing in an ordinary environment. Ahead, a gate stands before a bright S-phase corridor. To the right of that gate, a side door leads away from active cycling. Mira slides the same security file onto the G1 track and removes the false PROCEED stamp. The next decision must occur before DNA synthesis is committed. The headquarters will have to consider growth conditions, extracellular signals, and DNA integrity together, then decide whether the cell enters S phase, pauses, or moves into a nondividing state."
 ],
 'close':'The command map now distinguishes a checkpoint from the possible outcomes it controls. The first unresolved file reaches the G1 commitment decision, so Mira carries it into the G1 Commitment Gate.'
},
'U4-L43':{
 'title':'The Gate Before the Copy Room','kicker':'G1 integrates whether the cell is ready to commit toward DNA synthesis.',
 'paragraphs':[
  "You enter **G1 Commitment Gate** through a narrow corridor that ends at a sealed door marked S PHASE. On your **left**, the model cell stands beside three inspection panels: one reports growth and nutrient conditions, one displays extracellular signaling cues, and one shows the current DNA-integrity report. Directly **ahead**, the G1 decision gate blocks the route toward DNA synthesis. On your **right**, the corridor splits. The upper branch leads into S phase. The lower branch bends into a quieter side chamber marked G0. Mira clips the security file to the gate so all three left-side reports remain visible while the decision is made.",
  "First she gives the model cell adequate growth conditions, an appropriate pro-proliferation signal, and an acceptable DNA report. The central gate unlocks and the S-phase branch glows. This is the **G1 checkpoint** in the model: a major commitment decision where cell growth conditions, signaling cues, and DNA integrity influence whether the cell continues toward DNA synthesis or remains outside that progression. Mira then removes the growth signal and introduces a warning on the DNA panel. The S-phase door closes. The important feature is not that one particular condition always determines the answer. The gate integrates information that is relevant to whether continued cycling is appropriate.",
  "The lower branch now opens. A cell moving into **G0** leaves the active division cycle and enters a nondividing state. Mira sends one cell model down that branch, then places two different clocks above it. On one clock, a later signal allows reentry into the cycle. On the other, time advances while the cell remains specialized and nondividing for a long period. G0 therefore is not a synonym for G1 and is not automatically a permanent dead end. Some cells can reenter the cycle, while many terminally differentiated cells remain nondividing for long periods. Mira keeps G1 phase, its G1 checkpoint, and the G0 branch as three separate visual locations.",
  "An optional Quick Recall can now hide the labels and leave only the geometry. What information can influence the G1 checkpoint decision? You should be able to reconstruct the left-side growth conditions and signaling cues, the DNA-integrity report, the center gate, and the two right-side outcomes. Mira does not call this checkpoint universally the single most important checkpoint. It is a major commitment point, and its importance depends on biological context. The security file receives a temporary clearance and moves through a simulated S phase. When it returns, the DNA tab has changed from 'ready to copy' to 'replication complete?' A red crack appears across one DNA icon. The cell has passed the first commitment decision, but before mitosis it needs a different kind of inspection."
 ],
 'close':'The G1 gate can authorize S-phase entry or divert a cell toward pause or G0. After replication, the same file now carries a DNA-integrity problem to the G2 DNA-Integrity Gate.'
},
'U4-L44':{
 'title':'The Door That Refuses Damaged Cargo','kicker':'G2 can delay mitotic entry when replication is incomplete or DNA damage remains unresolved.',
 'paragraphs':[
  "The corridor opens into **G2 DNA-Integrity Gate**, a bright inspection room immediately before the entrance to mitosis. On your **left**, two large status panels show whether DNA replication has been completed and whether DNA damage remains. Directly **ahead**, the G2 control gate sits behind a red horizontal barrier. On your **right**, three work bays are labeled REPAIR, DELAYED ENTRY, and OTHER RESPONSE. The security file arrives with one replication-status box incomplete and a persistent damage warning. The old headquarters program tries to lift the barrier anyway. Mira slams the emergency stop and pins the file beneath the center scanner.",
  "With the abnormal report visible, the barrier stays closed. This is the **G2 checkpoint**. It helps prevent entry into mitosis when DNA replication is incomplete or DNA damage remains unresolved. Mira flips the file from PROCEED to PAUSE. That temporary halt is **cell-cycle arrest**, a pause in progression that can provide time for repair or prevent segregation and division under unsuitable conditions. The cell has not been sent backward into S phase as a magical reset, and arrest itself is not the same as cell death. The physical picture is a stopped file at a gate, not a destroyed file.",
  "The DNA warning also activates a broader **DNA-damage response**. Repair machinery appears in the right-hand bay. Beside it, Mira reveals several possible longer-term outcomes: continued arrest, senescence, apoptosis, or other context-dependent responses. She deliberately refuses to connect the damaged-DNA panel directly to an automatic death chute. Persistent damage can lead to different outcomes depending on cell type, damage, signaling context, and regulatory state. Apoptosis will be one important safety response later, but the story does not encode 'irreparable damage always equals apoptosis.' When the simulated damage is repaired and the replication report becomes acceptable, the G2 barrier can finally lift.",
  "Mira stamps the evidence into the file and sends the model cell toward mitosis. The DNA tab is green now, but the spindle-attachment tab remains blank. Before the file leaves, she briefly resets the damage warning without repairing it and lets the red barrier remain down for another few seconds. The pause itself does not fix DNA. It creates time in which repair or another response can occur. That distinction gives **cell-cycle arrest** a concrete job and keeps it separate from the molecular repair machinery. Through a window on the right, you can see a metaphase-stage cell with one chromosome tilted away from the equator and one kinetochore lacking an adequate spindle attachment. The old system again flashes PROCEED TO ANAPHASE. Mira points to the difference between the current problem and the one you just solved. G2 checked premitotic DNA status. The next gate will inspect chromosome attachment and alignment after the spindle has formed."
 ],
 'close':'G2 has delayed mitotic entry until replication and DNA status are acceptable. The file now reaches a metaphase-stage attachment problem, leading directly to the Spindle-Assembly Checkpoint.'
},
'U4-L45':{
 'title':'One Bad Attachment Holds the Whole Gate','kicker':'Anaphase waits until chromosome attachment and alignment are adequate.',
 'paragraphs':[
  "You step into **Spindle-Assembly Checkpoint**, a narrow chamber built around a metaphase cell. On your **left**, one replicated chromosome is visibly misaligned, with an inadequate kinetochore-microtubule attachment. Directly **ahead**, a heavy gate labeled ANAPHASE spans the spindle midline. On your **right**, the daughter-chromosome tracks from Journey 6 are visible but empty. Mira clips the security file above the gate. Its DNA tab is green, but the spindle-attachment tab flashes red. The headquarters has reached the point where a cell can have intact DNA and still be unsafe to segregate chromosomes.",
  "The anaphase gate remains locked while the defective attachment persists. This control is the **spindle assembly checkpoint**. It delays anaphase until chromosomes have appropriate kinetochore-microtubule attachment and alignment. Mira corrects the model so spindle microtubules make adequate attachments and the chromosome joins the metaphase alignment. Only then does the warning clear and the gate release. The stage does not advance because a timer expired. The permission changes after the attachment state becomes acceptable.",
  "Mira then sprays a simulated microtubule-disrupting treatment into the model. The spindle becomes disorganized and chromosome attachment fails. The checkpoint warning returns, and anaphase permission stays closed. She points to the causal order. A microtubule-disrupting drug can impair spindle formation or attachment, which activates checkpoint control and prevents normal progression into anaphase. It is misleading to say the drug simply 'damages anaphase' as though anaphase were already proceeding normally. The problem appears upstream, in the machinery and attachment state required before anaphase can begin.",
  "The model resets with proper attachment and safely completes the checkpoint test. Mira stamps SPINDLE VERIFIED on the file, then runs one final contrast. She leaves every kinetochore attachment adequate but places a DNA-damage card back on the file. The spindle gate does not suddenly become the G2 gate. Each checkpoint is tied to the class of information it evaluates, even though the larger control system coordinates the results. She then opens a dark side corridor that did not appear on the ordinary cycle map. Its sign does not say PAUSE. It says SAFETY EXIT. The file now receives a different test condition: damage so severe, or a cellular state so dangerous, that allowing continued survival and proliferation would be risky. A checkpoint can pause progression, but some circumstances call for regulated removal of the cell itself. The right-hand corridor leads away from the cycle into a quiet chamber where the cell is dismantled in an orderly way."
 ],
 'close':'The spindle checkpoint protects chromosome segregation by withholding anaphase permission until attachment and alignment are adequate. A different safety problem now sends the file into the Apoptosis Safety Exit.'
},
'U4-L46':{
 'title':'The Exit That Dismantles the Cell on Purpose','kicker':'Apoptosis is an organized cell-fate program, not a synonym for any kind of cell death.',
 'paragraphs':[
  "The **Apoptosis Safety Exit** is unexpectedly quiet. On your **left**, the model-cell security file carries a severe damage signal and a bright warning that continued survival may be dangerous. Directly **ahead**, a sealed chamber contains the regulated cell-death program. On your **right**, small membrane-bound fragments are collected by cleanup cells without spilling the entire cell contents across the floor. Mira places the damaged model cell into the center chamber and closes the transparent door. Nothing explodes. Nothing is portrayed as an accidental rupture.",
  "The central program activates in an ordered sequence. The model cell shrinks, internal structures are dismantled in a regulated manner, and the cell is packaged for removal. This is **apoptosis**, regulated programmed cell death that can remove damaged, unnecessary, or potentially dangerous cells. Mira stamps the continuity file DIVISION STOPPED / CELL REMOVED. That outcome is different from cell-cycle arrest. Arrest is a pause in progression. Apoptosis is a regulated cell-fate program that removes the cell. The word is also kept distinct from accidental necrotic cell death, which can involve uncontrolled membrane damage and inflammatory consequences.",
  "Mira reopens the security map from the first room. The checkpoint symbol appears at one decision point, PAUSE appears on a separate branch, and APOPTOSIS appears on this removal route. She traces them with three separate fingers so no one label can stand in for the entire safety system. A checkpoint may help determine whether progression should continue. Arrest may provide time for repair or enforce a stop. Apoptosis may remove a cell when regulated signaling drives programmed death. The biological pathways can interact, but the meanings remain different.",
  "The damaged test cell has now been removed, so Mira does not pretend it can stroll into the next room. Instead, she closes that case entry and flips the same security file to a healthy-control tab. The file itself remains the continuity object, but the new model cell is healthy and cycling. Before leaving, she places an accidentally ruptured cell beside the orderly apoptosis chamber. Its membrane is visibly compromised and its contents spill into the surrounding model space. She does not ask you to memorize a separate death pathway here; the comparison exists only to protect the definition. **Apoptosis** is regulated programmed cell death, not a blanket term for every way a cell can die. Mira points to the headquarters clock. Checkpoints explain permission decisions, yet a healthy cell still needs molecular machinery that drives scheduled transitions. Four empty slots on the file are labeled CYCLIN, CDK, COMPLEX, and TARGET. Ahead, a rack of protein regulators rises and falls with the cycle like a mechanical tide."
 ],
 'close':'Apoptosis has removed the dangerous test cell through regulated programmed death. Mira keeps the same security file, opens its healthy-control tab, and follows the question of what drives normal progression into the Cyclin–CDK Control Rack.'
},
'U4-L47':{
 'title':'The Regulator That Has to Find Its Kinase','kicker':'Cyclin levels change, CDKs are kinases, and the active complex acts on cell-cycle targets.',
 'paragraphs':[
  "The **Cyclin–CDK Control Rack** fills an entire wall with moving protein models. On your **left**, vertical gauges show the concentration of different cyclin regulators rising and falling as a model cell proceeds through the cycle. Directly **ahead**, a row of cyclin-dependent kinase molecules waits in docking cradles. On your **right**, target proteins sit beneath phosphate indicators beside cell-cycle event panels. Mira opens the healthy-control security file and places its CYCLIN/CDK STATE tab under the center rack. A CDK by itself remains relatively inactive in this simplified interaction. Then the appropriate cyclin level rises on the left and a cyclin docks with the kinase.",
  "The overall mechanism is **cyclin-CDK control**: interactions between cyclins and cyclin-dependent kinases regulate progression through the cell cycle. A **cyclin** is a regulatory protein whose concentration often rises and falls during the cell cycle and whose binding helps activate a cyclin-dependent kinase. Mira keeps the cyclin physically on the left until it binds, so the regulator is not confused with the enzyme. The central enzyme is a **cyclin-dependent kinase (CDK)**, a protein kinase whose activity depends on regulatory interactions including cyclin binding. Its name tells you what kind of enzyme it is and why the cyclin matters.",
  "Once cyclin and CDK are together in the active state, Mira labels the central pair the **cyclin-CDK complex**. The complex phosphorylates selected target proteins on the right. Those targets help promote or regulate particular cell-cycle events. The arrows point from changing cyclin availability to regulated kinase activity and then to phosphorylated targets. Later, cyclin levels or other regulatory conditions change and the activity falls. The room therefore links a changing regulator, a kinase, an active complex, and target phosphorylation without making those four terms interchangeable.",
  "The optional Quick Recall hides the labels and asks for the functional relationship among cyclin, CDK, and the cyclin-CDK complex. Mira accepts a mechanistic reconstruction: cyclin binding helps regulate or activate the CDK, and the active complex phosphorylates target proteins that regulate cell-cycle events. She then sweeps away a long catalog of named cyclin/CDK pairings that the old headquarters tried to force into the file. The general interaction is the mechanism that matters here; a long catalog of named pairings would hide the simpler causal pattern the rack is showing. When the rack is stable, three external lights begin flashing from the next bay: a growth-factor signal, a crowding sensor, and an attachment sensor. The internal engine works, but it cannot make every proliferation decision in isolation from the environment."
 ],
 'close':'Cyclin–CDK regulation provides an internal molecular engine for cell-cycle progression. External growth, crowding, and anchorage information now enters the security file at Growth and Attachment Signals Bay.'
},
'U4-L48':{
 'title':'The Cell Has to Read the Room','kicker':'Normal proliferation decisions respond to extracellular growth signals, crowding, and attachment context.',
 'paragraphs':[
  "You enter **Growth and Attachment Signals Bay**, a broad room with three experimental platforms. On your **left**, a receptor-bearing cell faces a dispenser of extracellular growth-factor molecules. Directly **ahead**, identical cells occupy a culture surface whose density can be increased from sparse to crowded. On your **right**, one normal animal cell is attached to an appropriate extracellular-matrix-like substrate while a second is suspended without attachment. Mira clips the security file above all three platforms. Its cyclin/CDK tab is ready, but the DECISION field remains blank because the cell has not yet read its surroundings.",
  "Mira releases a growth factor on the left. It binds its receptor and activates a signal-transduction pathway that influences cyclin/CDK activity and the decision to progress through the cycle. This is **growth-factor cell-cycle signaling**. The growth factor is an extracellular signaling molecule. Mira places a large crossed-out label over the word HORMONE because growth factors are not universally hormones; many act locally. The important link is signaling from outside the cell into regulatory pathways that can alter the internal cell-cycle machinery.",
  "At the center platform, Mira increases cell number until neighbors make extensive contact. Proliferation in the normal-cell model slows. This commonly described response is **density-dependent inhibition**: many normal animal cells reduce proliferation when cell density or contact signals indicate crowded conditions. On the right platform, the attached cell receives an appropriate substrate context and can proliferate under suitable conditions, while the unattached model does not. This requirement in many normal animal cells is called **anchorage dependence**. Mira keeps both labels small and specific so these useful patterns do not become universal definitions of normal or cancer cells.",
  "The three platforms remain visible at once. Growth-factor signaling is an extracellular cue that can promote proliferation through signaling pathways. Density-dependent inhibition concerns responses to crowded/contact conditions. Anchorage dependence concerns attachment to an appropriate substrate or extracellular matrix. Mira prevents the terms from collapsing into a single idea called 'growth control.' She then disables all three restraints in a simulation. The model cell responds excessively to proliferative input, ignores crowding, and continues dividing without normal attachment context. The security file begins filling with additional abnormalities, each logged in a separate field. Mira does not call any one of these changes 'the definition of cancer.' Instead, she follows the accumulating failures toward a large black board where proliferation control, DNA maintenance, checkpoints, and cell-death systems are connected by dozens of wires."
 ],
 'close':'External signals and physical context normally contribute to proliferation decisions. With several restraints disabled, the altered file moves to the Cancer Control-Failure Board to examine how multiple regulatory failures accumulate.'
},
'U4-L49':{
 'title':'Cancer Is More Than a Fast Division Switch','kicker':'Malignant behavior emerges through accumulated failures in several regulatory systems.',
 'paragraphs':[
  "The **Cancer Control-Failure Board** looks like the security headquarters after a storm. On your **left**, cards representing genetic and epigenetic alterations accumulate in a deep tray beside pathways for proliferation control, genome maintenance, and cell death. Directly **ahead**, the cell-control network is wired across a black board. Several connections are broken, others are stuck active, and warning lights no longer halt the system. On your **right**, the model cell keeps proliferating while checkpoint and apoptosis barriers fail to restrain it. Mira lays the security file open across the center so every abnormal behavior can be traced to a specific regulatory failure rather than reduced to one dramatic symptom or one oversized warning light.",
  "The broad relationship is **disrupted cell-cycle control**: disruptions to cell-cycle regulation can contribute to cancer or trigger apoptosis, depending on what has been altered and how the cell responds. Mira then names **cancer** more carefully. Cancer is a disease of dysregulated cell behavior in which genetic or epigenetic changes enable uncontrolled proliferation and other malignant properties. She darkens a giant sign that reads CANCER = CELLS DIVIDE FAST. Rapid or uncontrolled proliferation is important, but cancer biology also involves altered survival, genome maintenance, tissue invasion, interaction with the environment, and other malignant behaviors.",
  "More alteration cards are added on the left over successive simulated generations. Some affect proliferation signaling, some checkpoint pathways, some genome maintenance, and some cell-death responses. These are **cancer-driver alterations** when they help drive malignant behavior. Mira refuses to stop at an arbitrary number. There is no universal fixed mutation threshold that defines cancer. Different cancers and individual tumors can carry very different sets and numbers of alterations, including drivers and many changes that do not themselves drive the disease. The meaningful story is accumulation and selection of alterations that change regulatory behavior, not a magic count.",
  "Two failures on the right receive their own labels. When altered cells bypass signals that would normally stop progression, the system demonstrates **checkpoint evasion in cancer**. When altered cells reduce normal programmed-death responses and survive serious abnormalities, the system demonstrates **apoptosis evasion in cancer**. Mira keeps those mechanisms separate even though both remove restraints on abnormal populations. The file now describes a dysregulated cell population, but the next corridor asks a different question. Does an abnormal proliferating mass remain localized, invade nearby tissue, or spread to distant sites? The terms tumor, benign, malignant, and metastasis cannot be inferred from division rate alone."
 ],
 'close':'The failure board now shows cancer as accumulated dysregulation involving proliferation, checkpoints, survival, and related systems without a fixed mutation count. The altered population moves into Tumor Progression Corridor to distinguish localization, invasion, and distant spread.'
},
'U4-L50':{
 'title':'The Corridor Where “Tumor” Splits Into Different Outcomes','kicker':'Localized mass, invasive malignancy, and distant spread are different biological states.',
 'paragraphs':[
  "The **Tumor Progression Corridor** is divided into three long sections by transparent walls. On your **left**, a compact mass of abnormally proliferating cells sits inside a clearly bounded tissue compartment. Directly **ahead**, a second mass has breached its local boundary and sends invasive cells into neighboring tissue. On your **right**, a transport channel leads to a distant organ model where a small secondary growth can form. Mira places the security file on a rail that runs past all three zones. The old headquarters had labeled the entire corridor simply TUMOR, which makes it impossible to distinguish what the cells are actually doing.",
  "Mira begins with the general term **tumor**, a mass of abnormally proliferating cells. Tumors may be benign or malignant. She keeps the localized left-side mass contained and labels it a **benign tumor**. It is a nonmalignant localized mass whose cells do not invade surrounding tissue or metastasize. A large red arrow reading CANCER LATER is removed from the wall. Benign does not mean a tumor is simply waiting to become cancer. Some benign tumors can still cause significant clinical problems because of size, location, secretion, or other effects, but the term itself does not mean malignant.",
  "At center, the boundary is breached. The invasive mass is labeled a **malignant tumor** because it contains cancer cells capable of invasive growth and potentially spread to distant sites. Mira then allows some malignant cells to enter the right-side transport route, survive the journey, leave the circulation, and establish a secondary growth at a distant site. That distant spread is **metastasis**. The primary tumor, invasive behavior, and distant secondary growth remain physically separated so the terms cannot collapse together. Malignancy involves invasive cancer behavior; metastasis specifically describes spread from a primary site to distant locations where secondary tumors may form.",
  "A separate counter above the corridor shows another property many transformed populations can acquire: very extensive or indefinite proliferative capacity, often called **replicative immortality**. Mira lets the population continue through many rounds in the model, then removes a sign that says EVERY CANCER CELL LIVES FOREVER. Replicative immortality is a common acquired property of many transformed or cancer cell populations, especially evident in culture models, but it is not a literal guarantee that every individual cancer cell divides indefinitely. The optional Quick Recall now hides all labels and asks you to distinguish benign tumor, malignant tumor, and metastasis from the left-center-right geometry. When the corridor reappears, Mira closes the file on a final question: what kinds of exposures can increase the chance that DNA-damaging alterations enter such a multistep process in the first place?"
 ],
 'close':'The corridor now distinguishes a tumor from benign localization, malignant invasion, metastasis, and extended proliferative capacity. The final security-file question leads to Carcinogen Risk Bay.'
},
'U4-L51':{
 'title':'The Risk Bay With Two Damaged DNA Models','kicker':'Carcinogen risk is tied to DNA-damaging exposures, while risk reduction changes probability rather than guaranteeing an outcome.',
 'paragraphs':[
  "The last door opens into **Carcinogen Risk Bay**. On your **left**, a skin-cell DNA model lies beneath an ultraviolet lamp whose beam can be turned up or shielded. Directly **ahead**, the security file rests on a risk console that records DNA damage and exposure history without pretending to predict an individual future with certainty. On your **right**, a lung-cell DNA model sits beside a chamber containing a simulated mixture of tobacco-smoke chemicals. Mira locks the two exposure systems apart. The bay is about evidence-based risk mechanisms, not a grab bag of lifestyle slogans.",
  "Mira activates the left lamp. Ultraviolet radiation strikes the DNA model and damage markers appear. This establishes **UV and skin-cancer risk**: ultraviolet radiation can damage DNA and increase skin-cancer risk. She then lowers the exposure and adds appropriate protective barriers. The number of new damage markers falls in the simulation. Reducing excessive UV exposure and using appropriate sun protection can reduce risk. Mira leaves the word 'reduce' illuminated. Risk reduction is not a guarantee that cancer can never occur, and ordinary sunlight is not portrayed as a mysterious poison. The biologically relevant mechanism is exposure to ultraviolet radiation and resulting DNA damage.",
  "On the right, Mira runs the tobacco-smoke simulation. Several carcinogenic compounds contact the DNA model and damage markers increase. This is **tobacco carcinogen risk**: tobacco smoke contains carcinogens that cause DNA damage and increase cancer risk. A separate nicotine card appears beside the chamber, labeled ADDICTIVE AGENT. Mira keeps it physically separate from the DNA-damaging carcinogen mixture. Nicotine is primarily responsible for addiction; it should not be taught as the main mutagenic carcinogen in tobacco smoke. That distinction lets the learner connect tobacco exposure to cancer risk without assigning the wrong molecular role to nicotine.",
  "The center console briefly displays two rejected claims from the malfunctioning headquarters: DRINK MORE WATER TO PREVENT CANCER DIRECTLY and AVOID FATTY FOODS BECAUSE FAT CAUSES CANCER. Mira deletes both from the mechanism board. Broad health behaviors can matter in many contexts, but this Unit 4 risk bay stays tied to supported mechanisms and does not invent generic direct causal rules. The security file is now thick with everything you have tracked through the headquarters: checkpoint decisions, G1 and G2 control, spindle attachment, arrest and repair, apoptosis, cyclin-CDK regulation, extracellular growth constraints, accumulated cancer-control failures, tumor behavior, metastasis, and DNA-damaging exposures.",
  "Mira carries the file back to a glass overlook above the entire ten-room route. The original false PROCEED stamp is still visible underneath the newer evidence marks. She asks you to reconstruct the headquarters without labels. Incoming information reaches checkpoints. G1 weighs commitment toward S phase or G0. G2 checks replication and damage before mitosis. The spindle checkpoint protects chromosome segregation. Apoptosis can remove dangerous cells. Cyclins and CDKs regulate scheduled progression, while extracellular signals and physical context influence proliferation. Cancer can emerge through accumulated regulatory failures, and malignant progression can include invasion and metastasis. DNA-damaging exposures such as UV radiation and tobacco-smoke carcinogens can increase cancer risk. The file finally receives no universal stamp at all. Its last field reads DECISION DEPENDS ON EVIDENCE."
 ],
 'close':'The final file contains no automatic PROCEED rule and no single-feature definition of cancer. The full Unit 4 narrative route is now complete, ready for finalization, Review, and application design in F5 rather than another story journey.'
}
}

# One concrete memory image per term; the science remains in the locked canonical statement.
def term_image(b,t):
    left=b['spatial_layout']['left']['anchor']; center=b['spatial_layout']['center']['anchor']; right=b['spatial_layout']['right']['anchor']
    return f"At {b['scene_title']}, use the fixed {left} → {center} → {right} mechanism to retrieve {t['canonical_term']}."

def scene_layout(b):
    zones=[]
    for pos in ('left','center','right'):
        z=b['spatial_layout'][pos]
        zones.append({'position':pos,'label':z['anchor'],'description':f"A conventional, clearly labeled scientific representation of {z['anchor']} fixed on the learner’s {pos} in {b['micro_anchor']}. {z['layout_job'].capitalize()}."})
    return {'orientation':f"Stand at the entrance to {b['scene_title']}. Keep {b['spatial_layout']['left']['anchor']} on your left, {b['spatial_layout']['center']['anchor']} directly ahead in the central action zone, and {b['spatial_layout']['right']['anchor']} on your right. Do not rotate the room while the mechanism runs.", 'zones':zones}

def cast_for(b):
    out=[{'name':GUIDE['name'],'kind':'guide','visual':GUIDE['visual'],'job':GUIDE['story_job']}]
    for pos,kind in [('left','scientific_part_or_reference'),('center','scientific_process_or_structure'),('right','scientific_part_or_output')]:
        z=b['spatial_layout'][pos]
        out.append({'name':z['anchor'],'kind':kind,'visual':f"A conventional scientific representation of {z['anchor']} fixed in the {pos} zone.",'job':z['layout_job']})
    out.append(FILE_CAST)
    return out

HINTS={
 'U4-L43':'Look at the three inspection panels on the left of the G1 gate: growth conditions, extracellular signaling cues, and DNA integrity. Then decide which route on the right can open.',
 'U4-L47':'Picture the cyclin gauge on the left, the CDK in the center, and the phosphorylated target on the right. Ask what cyclin binding changes and what the active complex does.',
 'U4-L50':'Rebuild the corridor from left to right: localized noninvasive mass, invasive malignant growth, then distant secondary growth reached by spread from the primary site.'
}

def make_scene(lid,idx):
    b=B[lid]; n=NARR[lid]; beats=[]; snaps=[]
    for t in b['term_introductions']:
        image=term_image(b,t)
        beats.append({'object_id':t['knowledge_id'],'term':t['canonical_term'],'story':image,'science':t['canonical_science'],'exact_name':bool(t.get('exact_name_recall')),'hint':image,'name_support':t['name_support']})
        snaps.append({'term':t['canonical_term'],'meaning':t['canonical_science'],'image':image})
    qr=b['quick_recall']; cp=bool(qr.get('enabled'))
    return {
      'scene_index':idx,'locus':b['scene_title'],'locus_id':lid,'title':n['title'],'scene_kicker':n['kicker'],
      'location_description':b['exact_location']+' — '+b['micro_anchor']+'.','scene_layout':scene_layout(b),'cast':cast_for(b),'continuity_object':J7['continuity_object'],
      'story_open':n['paragraphs'][0],'story_paragraphs':n['paragraphs'],'story_close':n['close'],'object_ids':b['knowledge_ids'],'story_beats':beats,'memory_snapshot':snaps,
      'misconception_guards':b['misconception_guards'],'exit_memory':b['exit_memory'],'checkpoint':cp,'checkpoint_object_id':b['primary_knowledge_id'],
      'checkpoint_prompt':qr.get('candidate_prompt','') if cp else '','checkpoint_answer':qr.get('answer','') if cp else '','checkpoint_hint':HINTS.get(lid,'') if cp else '',
      'next_locus':B[b['causal_transition']['to_locus_id']]['scene_title'] if b['causal_transition']['to_locus_id'] else None,'causal_transition':b['causal_transition']['transition_logic']
    }

lids=J7['route']; scenes=[make_scene(lid,i) for i,lid in enumerate(lids)]
journey={
 'palace_id':'U4-J7','palace_name':'Cell-Cycle Security Headquarters','story_title':'The Headquarters That Stamped PROCEED on Everything',
 'tagline':'One model-cell security file moves through ten decision rooms where normal checkpoint control is rebuilt before accumulated failures are followed into cancer progression and carcinogen risk.',
 'guide':GUIDE,'premise':J7['premise'],'mission':J7['mission'],
 'finale':'At the headquarters overlook, the learner can reconstruct cell-cycle control as a sequence of evidence-dependent decisions. Checkpoints remain distinct from arrest and apoptosis; cyclin–CDK activity remains linked to target phosphorylation; external growth conditions influence normal proliferation; cancer is understood as accumulated dysregulation with no fixed mutation count; benign tumors, malignant invasion, metastasis, and replicative capacity remain distinct; and UV radiation and tobacco-smoke carcinogens are tied to DNA-damage risk without unsupported prevention claims.',
 'estimated_minutes':46,'scene_count':len(scenes),'checkpoint_count':sum(bool(s['checkpoint']) for s in scenes),
 'learner_rule':'Read or listen while following the same model-cell security file. At every station, identify the incoming evidence on the left, the regulatory decision or mechanism at center, and the outcome on the right before naming the term. Quick Recall is optional during first exposure.',
 'route_orientation':'The Cell-Cycle Security Headquarters is one continuous ten-location route. Enter at the general checkpoint map, pass through G1, G2, spindle, apoptosis, cyclin–CDK, and external-growth control stations, then follow accumulated control failures through cancer, tumor progression, metastasis, and evidence-based carcinogen risk.',
 'route':route,'scenes':scenes,'student_release':'DEVELOPER_PREVIEW_F4G','narrative_standard':'V2-NARRATIVE-4.6-U4-F4G'
}
(U4/'journeys'/'U4-J7.json').write_text(json.dumps(journey,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

def card(j): return {k:j[k] for k in ['palace_id','palace_name','story_title','tagline','guide','premise','mission','finale','estimated_minutes','scene_count','checkpoint_count','narrative_standard']}
allj=(J1,J2,J3,J4,J5,J6,journey)
registry={'schema':'memory-palace-v2-unit4-f4g-registry-1.0','course_id':'ap-biology','unit_id':'unit-4','unit_title':'Cell Communication and Cell Cycle','narrative_standard':'V2-NARRATIVE-4.x-U4-F4G','journey_count':7,'scene_count':sum(x['scene_count'] for x in allj),'checkpoint_count':sum(x['checkpoint_count'] for x in allj),'guided_journeys':[card(x) for x in allj]}
(U4/'journeys-f4g.json').write_text(json.dumps(registry,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

status=json.loads((U4/'status-f4f.json').read_text(encoding='utf-8'))
status.update({'status':'F4G_ALL_7_JOURNEYS_POLISHED_DEVELOPER_PREVIEW','pipeline_status':'POLISHED_NARRATIVE_F4G','narrative_lock':'LOCKED_F4G_J1_J2_J3_J4_J5_J6_J7','student_release':False,'preview_release':True,'journey_count':7,'scene_count':51,'polished_journeys':7,'polished_scenes':51,'polished_checkpoint_count':18,'narrative_story_files':7,'next_required_output':'F5 Unit 4 finalization: build runtime Memory Objects, Review targets, confusable practice, Challenge Lab, full release accounting, and student-release QA without rewriting locked Journeys 1–7'})
(U4/'status-f4g.json').write_text(json.dumps(status,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (U4/'status.json').write_text(json.dumps(status,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

cp=ROOT/'content'/'ap-biology'/'course.json'; course=json.loads(cp.read_text(encoding='utf-8'))
for u in course['units']:
    if u['unit_id']=='unit-4':
        u.update({'status':'F4G_ALL_7_JOURNEYS_POLISHED_DEVELOPER_PREVIEW','journey_count':7,'scene_count':51,'source_status':'AUDITED_F1_ARCHITECTURE_F2_SCENE_BRIEFS_F3_ALL_7_JOURNEYS_POLISHED_F4G','polished_journeys':7,'polished_scenes':51,'student_release':False,'preview_release':True,'canonical_records':180})
cp.write_text(json.dumps(course,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

files=[*(f'journeys/U4-J{i}.json' for i in range(1,8)),'journeys-f4g.json','status-f4g.json']
lock={'schema':'memory-palace-v2-unit4-f4g-content-lock-1.0','unit_id':'unit-4','stage':'F4G','lock_status':'LOCKED_F4G_J1_J2_J3_J4_J5_J6_J7','student_release':False,'preview_release':True,'protected_predecessors':{rel:LOCK_F['files'][rel] for rel in (f'journeys/U4-J{i}.json' for i in range(1,7))},'files':{f:{'bytes':(U4/f).stat().st_size,'sha256':sha(U4/f)} for f in files}}
(U4/'content-lock-f4g.json').write_text(json.dumps(lock,indent=2)+'\n',encoding='utf-8')
manifest={'schema':'memory-palace-v2-unit4-f4g-release-manifest-1.0','unit_id':'unit-4','stage':'F4G','student_release':False,'preview_release':True,'canonical_records_protected':180,'polished_journeys':7,'polished_scenes':51,'journey_7_records':sum(len(s['object_ids']) for s in scenes),'journey_7_checkpoints':sum(bool(s['checkpoint']) for s in scenes),'journey_7_narrative_words':sum(len(re.findall(r"\b[\w’'-]+\b",' '.join(s['story_paragraphs']))) for s in scenes),'all_journey_checkpoints':registry['checkpoint_count'],'next_stage':'F5_UNIT4_FINALIZATION_AFTER_F4G_QA'}
(U4/'f4g-release-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')

doc=['# Unit 4 F4G · Journey 7 Narrative','',f"## {journey['story_title']}",'',journey['tagline'],'',f"**Guide**  {GUIDE['name']}, {GUIDE['role']}",'',f"**Premise**  {journey['premise']}",'',f"**Mission**  {journey['mission']}",'',f"**Route**  {' → '.join(r['locus'] for r in route)}",'', '> F4G is a developer narrative preview. Unit 4 remains `student_release: false`. Journeys 1–6 are protected byte-for-byte from F4F.','']
for s in scenes:
    doc += [f"## {s['scene_index']+1}. {s['locus']}",'',f"### {s['title']}",'',f"*{s['scene_kicker']}*",'',f"**Physical layout**  {s['scene_layout']['orientation']}",'']
    for p in s['story_paragraphs']: doc += [p,'']
    doc += [f"**Exit**  {s['story_close']}",'']
    if s['checkpoint']: doc += [f"**Optional Quick Recall**  {s['checkpoint_prompt']}",'']
doc += ['## Journey payoff','',journey['finale'],'']
(ROOT/'docs'/'UNIT4_F4G_JOURNEY7_STORY.md').write_text('\n'.join(doc),encoding='utf-8')
release_doc=f'''# Unit 4 F4G Release\n\n## Scope\n\nF4G adds only **Journey 7, Cell-Cycle Security Headquarters**. Journeys 1–6 remain protected byte-for-byte from F4F. F1 science, F2 architecture, and F3 scene briefs remain locked. All seven Unit 4 narrative journeys are now polished, but Unit 4 is still a developer preview until F5 constructs the runtime learning/review/application layer and passes final release QA.\n\n## Narrative release\n\n- Journey 7 title: **{journey['story_title']}**\n- Polished journeys: **7 / 7**\n- Polished scenes: **51 / 51**\n- Journey 7 knowledge records: **{manifest['journey_7_records']}**\n- Journey 7 narrative words: **{manifest['journey_7_narrative_words']}**\n- Journey 7 optional first-exposure recalls: **{manifest['journey_7_checkpoints']}**\n- All Unit 4 optional first-exposure recalls: **{manifest['all_journey_checkpoints']}**\n- Student release: **false**\n- Developer preview: **true**\n\n## Narrative standard\n\nJourney 7 uses one persistent model-cell security file to connect general checkpoints, G1/G2/spindle decisions, arrest, apoptosis, cyclin–CDK regulation, extracellular proliferation cues, cancer-control failure, tumor progression, metastasis, and carcinogen risk. The story keeps checkpoint, arrest, and apoptosis distinct; avoids ranking G1 as universally the single most important checkpoint; treats DNA-damage outcomes as context-dependent; prevents specific cyclin/CDK pair catalogs from becoming AP requirements; keeps growth factors from being universally classified as hormones; defines cancer as accumulated dysregulation without a fixed mutation threshold; separates tumor, benign tumor, malignant tumor, and metastasis; and ties UV/tobacco risk to DNA damage without unsupported prevention claims.\n\n## Next gate\n\nF5 must finalize Unit 4 without rewriting Journeys 1–7. It should build runtime Memory Objects, Review targets, confusable practice, the 15-item Challenge Lab, scope-guard exposure, release accounting, and the student-ready gate.\n'''
(ROOT/'docs'/'UNIT4_F4G_RELEASE.md').write_text(release_doc,encoding='utf-8')
print('Built Unit 4 F4G',json.dumps(manifest,indent=2))
