from __future__ import annotations
import json, hashlib, re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
U6=ROOT/'content'/'ap-biology'/'unit-6'
BRIEFS=json.loads((U6/'briefs'/'scene-briefs-f3.json').read_text(encoding='utf-8'))['scene_briefs']
JBRIEFS=json.loads((U6/'briefs'/'journey-briefs-f3.json').read_text(encoding='utf-8'))['journeys']
J4=next(j for j in JBRIEFS if j['journey_id']=='U6-J4')
B={b['locus_id']:b for b in BRIEFS if b['journey_id']=='U6-J4'}
CANON={r['knowledge_id']:r for r in json.loads((U6/'source'/'canonical-unit6-f1.json').read_text(encoding='utf-8'))['canonical_catalog']}

GUIDE={
 'name':'Dr. Sora Han','role':'molecular-information systems director',
 'visual':'dark-cobalt lab coat, clear gloves, transparent 5′→3′ compass tablet, and a narrow copper information ledger',
 'story_job':'Sora keeps one tracked eukaryotic gene, its promoter-linked expression meter, and its chromatin-state strip identifiable through the regulation route. She uses separate bacterial operon models for trp and lac comparisons so those systems never become confused with the tracked eukaryotic gene.'
}

ROUTE=[
 {'scene_index':0,'locus':'Expression Control Room','short':'Control output','floor':'Control-center entrance','symbol':'ON↕'},
 {'scene_index':1,'locus':'Operon Architecture Board','short':'Operon','floor':'Bacterial comparison wing','symbol':'P|O|GENES'},
 {'scene_index':2,'locus':'trp Repressible Chamber','short':'trp repress','floor':'Bacterial chamber A','symbol':'trp↓'},
 {'scene_index':3,'locus':'lac Inducible Chamber','short':'lac induce','floor':'Bacterial chamber B','symbol':'lac↑'},
 {'scene_index':4,'locus':'Eukaryotic Regulation Layers','short':'Many layers','floor':'Eukaryotic control tower','symbol':'5 LAYERS'},
 {'scene_index':5,'locus':'Epigenetic Chromatin Room','short':'Chromatin','floor':'Chromatin floor','symbol':'DNA+HIST'},
 {'scene_index':6,'locus':'Promoter–Enhancer Recruitment Hall','short':'Recruit','floor':'Transcription floor','symbol':'PROM↔ENH'},
 {'scene_index':7,'locus':'Activator–Repressor Balance Gate','short':'Balance','floor':'Transcription gate','symbol':'+/−'},
 {'scene_index':8,'locus':'RNA-Level Regulation Suite','short':'RNA control','floor':'RNA floor','symbol':'RNA↺'},
 {'scene_index':9,'locus':'Expression Profile Console','short':'Profile','floor':'Output floor','symbol':'▥'},
 {'scene_index':10,'locus':'Cell Specialization Gallery','short':'Specialize','floor':'Cell-identity gallery','symbol':'CELL'},
 {'scene_index':11,'locus':'Developmental Sequence Hall','short':'Develop','floor':'Development hall','symbol':'1→2→3'},
]

ZONES={
'U6-L29':[
 ('left','constitutive-expression channel','STEADY','An identical gene model feeds a steady transcript and product stream on the left, establishing a reference for expression that remains active under the displayed conditions.'),
 ('center','regulatory DNA/protein control room','CTRL','The tracked gene sits under glass with its promoter, nearby regulatory DNA, regulatory proteins, chromatin strip, and expression meter all visible at once.'),
 ('right','inducible-expression channel','SIGNAL','A matching gene model on the right changes output only after a defined regulatory signal alters the control state.')],
'U6-L30':[
 ('left','promoter / operator inputs','P|O','A bacterial DNA rail begins with a promoter and a physically separate operator, both fixed before the coding region.'),
 ('center','operon architecture board','OPERON','A transparent board joins shared control DNA to a coordinated cluster of bacterial genes without turning the repressor protein into part of the DNA.'),
 ('right','structural genes / coordinated output','GENES','Several related structural genes produce a coordinated transcript/output when the control region permits transcription.')],
'U6-L31':[
 ('left','low-tryptophan inactive-repressor side','LOW trp','Low tryptophan leaves the trp repressor unable to bind its operator effectively, so the biosynthetic operon remains transcribable.'),
 ('center','trp operon repressible switch','trp OPERON','The center DNA model carries the trp control region and biosynthetic genes with an expression meter attached.'),
 ('right','tryptophan corepressor / active-repressor side','trp+REP','Abundant tryptophan binds the repressor protein, changes its conformation, and enables operator binding that reduces transcription.')],
'U6-L32':[
 ('left','repressor-blocked operator side','REP BLOCK','The lac repressor occupies the operator when inducer is absent, keeping the bacterial lactose-use genes at low transcription.'),
 ('center','lac operon inducible switch','lac OPERON','A second bacterial DNA model keeps promoter, operator, and lac structural genes distinct while output is measured.'),
 ('right','allolactose inducer / structural-gene output side','ALLO→OUT','Allolactose binds the lac repressor, reduces operator binding, and permits transcription of bacterial lactose-use genes.')],
'U6-L33':[
 ('left','chromatin / transcription layer','DNA ACCESS','The tracked eukaryotic gene returns on the left with chromatin accessibility and transcription initiation controls visible.'),
 ('center','multi-stage regulation stack','LAYERS','A vertical transparent stack aligns chromatin, transcription, RNA processing/stability, translation, and protein-level control around the same gene-to-product route.'),
 ('right','RNA / translation / post-translation layer','RNA→PROTEIN','RNA handling, translation rate, and protein processing/stability controls occupy the right side without altering the tracked DNA sequence.')],
'U6-L34':[
 ('left','histone-acetylation side','Ac-HIST','The same DNA region is wrapped around histones whose acetylation state can change while the nucleotide sequence stays fixed.'),
 ('center','reversible epigenetic chromatin state','CHROMATIN','A central chromatin strip can open or compact and carries an expression meter, making accessibility and output visible together.'),
 ('right','DNA-methylation / inherited-state side','CH3-DNA','Methylation marks are added to the same DNA region while a cell-division display tests whether a regulatory state can persist through daughter cells.')],
'U6-L35':[
 ('left','promoter / nearby control side','PROM','The tracked gene’s promoter and nearby control DNA remain fixed beside the transcription start region on the left.'),
 ('center','transcription-machinery recruitment hall','RECRUIT','RNA polymerase and transcription factors gather at the center initiation platform when regulatory contacts support recruitment.'),
 ('right','enhancer / distant-position side','ENH','A distant enhancer/control element sits on a flexible DNA segment that can lie upstream or downstream and contact the promoter region by looping.')],
'U6-L36':[
 ('left','activator / positive regulation side','ACT','An activator can support transcriptional recruitment or activity on the left while the DNA sequence remains unchanged.'),
 ('center','transcriptional output balance','METER','The tracked gene and expression meter sit at center so changes in transcriptional output can be assigned to the regulatory input.'),
 ('right','repressor / negative regulation side','REP','A negative regulatory protein can reduce transcription through a specific regulatory interaction on the right.')],
'U6-L37':[
 ('left','alternative-splicing side','SPLICE','One pre-mRNA is processed into different mature RNA isoforms on the left without changing the underlying gene DNA.'),
 ('center','RNA-level regulation suite','RNA CTRL','The tracked transcript enters a center suite where stability and use can change after transcription.'),
 ('right','miRNA / siRNA small-RNA side','mi/siRNA','Small regulatory RNAs base-pair with target RNA on the right and can promote degradation or reduce translation.')],
'U6-L38':[
 ('left','gene-product amount / function input','PRODUCT','Bars for several transcripts and functional gene products show which outputs are abundant, scarce, active, or inactive.'),
 ('center','expression-profile phenotype console','PROFILE','A central console compares expression patterns across many genes while keeping the underlying genome constant.'),
 ('right','phenotypic output','PHENO','Observable cell properties change as the combination, amount, and function of gene products changes.')],
'U6-L39':[
 ('left','shared genome / inactive genes side','SAME DNA','Two model cells display the same chromosome set while different gene panels are silent or active.'),
 ('center','differential-expression specialization gallery','DIFF EXP','The same-genome cells pass through different expression programs, accumulating different sets of RNAs and proteins.'),
 ('right','tissue-specific protein / cell-identity side','IDENTITY','Distinct cell structures and tissue-specific products appear on the right, making specialization visible without changing the genome.')],
'U6-L40':[
 ('left','early determinants / induction side','EARLY SIGNALS','An egg/early-embryo model contains unevenly distributed cytoplasmic determinants while neighboring cells exchange inductive signals.'),
 ('center','sequential developmental gene-expression route','TF 1→2→3','A timed corridor activates transcription factors and downstream genes in sequence rather than all at once.'),
 ('right','patterning / morphogenesis / apoptosis side','FORM','Regional identity, coordinated changes in form, and programmed cell death shape the developing tissue on the right.')],
}

NARR={
'U6-L29':{
 'title':'The Building Where Every Cell Is Producing the Same Thing',
 'kicker':'The emergency is visible immediately. Identical DNA sequences are producing the wrong pattern of gene products because the control system has stopped distinguishing steady expression from regulated expression.',
 'paragraphs':[
  "The **Gene Control and Differentiation Center** opens into a three-lane room with a wall of model cells beyond the glass. Every cell carries the same highlighted gene sequence, yet every output meter has jammed at the same value. On your **left**, a **constitutive-expression channel** sends a steady stream of transcripts and gene product beneath a white lamp marked STEADY. Directly **ahead**, the **regulatory DNA/protein control room** holds the journey’s tracked eukaryotic gene under glass. Its promoter, nearby regulatory DNA, chromatin-state strip, transcript counter, and protein-output meter are all fixed in place. On your **right**, an **inducible-expression channel** is dark until a signal panel flashes. Dr. Sora Han clips the tracked gene’s sequence map into her copper ledger and places a seal over the nucleotide letters. That sequence will remain unchanged through the route. Only the regulatory conditions around it are allowed to move.",
  "Sora first turns to the center chamber. A regulatory DNA segment sits beside the tracked promoter, and a regulatory protein approaches that DNA without altering its sequence. When the protein binds, the transcription meter changes. When the interaction is reversed, the meter changes again. The DNA letters under the seal stay exactly the same. Only after you can see DNA sequence, regulatory protein, and transcription output as separate things does Sora name **Regulatory DNA sequences and proteins**. Regulatory DNA sequences interact with regulatory proteins to control transcription. The control system therefore works through molecular interactions with DNA and transcription machinery. A change in gene output does not require the gene itself to mutate.",
  "The left and right channels now make a second distinction. The left reference channel continues producing its gene product across the displayed conditions. Sora labels that pattern **constitutive expression**. Some genes are constitutively expressed under the relevant conditions because their products are required continuously or their regulatory state maintains ongoing transcription. The right channel behaves differently. Its output is low until an internal or environmental signal arrives. A regulatory protein changes state, the expression meter rises, and transcripts begin moving down the lane. Sora labels the pair **Constitutive and inducible expression**. Some genes are constitutively expressed while others are inducible in response to internal or environmental conditions.",
  "The room does not reduce regulation to two permanent categories. Sora keeps the tracked gene at center and varies only the regulatory condition. A signal can raise output, another control can reduce it, and the same gene can occupy different expression states in different cells or conditions. The useful memory is the causal arrangement. Regulatory DNA and regulatory proteins sit between a stable DNA sequence and a changing expression meter. Constitutive expression gives you a steady reference. Inducible expression shows that a gene’s output can change when regulatory conditions change. The meter records the consequence, while the sealed DNA sequence proves that expression regulation and mutation are different events.",
  "When the three lanes finally behave differently, the center wall opens downward into a bacterial comparison wing. Sora leaves the tracked eukaryotic gene sealed in a transparent carrier at the doorway so it cannot be confused with the bacterial models below. A long bacterial DNA rail appears in the next room with a promoter, a second regulatory site, and several related genes aligned in one row. The expression-control problem has narrowed. To understand how groups of prokaryotic genes can be coordinated, you must first learn the physical architecture of an **operon** at the **Operon Architecture Board**."
 ]},
'U6-L30':{
 'title':'One DNA Rail, Four Different Jobs',
 'kicker':'The bacterial comparison wing makes promoter, operator, structural genes, and repressor protein impossible to merge into one vague “switch.”',
 'paragraphs':[
  "You descend one level into a narrow bacterial control room. On your **left**, the DNA rail begins beneath two fixed plates labeled **promoter** and **operator**. Directly **ahead**, the **operon architecture board** magnifies the entire control region and the related genes beside it. On your **right**, three **structural genes** run in sequence toward a coordinated RNA-output display. Sora keeps the sealed eukaryotic gene carrier parked behind you and places a new cyan bacterial DNA model on the board. A separate gray protein floats above the rail. The room is arranged so DNA sites stay attached to DNA, coding regions stay downstream, and the movable regulatory protein can never be mistaken for one of the DNA elements.",
  "Sora points to the first DNA site. RNA polymerase can be recruited at the **promoter**. A short distance away, the **operator** is a regulatory DNA site where a repressor can influence transcription in the simplified bacterial model. The related coding regions farther to the right are structural genes. She traces the physical order and names the **Promoter–operator–structural gene model**. In this model, the promoter recruits RNA polymerase, the operator is regulatory DNA, and the adjacent structural genes encode related products. Each piece has a different job even though all three are part of one local regulatory arrangement on bacterial DNA.",
  "The gray protein now moves toward the operator. When it binds the regulatory DNA, transcription of the downstream gene set decreases. When it releases, RNA polymerase can again pass through the region under the appropriate conditions. Sora names the molecule **Repressor protein** only after its movement is visible. A repressor is a regulatory protein whose binding to regulatory DNA can decrease transcription. Its binding can be reversible and can be controlled by small molecules. The protein is diffusible. The operator stays in the DNA. Their interaction changes output without changing the operator sequence.",
  "Sora widens the board so promoter, operator, and related genes are enclosed by one illuminated bracket. The unit is an **Operon**, a cluster of functionally related bacterial genes regulated together from shared control DNA, allowing coordinated transcription. She then activates two neighboring bacterial cells and changes the same regulatory state in both. The entire related gene set changes output together. That behavior is **Coordinated prokaryotic operon regulation**. Prokaryotes can coordinately regulate groups of genes using inducible or repressible operons. The operon is the DNA/regulatory unit. The repressor is one kind of protein regulator that can act on it.",
  "The board now splits into two doors with opposite default states. The left door is labeled **trp** and shows biosynthetic genes that are transcribed when the end product is scarce. The right door is labeled **lac** and shows lactose-use genes whose transcription can rise when the substrate signal is present. Sora covers both labels for the optional Quick Recall and asks you to reconstruct the idea of coordinated operon regulation from the promoter, operator, repressor, and shared gene output you just watched. Then she opens the trp door first. The next chamber will show why a **repressible system** can be active until a corepressor helps shut it down."
 ]},
'U6-L31':{
 'title':'The Product That Helps Shut Down Its Own Production Line',
 'kicker':'The trp chamber turns feedback into a molecular event. Abundant tryptophan changes a repressor protein so the biosynthetic genes are transcribed less.',
 'paragraphs':[
  "The **trp Repressible Chamber** is divided by a single bacterial operon running across the center. On your **left**, the low-tryptophan side contains an inactive repressor that cannot bind the operator effectively. Directly **ahead**, the cyan **trp operon repressible switch** controls a set of tryptophan-biosynthesis genes and an expression meter. On your **right**, a tray of tryptophan molecules surrounds the same type of repressor protein beside the operator. Sora keeps the promoter, operator, and structural genes in the same positions you learned in the previous room. Only the small molecule concentration and the repressor’s binding state are allowed to change.",
  "Before touching the operon, Sora briefly reactivates a relationship from earlier biology. A small molecule binds a protein at a regulatory site, the protein changes conformation, and its activity changes. She labels the idea **Allosteric regulation review**. Binding of a regulatory molecule at an allosteric site can change protein conformation and activity, and the ligand does not have to be a substrate. The point here is protein-state control. The trp repressor is a regulatory protein. It is not being treated as an allosteric enzyme that catalyzes tryptophan synthesis.",
  "On the left, tryptophan is scarce. The repressor remains in a state with little operator-binding activity, so RNA polymerase can transcribe the tryptophan-biosynthesis genes. The expression meter stays high enough to support production of enzymes used in the pathway. Sora then moves several tryptophan molecules to the right side. Tryptophan binds the repressor and changes its conformation. The repressor can now bind the operator much more effectively. Transcription of the biosynthetic gene set falls. Only after that direction is visible does Sora name the **trp operon as repressible system**. In the E. coli trp operon, high tryptophan favors activation of the trp repressor through corepressor binding, reducing transcription of tryptophan-biosynthesis genes.",
  "Sora lifts one tryptophan molecule and places it beside the repressor rather than on the DNA. This molecule is **Tryptophan as corepressor**. Tryptophan functions as a corepressor by binding the trp repressor protein and enabling it to bind operator DNA. The word corepressor therefore describes the small molecule’s regulatory role in this system. It does not mean tryptophan itself is the DNA-binding protein. The repressor binds the operator. Tryptophan binds the repressor and helps place that protein in the operator-binding state.",
  "The output meter now behaves like a feedback device. When tryptophan is abundant, the cell has less need to express the biosynthetic genes at the same level, and repression increases. When tryptophan is low, that corepressor-dependent repression is relieved. A second door opens across the hall. Its default condition is visibly different. A repressor already blocks the operator until a lactose-derived signal changes its behavior. Sora leaves the trp chamber frozen in the high-tryptophan state so you can compare it directly with the **lac Inducible Chamber**, where an **inducer** will move regulation in the opposite functional direction."
 ]},
'U6-L32':{
 'title':'The Sugar Signal That Opens a Blocked Gate',
 'kicker':'The lac chamber begins with repression. Allolactose changes the repressor so transcription of bacterial lactose-use genes can proceed.',
 'paragraphs':[
  "The next room preserves the same three-part operon geometry but reverses the regulatory problem. On your **left**, the **repressor-blocked operator side** shows a lac repressor sitting on operator DNA while inducer is absent. Directly **ahead**, the **lac operon inducible switch** connects its promoter and operator to the lac structural genes. On your **right**, a clear tray labeled allolactose sits beside a second copy of the lac repressor and a product display for bacterial lactose-use proteins. The frozen trp chamber remains visible through the doorway behind you, making the contrast physical. The two systems share regulatory logic involving repressors and small molecules, yet the small molecule has a different effect on repressor function.",
  "At first, no inducer is present. The lac repressor binds operator DNA and reduces transcription of the downstream genes. Sora then adds allolactose to the right-side repressor. The protein changes conformation, and its operator-binding activity falls. The operator becomes less occupied by repressor, allowing transcription to proceed when the other required cellular conditions support lac expression. Only after the blocked gate opens does Sora name the **lac operon as inducible system**. In the E. coli lac operon, lactose availability can inactivate the lac repressor through allolactose, permitting transcription of genes involved in lactose uptake and metabolism.",
  "The small molecule itself receives a separate label. **Allolactose as inducer** means allolactose binds the lac repressor and reduces its operator-binding activity, acting as an inducer of lac-operon transcription. Sora places an allolactose token beside a tryptophan token from the previous room. The difference is diagnostic. Tryptophan functions as a corepressor in the trp system and promotes a repressor state that binds operator DNA. Allolactose functions as an inducer in the lac system and reduces the lac repressor’s operator-binding activity. The words corepressor and inducer describe opposite effects in these two model systems.",
  "The structural genes on the right now light one at a time. Sora labels the **lac structural gene products** accurately. The lac operon includes genes such as **lacZ**, which encodes **β-galactosidase**, and **lacY**, which encodes lactose permease. Another gene, lacA, encodes transacetylase. These are bacterial lactose-use proteins. The room never replaces them with the human intestinal enzyme lactase. The mnemonic anchor is therefore the bacterial operon and its real gene products, not a generic “lactase gene.”",
  "For the optional Quick Recall, Sora closes the allolactose tray and restores the left-side blocked state. She asks what kind of regulatory system can be induced when allolactose reduces repressor binding and transcription is permitted. Once the **lac operon as inducible system** is retrieved, the bacterial comparison wing powers down. Sora retrieves the sealed eukaryotic tracked gene from the entrance. Its promoter-linked expression meter and chromatin strip have not changed. An elevator rises into a much taller control tower with several floors. The next problem is larger than a single operon. Eukaryotic gene expression can be regulated at multiple stages, and the same tracked gene must remain recognizable across all of them."
 ]},
'U6-L33':{
 'title':'One Gene, Five Places Where Output Can Change',
 'kicker':'The eukaryotic control tower replaces a single local switch with a layered route from chromatin state to finished protein.',
 'paragraphs':[
  "The elevator opens into a tall room built around the tracked eukaryotic gene. On your **left**, the **chromatin / transcription layer** holds the same sealed DNA sequence, its promoter, nucleosomes, and a transcription-initiation platform. Directly **ahead**, a transparent **multi-stage regulation stack** rises through several floors. On your **right**, the **RNA / translation / post-translation layer** contains RNA-processing stations, ribosome controls, and protein-modification or stability controls. Sora reconnects the tracked gene to its expression meter. The DNA sequence still matches the copy you saw in the opening room. The new question is how many different control points can change the final amount or activity of gene product without altering that sequence.",
  "Sora begins at the bottom of the stack. Chromatin can be more or less accessible to transcription machinery. At the transcriptional level, regulatory DNA and transcription factors can change how frequently transcription begins. Above that, an RNA transcript can be processed in different ways or persist for different lengths of time. Translation can be increased or decreased. After a polypeptide is produced, protein modification, activation, localization, or degradation can change the amount of functional product. Sora labels this architecture **Multiple regulatory stages in eukaryotes**. Eukaryotic gene expression can be regulated at chromatin/transcriptional, RNA-processing/stability, translational, and post-translational stages.",
  "The stack makes a crucial relationship visible. A gene’s transcript counter can change even when protein output changes by a different amount, because regulation can occur after transcription as well. Conversely, an accessible gene can still produce little functional protein if later control points reduce RNA stability, translation, or protein persistence. Sora keeps every layer attached to the same gene-to-product path. The model therefore avoids the shortcut that gene regulation means only promoter on versus promoter off. She briefly freezes the transcript counter and changes only protein degradation on the top floor. The functional-protein meter falls while transcription is unchanged. Then she restores protein stability and changes RNA persistence instead. The output changes again from a different control layer, making the layered architecture impossible to collapse into one switch.",
  "She then lights several different gene panels across the room. The genes are located on different chromosome regions, yet the same transcription factor can recognize compatible control elements associated with more than one target. Their expression meters rise together. Sora names **Coordinated eukaryotic regulation**. Groups of eukaryotic genes can be coordinately regulated when they respond to the same transcription factors. Coordination therefore does not require the genes to be arranged together in one bacterial operon. Multiple eukaryotic genes can respond to shared regulatory factors even when they are physically separated in the genome.",
  "The stack now narrows to its first floor. The tracked gene’s chromatin strip changes from compact to more accessible and back again while its nucleotide sequence remains sealed. Sora points to the next door. Before transcription factors can recruit efficiently, DNA packaging itself can influence access. You enter the **Epigenetic Chromatin Room**, where histone and DNA modifications will change regulatory state while the DNA letters remain unchanged."
 ]},
'U6-L34':{
 'title':'The Chromatin Strip Changes While the DNA Letters Stay Sealed',
 'kicker':'Epigenetic regulation changes gene expression through DNA or histone modifications without rewriting the nucleotide sequence.',
 'paragraphs':[
  "The tracked gene enters a quiet room where every nucleotide letter is visible beneath a sealed transparent cover. On your **left**, the **histone-acetylation side** shows the same DNA wrapped around histones whose chemical marks can be altered. Directly **ahead**, the **reversible epigenetic chromatin state** strip connects chromatin accessibility to the expression meter. On your **right**, the **DNA-methylation / inherited-state side** places methylation marks on the same DNA region and follows the regulatory state through a model cell division. Sora does not allow the DNA sequence cover to open. Any change in transcription must therefore come from regulatory state rather than a nucleotide substitution, insertion, or deletion.",
  "At center, the chromatin strip loosens and compacts as chemical marks change. Sora names the broad mechanism **Reversible epigenetic regulation**. Reversible modifications of DNA or histones can alter gene expression without changing the DNA nucleotide sequence. The word epigenetic here refers to regulation associated with DNA or chromatin state. The tracked gene remains genetically the same sequence even when its accessibility or transcriptional potential changes.",
  "On the left, histone acetylation increases on the displayed locus and the chromatin becomes more accessible in this model. Sora names the observed relationship **Histone acetylation association**. Histone acetylation is commonly associated with more accessible chromatin and increased transcriptional potential at affected loci. She deliberately keeps the word commonly. Acetylation is not a universal command that forces every affected gene to be highly transcribed regardless of context. The effect depends on locus, interacting proteins, and the broader regulatory system.",
  "On the right, methylation marks appear on the same DNA region and the expression meter falls in the displayed context. Sora names **DNA methylation association**. DNA methylation can contribute to stable or reversible repression of gene expression in many eukaryotic contexts, depending on genomic location and regulatory system. The room therefore separates an association that is common in many contexts from an absolute rule. Histone acetylation and DNA methylation are also physically distinct modifications. One is a modification of histone proteins in this scene. The other is a modification of DNA.",
  "The cell-division display now copies the marked chromatin state into daughter-cell models with enough persistence to influence later expression. Sora labels the idea **Epigenetic state inheritance**. Some chromatin states and DNA or histone modifications can persist through cell division without altering nucleotide sequence. Transgenerational persistence depends on biological context and is not guaranteed by every epigenetic mark. To make the boundary unmistakable, she places a mutation card beside the sealed gene. A mutation would alter nucleotide sequence. The epigenetic state shown here changes regulation while the nucleotide sequence remains the same. The two routes may both influence phenotype, yet they are mechanistically different. For the optional Quick Recall, Sora covers the modification labels and asks what kind of regulation can change expression without changing DNA sequence. Once **Reversible epigenetic regulation** is retrieved, the chromatin door opens into a long hall where promoter DNA and a distant enhancer can physically contact the same transcription machinery."
 ]},
'U6-L35':{
 'title':'A Distant DNA Element Reaches the Promoter Without Moving the Gene',
 'kicker':'Promoters, enhancers, transcription factors, activators, and repressors remain separate structures whose interactions regulate transcription initiation.',
 'paragraphs':[
  "The tracked gene enters a hall built along one enormous DNA segment. On your **left**, the **promoter / nearby control side** sits beside the transcription start region. Directly **ahead**, the **transcription-machinery recruitment hall** contains RNA polymerase and several transcription factors waiting at an initiation platform. On your **right**, an **enhancer / distant-position side** lies far along the same flexible DNA, mounted so the DNA can loop through the air without changing its sequence. Sora keeps the promoter marker from the transcription journey and adds a distant control element to the same gene model. A small TATA panel hangs nearby as one possible promoter element in some eukaryotic genes, visibly subordinate to the larger promoter region.",
  "Sora activates a transcription factor that binds the promoter-associated region and another regulatory protein that binds the distant enhancer/control element. The DNA loops, bringing regulatory proteins into contact with the transcription-initiation machinery. RNA polymerase recruitment or initiation becomes more favorable and the expression meter rises. Only after the contact is visible does she name **Promoter/enhancer recruitment of transcription machinery**. RNA polymerase and transcription factors bind promoter or enhancer DNA sequences to regulate initiation of transcription. Promoters and enhancers are DNA sequences. The proteins that bind them are separate regulatory molecules.",
  "The right-side DNA segment now slides to several different map positions. The enhancer remains capable of influencing the tracked promoter when the required regulatory contacts are possible. Sora names **Regulatory-sequence position**. Promoter and enhancer regulatory sequences can influence transcription from positions upstream or downstream of the transcription start site. She does not reduce the entire promoter to a TATA box, and she does not require every enhancer to sit immediately beside the promoter. Regulatory architecture can vary while the basic distinction between DNA control elements and protein regulators remains intact.",
  "Sora then places several labels on the real components that have already moved. **Control elements, activators, and repressors** are distinct. Noncoding regulatory DNA elements can bind transcription factors that increase or decrease transcription of target genes. An activator is a regulatory protein that can increase transcription through its interactions. A repressor can reduce transcription. Neither protein becomes the enhancer or promoter DNA merely because it binds there. The hall keeps molecule type and job visible at the same time.",
  "The promoter and enhancer contacts remain in place as the floor narrows into a balance gate. Sora fixes the tracked gene sequence and promoter position so neither can move in the next experiment. The only variable will be the regulatory protein arriving from the left or right. The next room asks a narrower question. When a negative regulator is added and transcription falls, can you identify **Negative transcriptional regulation** without confusing the repressor protein with the DNA element it acts through?"
 ]},
'U6-L36':{
 'title':'The Output Meter Falls Even Though the Gene Has Not Changed',
 'kicker':'Negative regulation is diagnosed by a decrease in transcription caused by a regulatory interaction, not by a mutation in the gene.',
 'paragraphs':[
  "The **Activator–Repressor Balance Gate** is deliberately sparse. On your **left**, an **activator / positive regulation side** holds a regulatory protein that can support transcription under the displayed conditions. Directly **ahead**, the **transcriptional output balance** holds the tracked gene, its fixed promoter position, and an expression meter at baseline. On your **right**, a **repressor / negative regulation side** contains a different regulatory protein and its matching interaction site. Sora shows you the sealed DNA sequence one more time. The gene is identical before and after every regulatory test in this room.",
  "The left-side activator approaches its regulatory context and the meter rises above baseline. Sora removes it and lets the system settle. She does not turn that one example into a universal mechanism for all activators. The purpose is to give the center meter a visible positive reference. Regulatory proteins can affect transcription through different molecular interactions, and their effects depend on the specific system.",
  "Now the right-side negative regulator enters. Its interaction reduces transcription, and the expression meter drops while the DNA sequence remains fixed. Sora names the relationship **Negative transcriptional regulation**. Negative regulatory molecules can inhibit gene expression by binding DNA and preventing or reducing transcription. The exact mechanism can vary among systems. The diagnostic relationship is the decrease in gene expression associated with the negative regulatory interaction.",
  "Sora then removes or counteracts the negative input. The meter recovers toward its earlier state. That reversibility matters because it shows a regulatory effect rather than a permanent DNA lesion. She places the bacterial operon repressor model behind a side window for comparison. Some bacterial repressors directly bind operator DNA. Eukaryotic negative regulation can involve different regulatory sequences, proteins, chromatin interactions, and transcription machinery. The shared idea is reduced transcription through regulation. The molecular architecture should not be assumed identical in every organism or gene. She repeats the test with RNA polymerase recruitment markers visible. When the negative regulator is present, fewer initiation complexes assemble and the transcript counter falls. When the regulator is removed, initiation frequency recovers. The center meter therefore records the consequence of a molecular regulatory interaction rather than a vague label that the gene is simply off.",
  "The meter is now stable, yet Sora points to the RNA leaving the transcription platform. Even after transcription has occurred, the amount of protein produced from that RNA can still change. A transparent tube carries one pre-mRNA to the next floor, where exon choice, RNA stability, and small regulatory RNAs can change what message persists or is translated. She leaves the activator and repressor gate frozen behind you, so the next layer cannot be mistaken for another DNA-binding event. The journey moves into the **RNA-Level Regulation Suite**, making it clear that transcriptional regulation is one layer of control, not the final one."
 ]},
'U6-L37':{
 'title':'The Same Gene Sends Out Messages With Different Fates',
 'kicker':'RNA-level regulation changes which mature messages are produced, how long they persist, and how effectively they are translated.',
 'paragraphs':[
  "The tracked gene stays sealed behind glass while its newly transcribed RNA enters a three-part suite. On your **left**, the **alternative-splicing side** displays one pre-mRNA with clearly marked exons and introns. Directly **ahead**, the **RNA-level regulation suite** contains transcript-stability and translation-use meters. On your **right**, a **miRNA / siRNA small-RNA side** holds short regulatory RNAs beside complementary target sequences on longer transcripts. Sora leaves the DNA sequence display visible above all three stations. Whatever happens here changes RNA handling after transcription. It does not require a new mutation in the gene.",
  "The left station runs the same pre-mRNA through two permitted splice patterns. Different exon combinations become different mature RNA isoforms. Sora names **Alternative splicing as regulatory mechanism**. Alternative splicing can regulate which mature mRNA and protein isoforms are produced from a gene. The underlying gene DNA remains unchanged. This is the same RNA-processing principle you learned earlier, now used explicitly as a gene-regulatory mechanism because changing the mature RNA isoform changes the possible protein output.",
  "At center, Sora holds transcription rate constant and changes how long a target mRNA persists. When the transcript is degraded sooner, less message remains available for translation. When it persists longer, more opportunities for translation can occur. She names the broad AP-level relationship **Small RNA regulation** as the right-side molecules enter. Certain small RNA molecules regulate gene expression, for example by affecting mRNA stability or translation. The control point is now downstream of transcription.",
  "On the right, two named small-RNA categories are shown without adding unnecessary mechanistic detail. **microRNA and siRNA** can base-pair with target RNAs and promote RNA degradation or inhibit translation. Sora keeps the names separate on two trays while showing the shared principle of sequence-dependent interaction with target RNA. One target transcript is directed toward degradation, causing its abundance to fall. A second remains present but produces less protein because translation is inhibited. These named subclasses are useful context for the broader small-RNA requirement, and the scene avoids claiming every small RNA acts through one identical molecular pathway.",
  "Sora places one alternatively spliced transcript beside one small-RNA-regulated transcript. The first differs because exon choice changed during RNA processing. The second differs because a regulatory RNA changed the target message’s stability or translation. Both are RNA-level control, but they are not the same mechanism. She traces the regulatory event backward to the same unchanged DNA sequence and forward to different protein output, reinforcing where this layer sits in the information pathway. The suite releases several RNA outputs with different isoforms, stabilities, and translation potentials. Sora sends their measurements to a wall-sized console ahead. One cell may transcribe the same gene at a similar rate yet accumulate a different amount of functional product because RNA-level control differs. The next room combines many such outputs into a **gene-expression profile** so you can see how regulation across multiple genes contributes to phenotype."
 ]},
'U6-L38':{
 'title':'The Genome Stays the Same While the Output Pattern Changes',
 'kicker':'Phenotype depends on the pattern, amount, and function of gene products across many genes, not on transcript abundance alone.',
 'paragraphs':[
  "The **Expression Profile Console** faces three identical chromosome maps mounted above three model cells. On your **left**, the **gene-product amount / function input** displays bars for transcripts and functional products from several genes. Directly **ahead**, the **expression-profile phenotype console** arranges those values into a multigene pattern. On your **right**, the model cell’s observable structures and activities update as the product pattern changes. Sora compares the chromosome maps first. They match. She then changes regulatory inputs across several genes while leaving the underlying genome fixed.",
  "Some gene bars rise, others fall, and several remain nearly constant. The overall pattern becomes a **gene-expression profile**. Sora names the relationship **Gene-expression profile determines phenotype**. Cell and organism phenotypes depend on which genes are expressed and the levels at which they are expressed. The word profile matters because phenotype is influenced by a combination of gene-expression states rather than a single universal gene-output switch.",
  "Sora then separates RNA amount from functional protein output. One transcript is abundant, yet its protein product is rapidly degraded. Another transcript is less abundant, but its protein is stable and highly active. A third protein is present but inactive until modified. The right-side phenotype responds to these functional differences. Sora names **Gene-product amount and function influence phenotype**. The functions and amounts of gene products help determine phenotype. Transcript abundance can contribute useful information, but phenotype is not determined by transcript amount alone. She tests this by equalizing the transcript bars in two model cells while leaving protein stability and activity different. The cells still display different functional outputs. Then she equalizes protein amount but changes which proteins are active. Phenotype changes again, proving that both amount and function matter.",
  "The console now applies the earlier layers together. Chromatin accessibility changes how much transcription can occur. Promoter and enhancer interactions change initiation. RNA processing and stability change the messages available. Translation and protein-level control change final product amount and activity. The genome display remains fixed while the profile shifts. Sora points back down the tower. Every floor has changed output without changing the tracked gene’s nucleotide sequence. She then overlays the profiles from two cells as heat-map strips. The same genes are present in both profiles, yet their relative activity differs. The visual pattern is a direct bridge from molecular regulation to cell-level phenotype.",
  "Two doors open on the right. Behind each is a cell carrying the same genome, yet the cells have different shapes, internal structures, and tissue-specific proteins. The console sends different expression profiles into the two doors. The next question is no longer whether expression can vary. It is how **differential gene expression** can create stable differences in cell structure and function. You enter the **Cell Specialization Gallery** with both same-genome cells visible side by side."
 ]},
'U6-L39':{
 'title':'Two Cells Carry the Same Genome and Become Different Cells',
 'kicker':'Cell specialization emerges when different genes are expressed and different gene products accumulate in cells that share the same genome.',
 'paragraphs':[
  "The gallery is a long white room divided around two same-genome cell models. On your **left**, the **shared genome / inactive genes side** shows matching chromosome sets inside both cells. Directly **ahead**, the **differential-expression specialization gallery** contains two illuminated gene panels with different subsets active. On your **right**, the cells accumulate different tissue-specific proteins and develop different structures. Sora locks the chromosome maps together with a transparent bar so neither genome can be swapped. The only planned difference is which genes are expressed and how strongly their products accumulate.",
  "The first cell activates a set of genes that produces one characteristic protein collection. The second cell activates a different set while many other genes remain shared or constitutively expressed. Sora points to the resulting cell-specific products and names **Differentiation and tissue-specific proteins**. Observable cell differentiation reflects expression of genes that produce cell- or tissue-specific products. A specialized cell therefore does not need a completely different inherited genome from another ordinary somatic cell to have different structure and function.",
  "The expression panels continue changing until the two cells have distinct functional identities. Sora names the broader causal relationship **Differential gene expression and specialization**. Gene regulation creates differential gene expression, changing cell products and functions and thereby contributing to cell specialization. The term differential means the expression patterns differ. The genome comparison above the cells remains fixed to prevent the idea that each cell type must contain a unique set of genes. Several shared housekeeping genes remain active in both cells, while a smaller set of tissue-specific expression differences drives distinct products and functions. The contrast helps you picture specialization as a patterned change in expression across a shared genome, not a complete replacement of one genetic program with another.",
  "Sora then names the process visible across the room **Cell differentiation**. Cell differentiation is the process by which cells develop specialized structures and functions through regulated gene expression. She keeps differentiation physically separate from the architectural changes that will shape whole tissues in the final hall. A cell acquiring a specialized identity is one process. **Morphogenesis**, which you will see next, concerns the development of form through coordinated cell behavior, patterning, growth, and differentiation. To make the difference concrete, the two specialized cells remain stationary while the tissue model beyond the door changes arrangement and shape. Cell identity and tissue form are now two different pictures in the same line of sight.",
  "For the optional Quick Recall, Sora dims the expression panels and leaves only the identical genome maps and two different cell identities visible. She asks what regulatory relationship can explain those specialized outcomes without changing the genome. Once **Differential gene expression and specialization** is retrieved, a door opens into a developmental corridor. The two finished cell types are now shown as endpoints, while the next hall rewinds development to an early embryo and asks how sequences of regulatory events produce those differences over time."
 ]},
'U6-L40':{
 'title':'A Timed Sequence of Signals Builds Form From the Same Genetic Information',
 'kicker':'Development depends on sequential gene-expression changes, intercellular signals, early determinants, patterning, differentiation, and regulated cell removal.',
 'paragraphs':[
  "The final hall is the longest room in the center. On your **left**, the **early determinants / induction side** contains an egg and early-embryo model. Maternal molecules are distributed unevenly through the cytoplasm, and neighboring embryonic cells can send signals to one another. Directly **ahead**, the **sequential developmental gene-expression route** is a timed corridor marked TF1, TF2, TF3, with downstream gene panels activating in order. On your **right**, the developing tissue changes regional identity and shape while selected cells undergo controlled removal. Sora places the same genome symbol above every descendant cell. The developmental route is about changing gene-expression programs through time and space, not replacing the genome at each step.",
  "The center corridor begins with one transcription factor activated by an early developmental signal. That factor helps alter expression of downstream genes, including genes encoding additional regulatory proteins. A later state therefore depends partly on an earlier state. Sora names **Sequential developmental gene expression**. Induction of transcription factors during development can produce sequential patterns of gene expression. The timing matters. Developmental genes are not all turned on simultaneously, and one regulator does not single-handedly specify the entire final body plan.",
  "On the left, Sora turns to the unevenly distributed maternal molecules in the egg. These are **Cytoplasmic determinants**. Cytoplasmic determinants are maternal molecules distributed in an egg or early embryo that can influence developmental gene expression in descendant cells. In the neighboring-cell display, one group releases a signal that changes gene expression and developmental fate in another. Sora names **Induction in development**. Induction occurs when signals from one cell or tissue alter gene expression and developmental fate in another cell or tissue. Cytoplasmic determinants and induction therefore provide different sources of developmental information.",
  "The right side of the hall now assembles a regional map. Different locations activate different regulatory programs, and regional identities emerge. Sora names **Pattern formation and homeotic genes**. Developmental gene-regulatory networks establish body pattern, and homeotic genes are one class of developmental regulators that specify regional identity in many animals. She keeps homeotic genes as one class within a larger regulatory network. No single homeotic gene is presented as the universal controller of all development.",
  "As the patterned tissue grows, cell divisions, changes in cell shape, movement, adhesion, and differentiation alter the form of the developing structure. Sora labels this **Morphogenesis**. Morphogenesis is the development of organismal form through coordinated cell behaviors, differentiation, growth, and patterning. She points back to the previous gallery so the distinction remains visible. **Cell differentiation** describes cells acquiring specialized structures and functions. Morphogenesis describes coordinated development of form at the tissue or organismal level, with differentiation contributing to that process.",
  "A final row of cells is removed from a temporary tissue bridge in a controlled sequence. Their membranes remain intact long enough for orderly cellular dismantling rather than uncontrolled rupture across the model. Sora names **Apoptosis**. Apoptosis is regulated programmed cell death that contributes to normal development and tissue remodeling. The removal changes the shape of the tissue without being treated as random damage. When the bridge clears, the final tissue form is complete.",
  "The hall lights up behind you from entrance to exit. The same genetic information can support very different outcomes because regulation acts at many levels. Bacterial operons coordinate related genes through local control DNA and regulatory proteins. Eukaryotic regulation can act through chromatin, transcription factors and regulatory sequences, RNA processing and stability, translation, and protein-level control. Expression profiles shape phenotype. Differential gene expression supports cell specialization. Developmental signals and sequential regulatory programs organize specialized cells into form. Sora closes the copper ledger only after the tracked gene’s sequence is still visibly unchanged and you can explain how control of expression, rather than a change in that sequence, produced the different outputs."
 ]},
}

BEAT_IMAGES={
'U6-K-046':'the tracked gene surrounded by regulatory DNA and regulatory proteins while its expression meter changes but its sequence seal does not',
'U6-K-047':'the steady constitutive channel beside the signal-responsive inducible channel',
'U6-K-053':'the bacterial operon bracket causing a related gene set to change transcription together',
'U6-K-136':'the single bacterial DNA unit containing shared control DNA and functionally related genes',
'U6-K-137':'the promoter, operator, and structural genes held in distinct positions on one DNA rail',
'U6-K-138':'the separate repressor protein binding regulatory DNA and decreasing transcription',
'U6-K-139':'the regulatory ligand changing protein conformation at an allosteric site',
'U6-K-140':'the trp operon meter falling when abundant tryptophan activates repressor binding',
'U6-K-141':'tryptophan binding the trp repressor before the repressor binds operator DNA',
'U6-K-142':'the lac operator changing from repressor-blocked to transcribable when inducer is present',
'U6-K-143':'allolactose binding the lac repressor and reducing its operator-binding activity',
'U6-K-144':'lacZ β-galactosidase, lacY permease, and other bacterial lac products on the output rack',
'U6-K-054':'separate eukaryotic genes responding together to the same transcription factor',
'U6-K-145':'the layered stack of chromatin, transcription, RNA, translation, and protein-level regulation',
'U6-K-048':'the same DNA sequence changing expression as reversible DNA or histone modifications change',
'U6-K-146':'the histone-acetylation side becoming more accessible in the displayed locus',
'U6-K-147':'DNA methylation marks associated with repression in the displayed regulatory context',
'U6-K-148':'a chromatin regulatory state persisting through model cell divisions without sequence change',
'U6-K-055':'promoter and enhancer contacts recruiting transcription factors and RNA polymerase toward initiation',
'U6-K-056':'the enhancer/control element influencing the promoter from a distant upstream or downstream position',
'U6-K-149':'DNA control elements held apart from the activator and repressor proteins that bind them',
'U6-K-057':'the expression meter dropping when a negative regulatory protein is added to the unchanged gene',
'U6-K-059':'small regulatory RNA changing target mRNA stability or translation after transcription',
'U6-K-150':'one pre-mRNA producing different mature RNA isoforms through alternative splicing',
'U6-K-151':'microRNA and siRNA pairing with target RNAs to promote degradation or inhibit translation',
'U6-K-049':'the multigene expression profile changing while the genome display remains fixed',
'U6-K-052':'different amounts and activities of gene products producing different phenotypic output',
'U6-K-050':'same-genome cells accumulating different tissue-specific proteins',
'U6-K-058':'different expression programs producing different specialized cell functions',
'U6-K-152':'a cell acquiring specialized structure and function through regulated gene expression',
'U6-K-051':'developmental transcription factors activating downstream expression programs in sequence',
'U6-K-153':'coordinated growth, patterning, cell behavior, and differentiation changing tissue form',
'U6-K-154':'maternal cytoplasmic determinants distributed unevenly in the egg or early embryo',
'U6-K-155':'a signal from one cell altering gene expression and developmental fate in another',
'U6-K-156':'regional patterning and homeotic-gene logic assigning developmental identity',
'U6-K-157':'regulated programmed cell death removing selected cells during normal development and remodeling',
}

CHECKPOINTS={'U6-L30','U6-L32','U6-L34','U6-L39'}

def word_count(pars): return len(re.findall(r"\b[\w’′'-]+\b",' '.join(pars)))
def zone_objs(lid): return [{'position':p,'label':label,'symbol':sym,'description':desc} for p,label,sym,desc in ZONES[lid]]
def cast_for(lid):
    items=[{'name':'Dr. Sora Han','kind':'guide','visual':GUIDE['visual'],'job':GUIDE['story_job']}]
    for p,label,sym,desc in ZONES[lid]:
        items.append({'name':label,'kind':'scientific anchor','visual':f'{sym} · {desc}','job':B[lid]['spatial_layout'][p]['layout_job']})
    items.append({'name':'Tracked gene and expression-state ledger','kind':'continuity object','visual':'one sealed eukaryotic gene sequence with a fixed promoter marker, chromatin-state strip, transcript counter, and protein-output meter; bacterial trp/lac models remain separately labeled comparison systems','job':'keeps DNA sequence, chromatin state, regulatory input, RNA output, protein output, and phenotype traceable without conflating bacterial operons with the tracked eukaryotic gene'})
    return items

def beats_for(lid):
    out=[]; terms={t['knowledge_id']:t for t in B[lid]['term_introductions']}
    for kid in B[lid]['knowledge_ids']:
        t=terms[kid]; c=CANON[kid]
        out.append({'object_id':kid,'term':t['canonical_term'],'story':BEAT_IMAGES[kid],'science':c['canonical_verified_statement'],'exact_name':bool(t['exact_name_recall']),'hint':BEAT_IMAGES[kid],'name_support':t['name_support'],'reactivation_mode':t['reactivation_mode'],'scope_class':t['scope_class']})
    return out

scenes=[]
for i,lid in enumerate(J4['route']):
    b=B[lid]; n=NARR[lid]; r=ROUTE[i]; pars=n['paragraphs']; cp=lid in CHECKPOINTS
    scenes.append({
      'scene_index':i,'locus_id':lid,'locus':r['locus'],'title':n['title'],'scene_kicker':n['kicker'],
      'location_description':b['micro_anchor'],'scene_layout':{'orientation':b['orientation_sentence'],'zones':zone_objs(lid)},
      'cast':cast_for(lid),'continuity_object':J4['continuity_object'],'story_open':pars[0],'story_paragraphs':pars,'story_close':pars[-1],
      'object_ids':list(b['knowledge_ids']),'story_beats':beats_for(lid),'prior_unit_reactivation':b['prior_unit_reactivation'],'misconception_guards':b['misconception_guards'],
      'checkpoint':cp,'checkpoint_object_id':b['primary_knowledge_id'] if cp else None,'checkpoint_prompt':b['quick_recall']['candidate_prompt'] if cp else '', 'checkpoint_answer':b['quick_recall']['answer'] if cp else '',
      'next_locus':ROUTE[i+1]['locus'] if i+1<len(ROUTE) else None,'f3_scene_brief_id':b['scene_brief_id'],'narrative_word_count':word_count(pars)
    })

journey={
 'palace_id':'U6-J4','unit_id':'unit-6','palace_name':'Gene Control and Differentiation Center','story_title':'The Control Center That Forgot Its Cell Identities',
 'tagline':'The genome has not changed, but every cell is drifting toward the same output state. Follow one tracked gene through bacterial comparison switches and the layered eukaryotic control system until distinct expression profiles and specialized cell identities can be restored.',
 'guide':GUIDE,
 'premise':'A gene-control failure has flattened expression across a bank of model cells. The cells still carry matching genomes, yet regulatory outputs that should differ by condition, cell type, and developmental state are converging toward the same pattern. Dr. Sora Han seals one tracked eukaryotic gene sequence so it cannot change and attaches an expression meter and chromatin-state strip. To restore cell identity, you must determine how gene output can change around an unchanged sequence. The route first descends through two bacterial operon comparison chambers, then returns to the tracked eukaryotic gene and follows regulation through chromatin, transcriptional recruitment, negative regulation, RNA-level control, expression profiles, differentiation, and developmental sequencing.',
 'mission':'Keep the tracked gene sequence fixed while changing only the scientifically relevant control layer. Distinguish constitutive from inducible expression, operon DNA from repressor protein, repressible trp logic from inducible lac logic, and bacterial control from eukaryotic layered regulation. Then follow the same eukaryotic gene through reversible epigenetic state, promoter/enhancer recruitment, negative transcriptional regulation, RNA-level control, multigene expression profiles, cell specialization, and developmental gene-expression sequences. At every stage, identify which molecule or regulatory state changed and which output changed as a consequence.',
 'finale':'The final developmental hall restores distinct cell identities without altering the tracked genome. Cytoplasmic determinants and inductive signals alter developmental gene expression, transcription factors act in sequence, regional patterning and homeotic-gene logic contribute to positional identity, morphogenesis changes tissue form, and apoptosis removes selected cells during normal remodeling. Looking back through the center, the learner can reconstruct a single causal principle across very different mechanisms. Stable DNA sequence does not imply fixed gene output. Regulatory DNA, regulatory proteins, chromatin, RNA processing and stability, translation, protein state, developmental signals, and expression profiles can all change what a cell produces and therefore what the cell becomes.',
 'estimated_minutes':36,'scene_count':12,'checkpoint_count':4,'student_release':'DEVELOPER_PREVIEW_F4D','preview_release':True,'narrative_design':'U6-F4D-NARRATIVE-1.0',
 'learner_rule':'Read or listen and place yourself in the fixed left/center/right geometry before each regulatory state changes. Keep the tracked eukaryotic gene sequence sealed in your mind, and treat the trp and lac operons as separately labeled bacterial comparison models. Optional Quick Recall appears only four times after the mechanism has already been encountered.',
 'route_orientation':'This is one continuous twelve-location route through the Gene Control and Differentiation Center. Begin at the broad expression-control room, descend through operon architecture and the trp/lac comparison chambers, return to the tracked eukaryotic gene in the regulation tower, then move through chromatin state, promoter/enhancer recruitment, activator/repressor balance, RNA-level control, expression profiles, specialization, and the final developmental sequence hall. The tracked eukaryotic gene sequence remains fixed while regulatory state and output change around it.',
 'route':ROUTE,'scenes':scenes,'source_brief_lock':'LOCKED_F3','scientific_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2'
}

(U6/'journeys').mkdir(exist_ok=True)
(U6/'journeys'/'U6-J4.json').write_text(json.dumps(journey,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
j1=json.loads((U6/'journeys'/'U6-J1.json').read_text(encoding='utf-8'))
j2=json.loads((U6/'journeys'/'U6-J2.json').read_text(encoding='utf-8'))
j3=json.loads((U6/'journeys'/'U6-J3.json').read_text(encoding='utf-8'))
summary={'schema':'memory-palace-v2-unit6-f4d-journeys-1.0','unit_id':'unit-6','stage':'F4D','student_release':False,'preview_release':True,'journey_count':4,'scene_count':40,'checkpoint_count':sum(j['checkpoint_count'] for j in [j1,j2,j3,journey]),'guided_journeys':[{k:j[k] for k in ['palace_id','palace_name','story_title','tagline','guide','premise','mission','finale','estimated_minutes','scene_count','checkpoint_count','student_release','narrative_design']} for j in [j1,j2,j3,journey]]}
(U6/'journeys-f4d.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

status={'unit_id':'unit-6','number':6,'title':'Gene Expression and Regulation','status':'F4D_JOURNEYS1_4_POLISHED_DEVELOPER_PREVIEW','pipeline_stage':'F4D_JOURNEY4_NARRATIVE','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','narrative_lock':'LOCKED_F4D_J1_J4','student_release':False,'preview_release':True,'journey_count':4,'scene_count':40,'memory_objects':0,'application_challenges':0,'canonical_records':202,'architecture_journeys':6,'architecture_loci':53,'scene_briefs':53,'palace_managed_records':161,'challenge_lab_records':16,'scope_guard_records':25,'exact_name_review_targets':134,'confusable_sets':37,'optional_first_exposure_recalls':18,'f4a_journey':'U6-J1','f4a_scene_count':12,'f4b_journey':'U6-J2','f4b_scene_count':8,'f4c_journey':'U6-J3','f4c_scene_count':8,'f4d_journey':'U6-J4','f4d_scene_count':12,'f4d_knowledge_records':36,'f4d_optional_recalls':4,'next_required_output':'F4E polished narrative for Journey 5 only after Journeys 1–4 remain frozen and all prior prose-quality gates continue to pass.'}
(U6/'status-f4d.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); (U6/'status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
cp=ROOT/'content'/'ap-biology'/'course.json'; course=json.loads(cp.read_text(encoding='utf-8')); u=next(x for x in course['units'] if x['unit_id']=='unit-6'); u.update({'status':'F4D_JOURNEYS1_4_POLISHED_DEVELOPER_PREVIEW','journey_count':4,'scene_count':40,'student_release':False,'preview_release':True,'source_status':'AUDITED_F1_ARCHITECTURE_F2_BRIEFS_F3_NARRATIVE_F4D','narrative_lock':'LOCKED_F4D_J1_J4','narrative_journeys':4}); cp.write_text(json.dumps(course,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

doc=['# Unit 6 F4D · Journey 4 Narrative','','## The Control Center That Forgot Its Cell Identities','',journey['tagline'],'','### Route','', ' → '.join(x['locus'] for x in ROUTE),'']
for s in scenes:
    doc += [f"## {s['scene_index']+1}. {s['locus']} · {s['title']}",'',f"*{s['scene_kicker']}*",'']+s['story_paragraphs']+['']
    if s['checkpoint']: doc += ['**Optional Quick Recall**','',s['checkpoint_prompt'],'']
(ROOT/'docs'/'UNIT6_F4D_JOURNEY4_STORY.md').write_text('\n'.join(doc),encoding='utf-8')

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
locked_rel=['journeys/U6-J1.json','journeys/U6-J2.json','journeys/U6-J3.json','journeys/U6-J4.json','journeys-f4d.json','status-f4d.json']
lock_files={rel:{'bytes':(U6/rel).stat().st_size,'sha256':sha(U6/rel)} for rel in locked_rel}
lock={'schema':'memory-palace-v2-unit6-f4d-lock-1.0','unit_id':'unit-6','lock_status':'LOCKED_F4D_J1_J4','student_release':False,'preview_release':True,'protected_prior_locks':['content-lock-f1.json','content-lock-f2.json','content-lock-f3.json','content-lock-f4a.json','content-lock-f4b.json','content-lock-f4c.json'],'frozen_f4a_journey_sha256':sha(U6/'journeys/U6-J1.json'),'frozen_f4b_journey_sha256':sha(U6/'journeys/U6-J2.json'),'frozen_f4c_journey_sha256':sha(U6/'journeys/U6-J3.json'),'journey_ids':['U6-J1','U6-J2','U6-J3','U6-J4'],'scene_count':40,'new_journey_scene_count':12,'new_journey_knowledge_record_count':36,'new_journey_checkpoint_count':4,'files':lock_files,'rule':'Journeys 1–3 remain byte-frozen from F4A/F4B/F4C. Journey 4 polished prose may not change after F4D without a new explicit narrative version. F1 science, F2 classification/geometry, and F3 briefs remain authoritative boundaries.'}
(U6/'content-lock-f4d.json').write_text(json.dumps(lock,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
release={'schema':'memory-palace-v2-unit6-f4d-release-1.0','generated_utc':'2026-09-08T03:30:00+00:00','unit_id':'unit-6','release_status':'F4D_JOURNEYS1_4_POLISHED_DEVELOPER_PREVIEW','student_release':False,'preview_release':True,'journeys':4,'scenes':40,'new_journey_id':'U6-J4','new_journey_scenes':12,'new_journey_knowledge_records':36,'new_journey_optional_first_exposure_recalls':4,'canonical_records':202,'permanent_loci_architecture':53,'scene_briefs':53,'memory_objects':0,'application_challenges':0,'scientific_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','narrative_lock':'LOCKED_F4D_J1_J4','next_stage':'F4E Journey 5 polished narrative after F4A/F4B/F4C/F4D regression'}
(U6/'f4d-release-manifest.json').write_text(json.dumps(release,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'journey':'U6-J4','scenes':12,'knowledge_records':36,'checkpoints':4,'words':sum(s['narrative_word_count'] for s in scenes),'min_words':min(s['narrative_word_count'] for s in scenes),'max_words':max(s['narrative_word_count'] for s in scenes)},indent=2))
