from __future__ import annotations
import json, hashlib, re
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timezone

ROOT=Path(__file__).resolve().parents[1]
U8=ROOT/'content'/'ap-biology'/'unit-8'
BRIEFS=U8/'briefs'; BRIEFS.mkdir(parents=True,exist_ok=True)
GEN=datetime.now(timezone.utc).replace(microsecond=0).isoformat()

def read(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def dump(p,obj): Path(p).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def split_ids(s): return [x.strip() for x in re.split(r'[,;]',s or '') if x.strip()]

canon_list=read(U8/'canonical-catalog.json'); canon={r['Knowledge ID']:r for r in canon_list}
cls=read(U8/'architecture/learning-classification-f2.json'); class_by={r['knowledge_id']:r for r in cls['records']}
arch=read(U8/'architecture/palace-architecture-f2.json')
flags={r['Flag ID']:r for r in read(U8/'review-flags.json')}
scope_guards=read(U8/'scope-guards.json')
mixed=arch['mixed_discrimination_sets']
conf_by=defaultdict(list)
for m in mixed:
    for k in m['knowledge_ids']: conf_by[k].append(m)

unit_guide={
 'name':'Dr. Mira Sen',
 'role':'ecological-systems field curator who accompanies the learner through all eight Unit 8 journeys',
 'visual_identity':'dark field vest, waterproof notebook, a transparent ecology tablet that can display the current scale, organism or population identity, energy/matter arrows, and measured variables, plus a pointer used only to indicate real structures, graphs, reservoirs, or interactions',
 'behavior_rule':'Mira establishes the physical geography before terminology, keeps ecological scale and organism/population/community identity visible, changes one causal variable or transfer at a time, and names a term only after its defining pattern or mechanism can be reconstructed.',
 'continuity_rule':'Mira records and points; she never replaces an organism, population, species interaction, trophic transfer, reservoir, molecule, graph, or environmental driver. Scientific entities and arrows retain their conventional biological meaning.'
}

journey_specs={
'U8-J1':dict(premise='The Behavioral Response Institute begins with observable cues and responses, then separates immediate mechanism, evolutionary explanation, inherited predisposition, learning, movement, communication, social behavior, and plant responses so behavior never becomes a loose list of labels.', mission='Carry one stimulus-response tablet through twelve rooms. At each room, identify the cue, biological responder, response pattern, and consequence before naming the behavior or learning mechanism.', stakes='Behavior concepts become confusable when mechanism and evolutionary function collapse together, when movement is mistaken for growth, when learned and innate are treated as absolute opposites, or when altruism is given a human-intention definition.', continuity_object='one transparent stimulus-response tablet with fixed fields for cue, responder, immediate mechanism, experience, behavioral output, and fitness/homeostasis consequence', recurring_scientific_cast=['the same stimulus-response tablet','real organisms or plant tissues responding to cues','fixed cue-to-response arrows and consequence readouts'], opening_image='The entry hall shows several organisms responding to light, chemicals, seasonal cues, social signals, and food, but every display is initially unlabeled. The route begins by asking what changed, what detected it, and what response followed.', ending_payoff='The learner can separate proximate from ultimate explanation, distinguish major behavior and learning categories by mechanism, track communication from sender to receiver, and keep animal movement separate from directional plant growth.', tone='observational, causal, comparison-rich, biologically grounded'),
'U8-J2':dict(premise='The Ecosystem Energy Exchange Hall follows energy from organism budgets into ecosystem structure, producer capture, feeding relationships, production, and trophic transfer while matter conservation stays visibly separate.', mission='Carry one two-column energy-and-matter ledger from organism intake through trophic transfer. Every transfer must show where energy enters, where it becomes less available, and where matter remains conserved.', stakes='Students often recycle energy, treat the ten-percent rule as exact, reverse food-web arrows, or collapse GPP, NPP, and secondary production. The route keeps input, transfer, respiration, heat, biomass, and matter reservoirs separate.', continuity_object='one transparent energy-matter ledger with an energy column that can dissipate as heat and a matter column that remains traceable through organisms and reservoirs', recurring_scientific_cast=['energy-matter ledger','real producers, consumers, decomposers, and detritus','arrows labeled by transfer direction and production/respiration readouts'], opening_image='A large hall receives sunlight, chemical energy, inorganic carbon, organisms, and detritus. Nothing is yet connected. The learner must build the flow while preserving the difference between energy transformation and matter cycling.', ending_payoff='The learner can explain organism energy balance, thermoregulation, trophic roles, food-web direction, GPP/NPP, secondary production, and variable trophic-transfer efficiency without violating conservation laws.', tone='accounting-like, directional, transfer-focused, quantitative without calculation overload'),
'U8-J3':dict(premise='The Biogeochemical Cycle Watershed uses the same reservoir-transfer frame for water, carbon, nitrogen, and phosphorus while keeping the chemistry and dominant reservoirs of each cycle distinct.', mission='Move labeled matter through abiotic and biotic reservoirs using only valid transfer processes. Each cycle must return to the shared reservoir-transfer logic without borrowing a process from another cycle.', stakes='Cycle diagrams become memorized arrows when reservoirs, transformations, and chemical direction are not explicit. Nitrogen transformations and the atmospheric difference between nitrogen and phosphorus are especially easy to confuse.', continuity_object='one watershed reservoir board with fixed pool boxes and transfer-arrow slots; the tracked substance changes by cycle, but reservoir versus process never changes meaning', recurring_scientific_cast=['reservoir boxes','transfer-process arrows','biotic uptake and abiotic return pathways'], opening_image='Four unlabeled tracer sets sit beside one empty watershed board. The route begins by defining what counts as a reservoir and what counts as a transfer before any named cycle is assembled.', ending_payoff='The learner can rebuild each cycle by reservoirs and processes, distinguish the nitrogen transformations by chemical direction, and explain why phosphorus is primarily sedimentary.', tone='map-based, chemical-directional, reservoir-first'),
'U8-J4':dict(premise='The Population Survey and Demography Reserve follows one population from field sampling through spatial pattern, age-specific survival, population-change accounting, and life-history allocation.', mission='Keep one marked population identity while changing how it is measured. Density, dispersion, demography, survivorship, births/deaths/migration, and life-history traits must remain different measurements of the same population scale.', stakes='Density can be confused with dispersion, survivorship types with species categories, and dN/dt with per-capita rate. The route makes each quantity and graph physically distinct.', continuity_object='one marked field population with a persistent census ID, mapped boundary, cohort ledger, and population-size counter N', recurring_scientific_cast=['field population and boundary','sampling/census records','age, survival, birth, death, and migration ledgers'], opening_image='A reserve contains one population whose size is unknown. The learner first defines the population boundary and sampling frame, then progressively adds spatial and demographic information.', ending_payoff='The learner can distinguish density from dispersion, read life tables and survivorship curves, account for population change, and connect life-history traits to energetic trade-offs.', tone='field-survey, measured, demographic, scale-explicit'),
'U8-J5':dict(premise='The Population Growth Control Center compares idealized exponential growth, environmental carrying capacity, logistic slowing, and density-linked versus density-independent regulation.', mission='Keep the same N, rmax, time axis, and resource condition visible while moving from exponential to logistic models and then testing regulatory factors.', stakes='Growth equations are often treated as formulas detached from assumptions. K can be mistaken for a fixed species trait, and density-independent events can be mislabeled merely because they reduce population size.', continuity_object='one population-growth dashboard with persistent N, time, rmax, K/resource readout, per-capita rate panel, and graph axes', recurring_scientific_cast=['population-growth dashboard','resource/carrying-capacity panel','matched population-density comparison plots'], opening_image='The control center begins with a small population under abundant resources and an empty graph. The learner must determine which assumptions justify each growth curve before the curve is drawn.', ending_payoff='The learner can derive the qualitative difference between J- and S-shaped growth, explain dynamic K, and diagnose regulation by whether per-capita effects depend on density.', tone='model-based, assumption-first, graph-linked'),
'U8-J6':dict(premise='The Community Interaction District places several species in one shared landscape so habitat, niche, competition, predation, symbiosis, disturbance, and succession can be interpreted from effects on real populations.', mission='Carry one community map with persistent species identities and resource layers. Every interaction changes a sign, resource access, abundance, or occupied niche, and those changes must remain visible into the next block.', stakes='Community ecology becomes vague when habitat and niche merge, interaction signs are memorized without effects, or succession is described as a fixed march toward one endpoint.', continuity_object='one shared community map with persistent species A/B/C identities, habitat layers, resource layers, abundance markers, and interaction-sign badges', recurring_scientific_cast=['community map','species and resource layers','interaction signs and abundance/niche readouts'], opening_image='A district map shows several species occupying the same landscape but gives no explanation of where each lives, what resources each uses, or how they affect one another.', ending_payoff='The learner can separate habitat from niche, distinguish major interspecific interactions, explain competition and partitioning, and reconstruct succession from disturbance and remaining biological legacies.', tone='networked, interaction-focused, spatially comparative'),
'U8-J7':dict(premise='The Diversity and Resilience Observatory begins with raw community counts and builds from richness and relative abundance to Simpson diversity, biodiversity, resilience, and disproportionate species effects.', mission='Keep one community sample visible while changing the question from composition to index interpretation to functional response after disturbance or species removal.', stakes='Richness is not diversity by itself, n is not N in Simpson’s index, and keystone status is not a permanent label attached to a taxon in every ecosystem.', continuity_object='one fixed community sample card with species counts, total N, diversity readout, and an intervention panel for disturbance or species removal', recurring_scientific_cast=['community count table','diversity index display','community-response intervention panel'], opening_image='The observatory receives two communities with equal richness but different abundance distributions. The route asks what each metric can and cannot tell us before any resilience claim is made.', ending_payoff='The learner can compute the meaning of the AP Simpson index symbolically, distinguish biodiversity levels, qualify diversity-resilience claims, and separate keystone from foundation effects.', tone='measurement-driven, comparative, qualified'),
'U8-J8':dict(premise='The Environmental Change Response Center traces distinct causes of ecological change from genetic variation and biological invasion through habitat alteration, harvesting, pollution, eutrophication, ocean acidification, and large-scale geographic drivers.', mission='Use one baseline landscape-and-community record. Each room changes one driver, then traces the mechanism to population or community consequences without substituting a generic “human impact” explanation.', stakes='Environmental-change topics are easily collapsed into moral labels or single-cause stories. The route preserves mechanism, time scale, ecological scale, and conditionality.', continuity_object='one baseline landscape record with habitat area, focal population size, community composition, trophic structure, water chemistry, and geographic context fields', recurring_scientific_cast=['baseline landscape record','driver-specific mechanism display','population/community consequence readout'], opening_image='The response center starts with an intact landscape and stable community record. Each later disturbance is introduced on a separate causal lane so consequences can be attributed to a mechanism.', ending_payoff='The learner can distinguish adaptation from need-directed mutation, introduction from invasion, fragmentation from overharvest, trophic magnification from acid deposition, eutrophication from ocean acidification, and broad biogeographic patterns from single-cause claims.', tone='mechanism-separated, evidence-led, environmentally realistic')
}

# exact_location, micro_anchor, left, center, right, three action steps
S={
'U8-L01':('Institute entry response bay','the cue-response workbench at the entrance','internal/external cue panel','organism response chamber','inheritance/experience and consequence panel',['Present one defined internal or external cue while keeping the organism and baseline state unchanged.','Trace the resulting behavioral or physiological response and identify the responder rather than attributing the change to the environment itself.','Compare inherited predisposition and prior experience as influences on the response, then introduce behavior and ethology only after the cue-response relation is visible.']),
'U8-L02':('Two-Level Causation Desk','the split analysis desk immediately beyond the entry bay','single observed behavior record','proximate mechanism/development desk','ultimate fitness/history desk',['Hold one behavior constant and ask how it is triggered, produced, and shaped during development.','Without changing the observed behavior, shift to effects on survival/reproduction and evolutionary history.','Label the left-to-right distinction as proximate versus ultimate only after the same behavior has been explained at both levels.']),
'U8-L03':('Behavior Origin Comparison Bay','the paired baseline-and-experience panels','untrained response baseline','experience/exposure panel','post-experience response and fitness panel',['Show a response that appears without prior learning of the basic action and keep its developmental context visible.','Expose a matched organism to a specific experience and record any subsequent behavioral modification.','Place innate and learned contributions on a continuum and connect either kind of behavior to fitness only when reproductive/survival consequences are shown.']),
'U8-L04':('Trigger Sequence Chamber','the red-cue trigger apparatus','candidate sign stimuli','fixed response sequence track','completed response and stickleback example panel',['Vary external cues while keeping the animal and context constant until the effective sign stimulus is isolated.','Trigger the unlearned response sequence and preserve its ordered acts after initiation.','Use the stickleback red-color case as an example of sign stimulus triggering a fixed action pattern, without generalizing every behavior to this mechanism.']),
'U8-L05':('Migration Navigation Dome','the long-distance route globe','departure location and seasonal state','sun/star/magnetic cue compass','arrival route and destination map',['Define migration as a regular long-distance location change before adding any navigation cue.','Overlay solar, celestial, and magnetic information as possible directional cues and trace how each could orient travel.','Keep migration itself separate from the specific cue system used by a species; the route must still be recognizable if the cue example changes.']),
'U8-L06':('Movement Gradient Arena','the floor arena with one stable stimulus gradient','stimulus source and gradient','movement tracks and turn/rate recorder','directionality classification panel',['Release matched organisms into the same gradient and record speed, turning frequency, and net direction separately.','Classify non-directional changes in rate/turning as kinesis and directed movement toward or away from the cue as taxis.','Use light, chemical, or gravity examples to identify phototaxis, chemotaxis, or gravitaxis while keeping directional plant growth outside the movement category.']),
'U8-L07':('Communication Sender-Receiver Gallery','the central signal-channel bridge','sender and signal-production panel','visual/auditory/tactile/electrical/chemical channels','receiver response and fitness panel',['Start with a sender producing a defined signal and keep the receiver response blank.','Transmit the signal through the appropriate modality and trace any stimulus-response chain in which one response becomes the next cue.','Record the receiver’s behavioral or physiological change and, where supported, connect the change to reproductive success; use pheromone and waggle dance as concrete examples.']),
'U8-L08':('Developmental Learning Timeline Room','the highlighted sensitive-period window','pre-experience developmental timeline','sensitive-period experience window','persistent later behavior panel',['Mark the developmental interval before any experience occurs and define learning as behavior modified by specific experience.','Deliver the relevant experience during the sensitive period and record the formed association or attachment.','Carry the effect forward beyond the window to show long-lasting imprinting while preserving that the effective stimulus is species- and context-dependent.']),
'U8-L09':('Learning Modes Wing','the three-panel learning comparison wall','landmark and spatial-layout panel','association/consequence panel','social-observation panel',['Demonstrate navigation from environmental spatial relationships and build a cognitive map from landmarks.','Create an association either between two environmental features or between a behavior and its consequence.','Show behavior changing after observation or interaction with another individual, then compare the three learning routes by what information produced the change.']),
'U8-L10':('Fitness Tradeoff Hall','the energy-risk and mating allocation board','foraging gain/time/risk ledger','mating-system relationship board','reproductive outcome and dimorphism panel',['Balance energetic gain against search time and risk to show how foraging behavior can be shaped by trade-offs.','Map mating relationships and distinguish monogamy, polygyny, and polyandry by who mates with multiple partners.','Connect mating-system conditions and sexual selection to reproductive outcomes and possible sexual dimorphism without treating dimorphism as universal.']),
'U8-L11':('Inclusive Fitness Ledger Chamber','the direct-and-indirect fitness accounting table','actor direct-fitness column','recipient/relatedness interaction column','inclusive-fitness outcome column',['Record the actor’s direct reproductive cost or benefit and the recipient’s benefit without assigning intention.','Add relatedness only where kin selection is being evaluated and keep cooperation separate from altruism by the actor’s direct-fitness effect.','Combine direct reproductive success with related-relative effects to construct inclusive fitness and use reproductive success as the evolutionary currency.']),
'U8-L12':('Plant Response Greenhouse','the cue-to-growth/defense bench','light/season/herbivory/soil cue racks','growth timing and defense response bench','signal/phenotype consequence display',['Use light direction to demonstrate phototropism as directional growth, then use day/night duration to demonstrate photoperiodic timing without confusing the two.','Trigger structural, chemical, or volatile defenses after herbivore challenge and keep each defense mechanism physically distinct.','Change soil chemistry in the hydrangea example to alter aluminum availability and flower phenotype, preserving the example as context-dependent environmental influence.']),
'U8-L13':('Organism Energy Budget Counter','the intake-expenditure balance board','energy intake and acquisition column','maintenance/growth/reproduction expenditure ledger','storage or sustained-deficit outcome column',['Record energy acquired and energy expended over the same interval.','Allocate expenditure to maintenance/homeostasis, growth, and reproduction while preserving the same energy units.','Show positive balance supporting storage/growth and sustained negative balance depleting reserves and reproductive output; keep reproductive-strategy responses conditional on environment.']),
'U8-L14':('Thermal Regulation Bay','the heat-source comparison platform','external heat environment','metabolic heat and metabolic-rate monitor','body-temperature and energetic-demand outcome',['Compare organisms receiving the same external thermal conditions while identifying whether metabolic heat plays a major thermoregulatory role.','Track metabolic rate through heat production or gas-exchange proxies and compare absolute versus mass-specific scaling with body size.','Classify endotherm and ectotherm by dominant heat source, retaining behavioral thermoregulation as possible in ectotherms.']),
'U8-L15':('Ecological Scale Atrium','the nested ecosystem-scale model','organism/population/community nesting','ecosystem exchange boundary','biotic/abiotic component and biome context panel',['Place populations inside communities and communities with their abiotic environment inside ecosystems, then situate ecosystems within broader biomes.','Separate living or once-living biotic components from nonliving physical and chemical abiotic components.','Trace one exchange of energy or matter across the community-abiotic boundary to make the ecosystem definition operational.']),
'U8-L16':('Energy-Matter Split Gate','the paired energy-flow and matter-cycle diagram','energy input/transformation lane','transfer and heat-dissipation gate','matter reservoir/cycling lane',['Track energy through transfer or transformation without creating or destroying it, then mark energy that becomes less available for biological work, often as heat.','Keep a separate matter tracer moving among reservoirs so matter remains conserved through ordinary biological transformations.','End with energy leaving the ecosystem largely as heat while matter remains available to cycle, preserving the distinction between thermodynamic energy conservation and matter conservation.']),
'U8-L17':('Carbon and Energy Acquisition Workshop','the carbon-source/energy-source matrix','inorganic carbon and external-energy inputs','autotroph/chemosynthesis conversion bench','heterotroph organic-matter intake panel',['Hold carbon source and energy source as separate variables before naming nutritional modes.','Show autotrophs building organic molecules from inorganic carbon using captured light or chemical energy; for chemosynthesis, trace energy from oxidation of inorganic substances.','Show heterotrophs acquiring organic carbon and energy from organisms or organic matter, making clear that chemosynthetic energy is transformed rather than created.']),
'U8-L18':('Trophic Ladder Tower','the feeding-position ladder beside the detritus chute','producer and primary-consumer levels','higher consumer and omnivory ladder','detritus/decomposer nutrient-return station',['Assign trophic position by source of energy and matter, beginning with producers and primary consumers.','Add secondary and higher consumers while allowing omnivores to occupy more than one feeding pathway in a real food web.','Route detritus to decomposers, then return inorganic nutrients to producer-accessible reservoirs without implying that decomposers recycle energy.']),
'U8-L19':('Food-Web Projection Room','the chain-to-web arrow wall','linear resource-prey sequence','interconnected feeding network','consumer energy/matter receipt endpoints',['Build one simplified food chain first and orient every arrow from resource or prey toward the consumer receiving energy and matter.','Add alternative feeding links until the chain becomes an interconnected food web without changing arrow convention.','Test a proposed arrow by asking which organism receives the transferred energy/matter; reverse any arrow that fails that test.']),
'U8-L20':('Production Accounting Ledger','the GPP-respiration-NPP accounting board','total producer capture/GPP column','producer respiration subtraction gate','NPP growth/consumer-transfer and secondary-production panel',['Record total primary production as GPP before any producer respiration is subtracted.','Subtract producer respiration R to obtain NPP = GPP − R and identify NPP as producer biomass production available for growth and trophic transfer.','Keep secondary production on a separate heterotroph pathway as new consumer biomass generated from assimilated food energy.']),
'U8-L21':('Trophic Transfer Pyramid Exit','the variable-efficiency energy pyramid','producer energy/biomass base','successive trophic transfer steps','upper-level population and ecosystem response panel',['Transfer energy upward while showing that ecological transfer efficiency varies; use about ten percent only as a rule of thumb, never a fixed law.','Reduce incoming energy or producer biomass and propagate the reduced energy supply to consumer and decomposer levels.','Explain resulting changes in trophic-level number or size and ecosystem structure using energy availability rather than a universal pyramid percentage.']),
'U8-L22':('Watershed Reservoir Map Hub','the pool-versus-process map key','abiotic and biotic reservoir boxes','transfer-process arrow slots','same-material tracer at destination reservoir',['Place matter in a named reservoir and keep the reservoir box stationary.','Move the tracer only when a specific transfer process is identified, leaving the process on the arrow rather than inside the pool.','Repeat with biotic and abiotic pools to define a biogeochemical cycle as movement among reservoirs through processes.']),
'U8-L23':('Water Cycle Watershed','the atmosphere-surface-groundwater cross-section','ocean/surface-water and organism reservoirs','evaporation/transpiration-condensation-precipitation loop','runoff/infiltration/groundwater/stream return paths',['Evaporate water from surface reservoirs and transpire water from organisms into the atmosphere.','Condense atmospheric water and return it by precipitation without changing the identity of the water tracer.','Route precipitation through runoff, infiltration, groundwater, and streams to complete multiple valid return pathways.']),
'U8-L24':('Carbon Cycle Reservoir Terrace','the atmosphere-organic-carbon exchange wall','atmospheric CO₂ and stored-carbon reservoirs','photosynthesis/respiration/decomposition exchange arrows','combustion and returned-CO₂ panel',['Move atmospheric carbon into organic matter through photosynthesis.','Return carbon dioxide through cellular respiration and decomposition while preserving carbon conservation.','Release stored carbon rapidly through combustion and compare the timescale/pathway with biological exchange.']),
'U8-L25':('Nitrogen Transformation Gallery','the chemically directional nitrogen pathway','atmospheric N₂ and organic-N pools','ammonium/nitrite/nitrate transformation track','assimilation and atmospheric-return endpoints',['Convert atmospheric N₂ to reduced nitrogen through fixation, then incorporate inorganic nitrogen into organisms through assimilation.','Convert organic nitrogen from dead matter or waste to ammonium by ammonification, then oxidize ammonium to nitrite and nitrate by nitrification.','Reduce nitrate to gaseous nitrogen forms through denitrification and return nitrogen to the atmosphere; keep all five transformations chemically directional.']),
'U8-L26':('Phosphorus Sedimentary Basin','the rock-soil-water-food-web cross-section','rock and sediment phosphate reservoirs','weathering/uptake/feeding/decomposition transfers','soil/water/sediment return reservoirs',['Weather phosphate-bearing rock to release phosphate into soil or water.','Move phosphate into producers by assimilation and into consumers by feeding without inventing a major atmospheric pool.','Return phosphate through decomposition/excretion and sedimentation, emphasizing the primarily sedimentary character of the cycle.']),
'U8-L27':('Reserve Population Survey Grid','the marked quadrat and population boundary','same-species population boundary','sampling/quadrat census grid','density estimate and representativeness check',['Define the focal population as same-species organisms interacting within the mapped boundary.','Sample the population with a representative design when a complete census is impractical and record area or volume sampled.','Calculate conceptually what density means as individuals per unit area/volume while keeping density distinct from later dispersion pattern.']),
'U8-L28':('Dispersion Pattern Field','the three equal-density plots','clumped plot','uniform plot','random plot',['Hold total abundance and plot area constant across all three panels so density is identical.','Rearrange only individual positions to produce clumped, uniform, and random dispersion patterns.','Link patchy resources/social aggregation, territoriality/competition, or independent placement to the appropriate pattern without treating the causes as universal.']),
'U8-L29':('Demography Census Station','the age-class life-table desk','age/stage classes','survival and mortality columns','reproduction and demographic summary columns',['Group the same population into age or life-stage classes without changing population identity.','Record survival or mortality across classes and keep these vital statistics tied to the cohort or stage structure.','Add reproductive patterns to the table so demography and life-table use can be distinguished from simple population size.']),
'U8-L30':('Survivorship Curve Observatory','the common age-versus-survival graph','Type I curve','Type II curve','Type III curve',['Plot survivorship against age on the same axes for all three patterns.','Identify Type I by late-life mortality increase, Type II by approximately constant mortality risk, and Type III by high early mortality.','Treat the curves as survivorship patterns rather than fixed species boxes; interpretation follows curve shape.']),
'U8-L31':('Population Change Ledger','the dN/dt births-deaths board with migration side lane','B births input','D deaths subtraction and dN/dt result','immigration/emigration and per-capita comparison lane',['Use the simplified AP model dN/dt = B − D to compute the direction and magnitude of absolute population change when migration is excluded.','Keep N as population size and distinguish absolute dN/dt from any rate scaled per individual.','Add immigration and emigration on a separate extension lane to show why the simplified B − D equation omits migration.']),
'U8-L32':('Life-History Allocation Walk','the lifetime energy allocation schedule','growth and maintenance phase','age at first reproduction and offspring allocation','future survival/reproduction tradeoff panel',['Lay out growth, survival, and reproduction across the organism’s lifetime.','Allocate finite energy among age at first reproduction, offspring number, offspring size, and reproductive frequency.','Show that increasing investment in one life-history component can constrain another, connecting strategies to environmental energy/matter acquisition.']),
'U8-L33':('Life-History Continuum Bridge','the r-to-K selection continuum','low-density/uncrowded end','trait continuum','high-density/near-K end',['Place reproductive traits along a continuum rather than sorting species into two rigid boxes.','At the low-density end, identify conditions favoring traits that maximize reproduction when competition is relatively weak.','At the high-density end near carrying capacity, identify traits favored under stronger crowding/resource competition and preserve the continuum framing.']),
'U8-L34':('Exponential Growth Console','the J-curve equation screen','initial N and abundant-resource assumption panel','dN/dt = rmaxN engine','J-shaped N-versus-time graph',['State the idealized conditions: constant positive per-capita growth and weak resource limitation over the interval.','Apply dN/dt = rmaxN conceptually so absolute growth increases as N increases while rmax remains the maximum per-capita rate.','Draw the accelerating J-shaped curve and label it as an idealized model, not a promise of unlimited real-world growth.']),
'U8-L35':('Carrying Capacity Resource Ceiling','the adjustable K ceiling over the habitat model','resource and environmental-condition panel','K ceiling control','sustainable abundance readout',['Set resource supply and environmental conditions first, then determine the abundance that can be sustained under those conditions.','Label that environment-dependent ceiling K and keep it distinct from current population size N.','Change a resource or environmental condition and move K accordingly to show carrying capacity can change.']),
'U8-L36':('Logistic Growth Console','the S-curve equation screen','current N and K resource ceiling','dN/dt = rmaxN((K−N)/K) engine','S-shaped graph and slowing per-capita growth panel',['Begin with N well below K so the density-limitation term permits relatively rapid growth.','Increase N toward K and visibly shrink (K−N)/K, slowing population growth as resource limitation strengthens.','Draw the S-shaped trajectory and keep density-independent influences as possible real-world departures from the idealized model.']),
'U8-L37':('Density-Dependent Regulation Test Bay','the matched-density vital-rate experiment','low-density population replicate','high-density population replicate','per-capita birth/death response comparison',['Expose low- and high-density populations to the same type of interaction or limiting factor.','Measure the per-capita birth or death effect at each density rather than only total numbers lost or gained.','Classify the factor as density-dependent only when the per-capita effect changes systematically with density; use competition, disease, or predation as possible examples.']),
'U8-L38':('Density-Independent Disturbance Test Bay','the matched-density weather/disturbance experiment','low-density population replicate','high-density population replicate','per-capita impact comparison',['Apply the same weather event or disturbance to populations of different density.','Compare per-capita impact and keep the event’s severity separate from population density.','Classify the effect as density-independent when its per-capita effect is not systematically determined by density, even though total losses may differ.']),
'U8-L39':('Community Map Plaza','the shared landscape with species and resource layers','physical habitat layer','species resource-use/condition layer','interacting-population community layer',['Locate where a focal population lives to define habitat as its physical and biological environment.','Overlay how the species uses resources and tolerates conditions to define ecological niche.','Add other interacting species to define the community and keep community composition/diversity as properties of that interacting set.']),
'U8-L40':('Niche Envelope Chamber','the nested potential-versus-occupied envelope','fundamental-condition/resource envelope','biotic-constraint filters','realized occupied envelope',['Map the full potential range of conditions/resources the species could use without constraining biotic interactions.','Add competition, predation, or other interactions as explicit filters.','Record the occupied subset after those constraints as the realized niche, preserving it as a portion of the fundamental niche.']),
'U8-L41':('Interaction Sign Network','the +/−/0 sign matrix linked to the food-web map','species A effect column','species B effect column','network and population/resource consequence panel',['Assign effects on each species separately using positive, negative, or approximately neutral signs.','Trace how the interaction changes access to energy/matter or population abundance, including direct and indirect network effects such as trophic cascades.','Use the sign/effect pattern to distinguish competition, predation, cooperation, or symbiosis categories without treating the labels as causes by themselves.']),
'U8-L42':('Competition Resource Axis','the shared limiting-resource track','species A resource-use range','species B resource-use range','exclusion or partitioned-use outcome',['Place two species on the same limiting-resource axis and show the −/− consequence of reduced access for both.','Under effectively identical niches and stable conditions, extend competition until one species is excluded or the niches diverge.','Differentiate resource use in space, time, or resource type to demonstrate partitioning that reduces direct competition.']),
'U8-L43':('Consumer-Defense Gallery','the prey/plant and warning-signal comparison corridor','consumer-resource encounter','capture/consumption and detection pathway','cryptic/Batesian/Müllerian defense comparison',['Separate predation, where prey are killed and consumed, from herbivory, where plant or algal tissue is consumed.','Reduce detection by matching organism appearance to background to demonstrate cryptic coloration.','Compare harmless resemblance to a harmful model for Batesian mimicry with shared warning signals among harmful/unpalatable species for Müllerian mimicry.']),
'U8-L44':('Symbiosis Sign Court','the +/−/0 relationship board','species 1 effect','species 2 effect','relationship classification and facilitation panel',['Define symbiosis first as a close, often long-term interspecific interaction without assigning benefit signs yet.','Set the paired effects to +/−, +/+, or +/0 to distinguish parasitism, mutualism, and commensalism.','Place broader positive facilitation on a separate positive-interaction lane when it does not fit a simple feeding relationship.']),
'U8-L45':('Disturbance-Succession Timeline','the before-disturbance-after community strip','pre-disturbance community','disturbance and sequential community-change timeline','abiotic-condition feedback panel',['Record community composition before the disturbance, then apply one event that changes structure, resources, or the physical environment.','Track sequential changes in species composition rather than assuming an immediate stable endpoint.','Show organisms modifying light, soil development, nutrients, or moisture during succession while keeping pH/mineral effects context-dependent.']),
'U8-L46':('Primary-Secondary Succession Fork','the matched post-disturbance sites','bare/no-established-soil-community site','soil-and-biological-legacies-remain site','contrasting succession starting conditions',['Inspect whether an established soil community remains after the event before naming the succession type.','Classify the no-established-soil starting condition as primary succession.','Classify the soil-and-biological-legacies starting condition as secondary succession and keep the distinction tied to starting conditions, not simply disturbance severity.']),
'U8-L47':('Community Composition Counter','the two matched species-count trays','species richness count','relative abundance distribution','combined species-diversity interpretation',['Count the number of species represented to determine species richness.','Calculate or compare the proportion of individuals belonging to each species to determine relative abundance distribution.','Combine richness and abundance distribution conceptually to interpret species diversity, demonstrating why equal richness can still yield different diversity.']),
'U8-L48':('Simpson Index Calculation Table','the count-table-to-equation pipeline','species-specific n counts','total N and 1−Σ(n/N)² equation','index interpretation scale',['For each species, place its individual count in n and place the total community count in N.','Form each (n/N)² term, sum across species, and subtract the sum from 1 while preserving the AP equation exactly.','Interpret larger values in this AP form as greater diversity because dominance by a few species lowers the index; reserve arithmetic practice for Challenge Lab.']),
'U8-L49':('Biodiversity Resilience Observatory','the three-level diversity and disturbance-response display','genetic/species/ecosystem diversity panels','disturbance challenge','resilience/function outcome panel',['Separate genetic, species, and ecosystem diversity as different components of biodiversity.','Apply the same type of disturbance and compare recovery or functional persistence across systems with different component diversity.','State the diversity-resilience relationship as a tendency that can support resilience in many contexts, not an unconditional guarantee.']),
'U8-L50':('Community Influence Removal Test','the keystone-versus-foundation comparison tank','species abundance/habitat-forming panel','species removal or reduction intervention','community-structure response panel',['Compare species abundance with ecological effect before any label is assigned.','Remove or reduce a low-abundance species and identify a disproportionate community response as evidence consistent with a keystone role.','Contrast an abundant or habitat-forming foundation species and keep both labels context-dependent on the specific interaction network.']),
'U8-L51':('Variation-Selection Sequence Lab','the mutation-before-selection timeline','preexisting genetic variation/mutation panel','environmental selection and genotype-fitness comparison','adaptation/heterozygote-advantage outcome',['Place mutation and genetic variation before the environmental selection step so no variant appears because it is needed.','Apply the environment to existing genotypes and compare relative reproductive success, including a case where heterozygotes exceed both homozygotes.','Describe adaptation as the population-level result of selection acting on heritable variation in a particular environment.']),
'U8-L52':('Introduction-Invasion Range Gate','the three-stage range expansion display','historical range and human-mediated arrival','establishment/spread panel','harmful ecological/economic/health impact panel',['Move the species outside its historical range and label the event as introduction without calling it invasive.','Test whether it establishes and spreads under the new ecological conditions.','Apply the invasive label only when spread is associated with harmful effects; keep rapid growth or competition as possible contributors rather than the definition itself.']),
'U8-L53':('Habitat Fragmentation Landscape','the intact-to-fragmented habitat map beside the species-area curve','continuous baseline habitat','fragmentation and area-reduction map','isolation/biodiversity and species-area response panel',['Begin with a continuous habitat and baseline focal-population/community record.','Reduce total habitat and divide remaining habitat into fragments, making isolation visible separately from area loss.','Use the species-area relationship as a general association that larger comparable areas often support more species, then connect habitat loss/fragmentation to biodiversity decline without treating area as the only mechanism.']),
'U8-L54':('Harvest-Replacement Ledger','the removal-versus-recruitment balance board','population replacement/recruitment rate','harvest/removal rate','population trend and extinction-risk panel',['Record the population’s replacement or recruitment over the same interval as removals.','Increase harvest until removals exceed replacement and track sustained population decline.','Connect persistent overharvest to collapse or extinction risk while keeping broader elevated extinction-rate claims qualified by definitions and time scale.']),
'U8-L55':('Persistent Pollutant Food-Web Lab','the contaminant concentration ladder beside a separate acid-deposition lane','persistent contaminant entry at lower trophic level','successive trophic transfer concentrations','high-trophic concentration and separate acid-deposition chemistry panel',['Introduce the same persistent contaminant at a lower trophic level and track concentration through successive consumers.','Show increasing concentration at higher trophic levels only for substances whose persistence and transfer support biological magnification.','Keep acid deposition on a separate chemical pathway whose ecosystem effects depend on pollutant, exposure, and buffering; do not merge it with trophic magnification.']),
'U8-L56':('Eutrophication Water Column','the nutrient-to-oxygen causal sequence','excess nutrient input','increased primary production and decomposition','dissolved-oxygen decline and community shift',['Add excess limiting nutrients to the aquatic system and track the resulting increase in primary production.','Route increased organic matter into decomposition and increase microbial oxygen demand.','Record declining dissolved oxygen and altered aquatic community structure as downstream consequences, preserving the full causal chain.']),
'U8-L57':('Ocean Carbonate Chemistry Tank','the CO₂-pH-carbonate equilibrium display','anthropogenic CO₂ input and dissolution','carbonate-chemistry shift with increased acidity','lower pH and reduced carbonate availability panel',['Dissolve added CO₂ into seawater and shift carbonate chemistry toward greater acidity.','Track the decline in pH and the reduction in carbonate ion availability as equilibria shift.','Connect reduced carbonate availability to challenges for calcifying organisms without claiming identical responses for every species or habitat.']),
'U8-L58':('Regional Change and Biogeography Map Room','the layered regional distribution atlas','geological/meteorological driver layer','latitude/climate/history richness layer','host-pathogen-community context layer',['Apply geological or meteorological change to habitat boundaries and trace resulting changes in ecosystem distribution using biogeographic evidence.','Compare richness across latitude while preserving multiple historical, climatic, and ecological explanations for the broad tropical-richness pattern.','Evaluate disease impact from host density, immunity, species interactions, environment, and pathogen traits, rejecting any single universal biodiversity or habitat explanation.'])
}
assert len(S)==58

quick={'U8-L02','U8-L06','U8-L16','U8-L20','U8-L21','U8-L22','U8-L25','U8-L28','U8-L31','U8-L34','U8-L36','U8-L40','U8-L42','U8-L44','U8-L48','U8-L50','U8-L52','U8-L57'}

base_constraints=[
 'Orient the learner to the exact physical location and fixed left/center/right scientific anchors before any ecological variable, organism, population, reservoir, graph, or chemical system changes state.',
 'Keep ecological scale explicit. An organism, population, community, ecosystem, biome, and biosphere may not silently substitute for one another.',
 'Use real biological entities, conventional arrows, graphs, equations, reservoirs, and interactions as the science-bearing substrate; mnemonic embellishment may be added later only if it does not replace them.',
 'Introduce an exact scientific term only after its defining mechanism, comparison, graph relation, or evidence pattern is visible.',
 'Preserve F1 qualifiers such as can, may, often, generally, under the model assumptions, and context-dependent whenever scientifically necessary.',
 'Do not expose PPT, CED, Campbell, source, lock, enrichment, exam-scope, teacher-management, or pipeline language in later student narrative.',
 'Do not convert teacher enrichment or scope guards into mandatory AP recall; F2 retrieval destinations remain authoritative.',
 'Keep energy flow separate from matter cycling. Energy may transform and dissipate as heat; matter remains conserved through ordinary ecological transformations.',
 'Keep trophic arrows directed from resource/prey toward the consumer receiving energy and matter.',
 'Keep population density separate from dispersion, dN/dt separate from per-capita rate, and N separate from n in Simpson diversity.',
 'Treat exponential and logistic growth as models with assumptions; carrying capacity K is environment-dependent and may change.',
 'Keep interaction signs tied to effects on each species rather than memorized labels alone.',
 'Keep adaptation population-level and nonteleological; mutations do not arise because organisms need them.',
 'Keep environmental-change mechanisms distinct. Introduction is not automatically invasion; biological magnification, eutrophication, ocean acidification, fragmentation, and overharvest follow different causal chains.',
 'Animate only the causal relation needed at the locus; avoid decorative absurdity that competes with the ecology.',
 'Carry one stable continuity object through each journey so spatial route memory reinforces ecological reasoning.',
 'Quick Recall is optional during first exposure and appears only at F3-approved candidate loci; Review later carries the main retrieval burden.'
]

route_by={j['journey_id']:j['route'] for j in arch['journeys']}
locus_by={l['locus_id']:l for l in arch['loci']}

journey_briefs=[]
for j in arch['journeys']:
    jid=j['journey_id']; spec=journey_specs[jid]
    topics=sorted({canon[k]['Topic'] for lid in j['route'] for k in [locus_by[lid]['primary_knowledge_id']]+locus_by[lid]['embedded_knowledge_ids']})
    jguards=[g['Canonical Verified Statement'] for g in scope_guards if g['Topic'] in topics]
    journey_briefs.append({
      'journey_id':jid,'f2_working_title':j['working_title'],'topics':', '.join(topics),'premise':spec['premise'],'mission':spec['mission'],'stakes':spec['stakes'],'unit_guide':unit_guide,
      'continuity_object':spec['continuity_object'],'recurring_scientific_cast':spec['recurring_scientific_cast'],'opening_image':spec['opening_image'],'ending_payoff':spec['ending_payoff'],'tone':spec['tone'],
      'route':j['route'],'route_rule':'Travel the F2 locus order exactly. F3 may make the physical route more concrete but may not reorder, merge, or skip permanent loci without a new architecture version.',
      'scope_guard_constraints':jguards,'narrative_constraints':base_constraints,'status':'JOURNEY_BRIEF_LOCKED_F3_NO_POLISHED_STORY_PROSE'
    })

scene_briefs=[]
for j in arch['journeys']:
    jid=j['journey_id']; route=j['route']; js=journey_specs[jid]
    for i,lid in enumerate(route):
        l=locus_by[lid]; exact_location,micro,left,center,right,steps=S[lid]
        kids=[l['primary_knowledge_id']]+l['embedded_knowledge_ids']
        rs=[canon[k] for k in kids]; cs=[class_by[k] for k in kids]
        prev=route[i-1] if i else None; nxt=route[i+1] if i+1<len(route) else None
        intros=[]
        for n,(r,c) in enumerate(zip(rs,cs),1):
            intros.append({
              'knowledge_id':r['Knowledge ID'],'canonical_term':r['Canonical Label'],'canonical_science':r['Canonical Verified Statement'],'scope_class':r['Scope Class'],
              'exact_name_recall':bool(c['exact_name_recall']),'delayed_review_target':bool(c['exact_name_recall']),'introduction_after_action_step':min(n,3),
              'insertion_rule':'Name the term only after its defining pattern, mechanism, graph relation, transfer, comparison, or ecological consequence is visible. Later prose may clarify the locked science but may not broaden or contradict the F1 statement.',
              'name_support':c['name_support'],'name_support_rule':'Use the scientific scene, spatial relation, and semantic role first. Only after exact-name retrieval failure may F2-approved sound support be added; a sound cue never replaces the ecological mechanism.',
              'spelling_policy':c['spelling_policy']
            })
        guards=[]
        for r in rs:
            for fid in split_ids(r.get('Review Flag IDs','')):
                if fid in flags: guards.append(f"Resolved F1 guard {fid}: {flags[fid]['F1 Resolution']}")
            note=(r.get('Notes') or '').strip()
            if note and ('Boundary:' in note or 'Guard' in note or 'not ' in note.lower() or 'context' in note.lower()): guards.append('F1 boundary: '+note)
        seen=set()
        for k in kids:
            for m in conf_by.get(k,[]):
                if m['set_id'] not in seen:
                    seen.add(m['set_id']); terms=[canon[x]['Canonical Label'] for x in m['knowledge_ids'] if x in canon]
                    guards.append(f"Discrimination requirement {m['set_id']}: {m['purpose']} Keep {', '.join(terms)} physically distinct until the comparison is complete.")
        deps=[]
        for r in rs:
            dep=(r.get('Cross-Unit Dependencies') or '').strip()
            if dep: deps.append({'knowledge_id':r['Knowledge ID'],'term':r['Canonical Label'],'dependency':dep,'rule':'Reactivate prerequisite science only as needed to interpret this ecology relationship; do not assign a duplicate mnemonic identity unless a later architecture explicitly requires one.'})
        q=lid in quick; primary=canon[l['primary_knowledge_id']]
        if nxt:
            nt=locus_by[nxt]['title']
            trans=f"Preserve the resolved state of {js['continuity_object']} and carry the diagnostic distinction, measured variable, transfer result, or ecological consequence from {l['title']} into {nt}. The next locus begins from that preserved state rather than resetting the system."
        else:
            trans=f"{l['title']} closes {jid}. Freeze the final {js['continuity_object']} state and require a route reconstruction in F2 order before leaving the journey."
        scene_briefs.append({
          'scene_brief_id':f'F3-{lid}','locus_id':lid,'journey_id':jid,'bundle_id':l['bundle_id'],'scene_title':l['title'],'exact_location':exact_location,'micro_anchor':micro,'entrance_from':'JOURNEY_ENTRANCE' if not prev else prev,
          'orientation_sentence':f"Enter {exact_location} and stop at {micro}. Keep {left} fixed on the left, {center} as the working center, and {right} fixed on the right. The learner should be able to redraw these positions before the system changes.",
          'spatial_layout':{'left':{'anchor':left,'layout_job':'fixed starting state/reference/input zone'},'center':{'anchor':center,'layout_job':'primary mechanism, calculation meaning, transfer, or diagnostic comparison zone'},'right':{'anchor':right,'layout_job':'fixed consequence/output/interpretation zone'}},
          'f2_spatial_anchor':l['spatial_anchor'],'unit_guide':unit_guide,
          'stable_cast':[{'name':left,'position':'left','visual_identity':f'A conventional scientific representation of {left}, fixed on the learner’s left.','job_in_scene':'Hold the starting state, cue, resource, population, reservoir, or comparison.','type':'SCIENTIFIC_PART_OR_REFERENCE'}, {'name':center,'position':'center','visual_identity':f'The main scientific work model at {exact_location}, centered on {micro}.','job_in_scene':f'Execute the defining action beginning with: {steps[0]}','type':'SCIENTIFIC_PROCESS_OR_STRUCTURE'}, {'name':right,'position':'right','visual_identity':f'A conventional scientific representation of {right}, fixed on the learner’s right.','job_in_scene':'Display the resulting ecological state, interpretation, or consequence.','type':'SCIENTIFIC_PART_OR_OUTPUT'}],
          'continuity_object':js['continuity_object'],'scene_problem':f"Make {primary['Canonical Label']} reconstructable from the visible ecology at {exact_location} while preserving every F1 qualifier and the F2 locus assignment.",
          'science_bearing_action':{'before':f'{left}, {center}, and {right} are visible but unresolved. No term should be inferred until the center operation distinguishes the relevant mechanism or relationship.','trigger':'Mira records the current ecological scale and baseline state on the continuity object, identifies the single unresolved relationship, and changes only the variable or transfer needed to reveal it.','during':steps,'after':f'Freeze the resolved state with {left} on the left, {center} in the center, and {right} on the right. The learner must explain the mechanism and its nearest confusable alternative before moving on.'},
          'knowledge_ids':kids,'primary_knowledge_id':l['primary_knowledge_id'],'term_introductions':intros,'cross_unit_links':deps,
          'visual_spec':{'visual_mode':l['scientific_visual'],'conventional_scientific_visual_required':True,'must_show':[left,center,right,*steps],'must_not_show':['source-management labels, textbook/CED references, or pipeline language','mnemonic characters replacing real ecological entities or graphs','energy being recycled through an ecosystem','food-web arrows pointing from consumer to resource when representing energy/matter transfer','organisms changing genetically because they need an adaptation','carrying capacity shown as an unchangeable species constant','the ten-percent trophic rule represented as an exact law','a nonnative species labeled invasive solely because it is introduced'],'composition_rule':'Preserve the F3 left/center/right geography and the F2 scientific visual. Decorative imagery may later support names but cannot obscure arrows, axes, reservoirs, organisms, or causal state changes.'},
          'misconception_guards':guards,
          'adaptive_name_support':{'first_pass':'Use the visible scientific mechanism, comparison, graph, or transfer first. Do not add a sound cue merely because an ecology term is unfamiliar.','fallback':'After exact-name retrieval failure, use only the record-level F2 name-support classification.','spelling':'No Unit 8 F2 target has a mandatory first-pass spelling gate; spelling support remains adaptive.'},
          'quick_recall':{'enabled':q,'candidate_prompt':f"Without looking back, identify or explain {primary['Canonical Label']} from the scientific relationship you just reconstructed." if q else None,'answer':primary['Canonical Verified Statement'] if q else None,'timing':'Optional first-exposure pause only after the defining relationship and term have already been encountered.' if q else 'No first-exposure interruption at this locus.','hint_rule':'Point to one fixed spatial anchor or one causal change; do not reveal the answer term before the learner attempts retrieval.' if q else None},
          'exit_memory':{'one_sentence_model':f"At {exact_location}, reconstruct {left} → {center} → {right} and explain {primary['Canonical Label']} from the actual ecological mechanism.",'terms_to_carry':[r['Canonical Label'] for r,c in zip(rs,cs) if c['exact_name_recall']],'redraw_test':f"From memory, place {left} on the left, {center} in the center, and {right} on the right, then redraw the relevant arrows, graph, reservoir transfer, population comparison, or chemical sequence."},
          'causal_transition':{'to_locus_id':nxt,'transition_logic':trans},'story_prose_status':'PROHIBITED_UNTIL_F3_BRIEF_QA_PASS','brief_status':'LOCKED_F3_SCENE_BRIEF'
        })

scene_doc={'schema':'memory-palace-v2-unit8-scene-briefs-f3-1.0','generated_utc':GEN,'unit_id':'unit-8','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','student_release':False,'design_standard':'Science-bearing briefs only. No polished learner narrative prose at F3.','counts':{'journeys':8,'scene_briefs':58,'palace_managed_records':211,'term_introductions':211,'optional_first_exposure_recalls':len(quick)},'scene_briefs':scene_briefs}
journey_doc={'schema':'memory-palace-v2-unit8-journey-briefs-f3-1.0','generated_utc':GEN,'unit_id':'unit-8','journey_count':8,'student_release':False,'journeys':journey_briefs}
dump(BRIEFS/'scene-briefs-f3.json',scene_doc); dump(BRIEFS/'journey-briefs-f3.json',journey_doc)

status={'unit_id':'unit-8','number':8,'title':'Ecology','status':'SCENE_BRIEFS_LOCKED_F3_NOT_STUDENT_RELEASED','pipeline_stage':'UNIT8_SCENE_BRIEFS_LOCKED_F3','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','student_release':False,'preview_release':False,'journey_count':0,'scene_count':0,'memory_objects':0,'application_challenges':0,'canonical_records':255,'architecture_journeys':8,'architecture_bundles':22,'architecture_loci':58,'scene_briefs':58,'palace_managed_records':211,'challenge_lab_records':13,'scope_guard_records':31,'exact_name_review_targets':135,'confusable_sets':40,'optional_first_exposure_recalls':len(quick),'next_required_output':'F4A polished narrative for Journey 1 only, generated strictly from the locked F3 briefs and subjected to prose-level spatial, scientific, causal, terminology, and memorability QA before Journey 2 is written.','next_gate':'UNIT8_F4A_JOURNEY1_POLISHED_NARRATIVE'}
dump(U8/'status-f3.json',status); dump(U8/'status.json',status)

f1_paths=['canonical-catalog.json','f1-source-lock.json','f1-manifest.json','review-flags.json','scope-guards.json','ced-atoms.json','ced-coverage.json']
f2_paths=['architecture/learning-classification-f2.json','architecture/palace-architecture-f2.json','content-lock-f2.json','f2-release-manifest.json','status-f2.json']
f3_rel=['content/ap-biology/unit-8/briefs/journey-briefs-f3.json','content/ap-biology/unit-8/briefs/scene-briefs-f3.json','content/ap-biology/unit-8/status-f3.json']
lock={'schema':'memory-palace-v2-unit8-content-lock-f3-1.0','generated_utc':GEN,'unit_id':'unit-8','lock_status':'LOCKED_F3','student_release':False,'f1_protected_hashes':{str((U8/p).relative_to(ROOT)):sha(U8/p) for p in f1_paths},'f2_protected_hashes':{str((U8/p).relative_to(ROOT)):sha(U8/p) for p in f2_paths},'files':{rel:{'bytes':(ROOT/rel).stat().st_size,'sha256':sha(ROOT/rel)} for rel in f3_rel},'policy':'F3 locks science-bearing journey and scene briefs while leaving F1 science and F2 architecture unchanged. F4 may write polished story prose only from these briefs.'}
dump(U8/'content-lock-f3.json',lock)
release={'schema':'memory-palace-v2-unit8-f3-release-1.0','generated_utc':GEN,'unit_id':'unit-8','release_status':'SCENE_BRIEFS_LOCKED_F3_NOT_STUDENT_RELEASED','student_release':False,'canonical_records':255,'palace_managed_records':211,'journey_briefs':8,'scene_briefs':58,'term_introductions':211,'optional_first_exposure_recalls':len(quick),'challenge_lab_records':13,'scope_guard_records':31,'exact_name_review_targets':135,'confusable_sets':40,'polished_story_files':0,'student_runtime_memory_objects':0,'student_runtime_journeys':0,'student_runtime_scenes':0,'next_gate':'F4A Journey 1 only: polished narrative prose from U8-J1 briefs, with spatial clarity, biological causal continuity, exact-term integration, misconception protection, and science-lock QA.'}
dump(U8/'f3-release-manifest.json',release)

course_path=ROOT/'content/ap-biology'/'course.json'; course=read(course_path); e=next(u for u in course['units'] if u['unit_id']=='unit-8')
e.update({'status':'SCENE_BRIEFS_LOCKED_F3_NOT_STUDENT_RELEASED','pipeline_stage':'UNIT8_SCENE_BRIEFS_LOCKED_F3','journey_count':0,'scene_count':0,'canonical_lock':'LOCKED_F1','source_status':'AUDITED_F1_ARCHITECTURE_F2_BRIEFS_F3','student_release':False,'preview_release':False,'canonical_records':255,'architecture_journeys':8,'architecture_bundles':22,'architecture_loci':58,'architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','scene_briefs':58,'palace_managed_records':211,'challenge_lab_records':13,'scope_guard_records':31,'mixed_discrimination_sets':40,'exact_name_review_targets':135,'optional_first_exposure_recalls':len(quick)})
dump(course_path,course)
print('UNIT 8 F3 BUILD PASS')
print(json.dumps(scene_doc['counts'],indent=2))
