from __future__ import annotations
import json,re,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; U7=ROOT/'content/ap-biology/unit-7'
def read(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
CANON={r['knowledge_id']:r for r in read(U7/'source/canonical-unit7-f1.json')['canonical_catalog']}
F3=read(U7/'briefs/scene-briefs-f3.json'); B={b['locus_id']:b for b in F3['scene_briefs'] if b['journey_id']=='U7-J5'}
J=[read(U7/f'journeys/U7-J{i}.json') for i in range(1,5)]
GUIDE={'name':'Dr. Imani Vale','role':'evolutionary-systems curator','visual':'charcoal field jacket, pale-green specimen gloves, brass pointer, and transparent lineage ledger','story_job':'keeps lineage A and lineage B, the gene-flow meter, and every mating or hybrid outcome physically traceable while changing only the barrier or timescale under study'}
CONT='one ancestral population represented by two interbreeding color bands that later separate into lineage A and lineage B; a visible gene-flow meter and mating/fertility outcome panel follow the same two lineages through every barrier. The two color bands keep their lineage identity after separation so every later barrier and hybrid outcome can be traced back to the same ancestral population.'
ROUTE=[
('U7-L42','Species Boundary Desk'),('U7-L43','Allopatric Barrier Island'),('U7-L44','Sympatric Overlap Island'),('U7-L45','Prezygotic Barrier Entry'),('U7-L46','Habitat and Temporal Isolation Gates'),('U7-L47','Behavioral–Mechanical–Gametic Gates'),('U7-L48','Postzygotic Outcome Ward'),('U7-L49','Evolutionary Tempo Gallery'),('U7-L50','Divergence–Radiation–Convergence Overlook')]
Z={
'U7-L42':('within-species gene exchange side','species / reproductive-isolation boundary desk','diverging population side'),
'U7-L43':('source population shore','geographic barrier','isolated descendant population'),
'U7-L44':('population niche / mating subset A','sympatric overlap zone','population niche / mating subset B'),
'U7-L45':('mate-encounter side','prezygotic barrier gate','fertilization threshold'),
'U7-L46':('habitat-isolation gate','encounter-frequency corridor','temporal-isolation gate'),
'U7-L47':('behavioral-isolation signal gate','mechanical-isolation fit gate','gametic-isolation fusion gate'),
'U7-L48':('reduced-hybrid-viability bay','postzygotic-barrier ward','reduced-fertility / hybrid-breakdown bays'),
'U7-L49':('gradual-change timeline','punctuated-equilibrium comparison','stasis interval display'),
'U7-L50':('divergent-evolution / adaptive-radiation branch','macroevolutionary overlook','convergent-evolution / extinction side')}
N={
'U7-L42':[
"The **Species Boundary Desk** overlooks one large breeding lagoon. On your **left**, blue-banded and amber-banded birds move freely across the same nesting ground and the gene-flow meter glows high. Directly **ahead**, the center desk shows mating attempts, fertilization, offspring survival, and later fertility in separate windows. On your **right**, two smaller lineage pens wait behind a boundary light that is still off. Dr. Imani Vale labels the birds lineage A and lineage B only for tracking. At this moment they still belong to one freely interbreeding population.",
"Imani begins with the biological outcome rather than appearance. Blue and amber birds mate across the color bands, fertilization occurs, and the offspring survive and later reproduce. Under the **Biological species concept**, sexually reproducing populations belong to the same species when members can exchange genes through mating and produce viable, fertile offspring. The color bands make ancestry visible, yet color difference alone does not create a species boundary.",
"The desk then names **Species** under that concept. The species boundary here is biological. Gene exchange still connects the lineages. Imani adds a caution to the ledger. The biological species concept is most useful for sexually reproducing organisms and becomes difficult or inapplicable for asexual organisms and many fossil taxa, where direct tests of interbreeding are unavailable.",
"The center gene-flow meter now begins to fall as successful gene exchange is experimentally reduced. The right pens accumulate different allele frequencies, but Imani refuses to call them new species merely because they diverge. Differences can accumulate while enough gene flow remains to keep the populations reproductively connected.",
"Only when the mating and offspring panel shows that gene exchange is sufficiently reduced or prevented does Imani name **Speciation requires reproductive isolation**. New species can arise when populations become reproductively isolated so gene flow is sufficiently reduced or prevented. The barrier is causal because it limits the exchange that otherwise keeps the populations connected.",
"A storm wall rises between the two pens and physically splits the lagoon. The same color bands remain visible on opposite shores, and the gene-flow meter drops for a reason that can now be seen. The next island will test whether geographic separation itself is enough for allopatric speciation, or whether reproductive isolation still has to evolve before the lineage split becomes a species boundary."],
'U7-L43':[
"The **Allopatric Barrier Island** is divided by a new volcanic channel. On your **left**, lineage A occupies the original shore with its blue-and-amber ancestry tags still visible. Directly **ahead**, the water channel cuts the former population in two and the migration arrows stop. On your **right**, lineage B occupies the isolated island while the gene-flow meter falls toward zero. Imani keeps both descendant groups linked to the same ancestral-population card.",
"The barrier changes geography first. Individuals on opposite shores no longer exchange genes routinely. Mutations, drift, and selection can now alter the two gene pools independently. Imani lets allele and trait frequencies diverge over many generations while the channel remains in place. Geographic separation reduces gene flow, but the birds are not declared separate species at the moment the channel forms.",
"After divergence accumulates, the archive temporarily brings members of A and B into a common test enclosure. Early in the sequence they can still mate successfully. Later, reproductive incompatibilities appear. That ordering protects the mechanism. Geography starts the separation, and reproductive isolation can evolve during the period of reduced gene flow.",
"Only then does Imani name **Allopatric speciation**. Allopatric speciation occurs when geographic separation reduces gene flow and diverging populations evolve reproductive isolation. The word allopatric stays attached to the visible channel. It does not mean every geographically isolated population automatically becomes a new species.",
"She places a comparison placard beside it reading **Allopatric and sympatric speciation**. Allopatric speciation involves geographic isolation, while sympatric speciation occurs despite geographic overlap. Geography is the defining contrast between the pathways, while reproductive isolation is still required for species formation in either case.",
"The recall light briefly hides the labels, leaving the channel, the two lineage pens, and the low gene-flow meter visible. When the labels return, the channel retracts from the next exhibit. Lineages A and B now occupy the same continuous habitat, yet mating begins clustering within each lineage. The next scene will ask how reproductive isolation can strengthen when there is no geographic wall to blame."],
'U7-L44':[
"The **Sympatric Overlap Island** has no channel at all. On your **left**, lineage A feeds and mates around one host patch. Directly **ahead**, the shared overlap zone remains physically open from end to end. On your **right**, lineage B concentrates around a different host patch and mating subset in the same geographic area. Imani checks the map twice so no hidden mountain, river, or distance can be smuggled into the explanation.",
"The two lineages can still encounter one another geographically, yet mating becomes increasingly nonrandom within the shared area. Habitat differentiation, mating preference, chromosome changes such as polyploidy in some organisms, or other mechanisms can reduce gene flow without geographic separation. The important feature is that the populations overlap while reproductive exchange declines.",
"Imani keeps the gene-flow meter in the center and watches it fall even though the map remains continuous. The lineages accumulate differences while living side by side. She avoids turning niche use into the only explanation. Several biological mechanisms can produce the needed reduction in gene exchange within geographic overlap.",
"When reproductive isolation becomes established, she names **Sympatric speciation**. Sympatric speciation occurs without geographic separation when gene flow is reduced within an overlapping population and reproductive isolation evolves. The overlap zone remains lit throughout the definition so the contrast with the previous island cannot disappear.",
"She now places the allopatric channel image beside the sympatric overlap map. Both pathways can lead to reproductive isolation. One begins with geographic separation. The other proceeds while geographic overlap remains. The comparison keeps geography and reproductive isolation as two different variables instead of treating them as synonyms.",
"Ahead, the archive stops asking where the lineages live and starts asking exactly where reproduction fails. A long causal track runs from encounter to courtship to mating to gamete transfer to gamete fusion and finally zygote formation. The next gate will divide all barriers that act before that zygote from the failures that can occur afterward."],
'U7-L45':[
"The **Prezygotic Barrier Entry** is a straight reproductive sequence. On your **left**, lineage A and lineage B enter the mate-encounter side together. Directly **ahead**, the center gate has checkpoints for encounter, courtship, mating, gamete transfer, and gamete fusion. On your **right**, a bright threshold marked ZYGOTE lights only if fertilization succeeds. The postzygotic ward is visible beyond the threshold but remains dark.",
"Imani first runs an unrestricted control. The two lineages encounter one another, complete mating, gametes fuse, and the zygote light turns on. She then resets the sequence and blocks a step before fusion. No zygote forms. The exact location of the stop matters more than the dramatic appearance of the barrier.",
"She labels the broad category **Reproductive isolating mechanisms**. Prezygotic and postzygotic barriers can maintain reproductive isolation and reduce gene flow between diverging populations. The category contains mechanisms acting at different times, so the next distinction must be based on the stage of reproduction at which the failure occurs.",
"Because the block occurs before zygote formation, Imani names a **Prezygotic barrier**. A prezygotic reproductive barrier acts before zygote formation by preventing mating or fertilization. The right-side zygote lamp remains off, making timing visible without requiring the learner to memorize a disconnected list.",
"Imani points through the glass toward the untouched postzygotic ward. A postzygotic barrier cannot be diagnosed unless fertilization has already occurred. That simple sequence protects the categories. Before zygote means prezygotic. After a zygote forms, later problems with hybrid survival or reproduction can be postzygotic.",
"The center gate now branches into five diagnostic paths. Two of them prevent potential mates from meeting at all. Different habitat use sends one lineage left. Different breeding time sends another right. The next corridor will separate those encounter barriers before courtship, structure, or gamete compatibility are tested."],
'U7-L46':[
"The **Habitat and Temporal Isolation Gates** share one long encounter corridor. On your **left**, lineage A and lineage B occupy different microhabitats inside the same broader region. Directly **ahead**, the center counter records how often potential mates actually encounter one another. On your **right**, the same lineages occupy overlapping space but the breeding clocks glow in different seasons. Imani leaves mating compatibility turned on so only encounter opportunity changes.",
"At the left gate, individuals remain capable of mating in principle, yet they spend their reproductive lives in different habitats or microhabitats and rarely meet. The encounter counter collapses even though no courtship or anatomical mismatch has been introduced. Imani names **Habitat isolation**. Habitat isolation reduces mating when populations occupy different habitats or microhabitats and therefore rarely encounter one another as potential mates.",
"At the right gate, the habitat map overlaps, but lineage A enters reproductive condition in spring while lineage B does so later in summer. The same location cannot create mating if reproductive timing does not overlap. Imani names **Temporal isolation**. Temporal isolation reduces mating when populations reproduce at different times of day, seasons, or years.",
"She then swaps the displays to prove the diagnostic difference. If the two groups are placed in the same microhabitat but keep different breeding seasons, temporal isolation remains. If their breeding times are synchronized but their reproductive activity occurs in different microhabitats, habitat isolation remains. The barrier is identified by what prevents the encounter.",
"Neither barrier requires a structural mismatch, a failed courtship signal, or incompatible gametes. Those mechanisms are still waiting farther down the reproductive sequence. Imani leaves the prezygotic header visible so all five mechanisms remain members of the same before-zygote class without becoming interchangeable.",
"The encounter corridor ends at three illuminated gates. A courtship signal flashes on the left, a structural-fit model locks in the center, and gametes approach one another on the right. The same two lineages pass into all three tests. The next scene will stop reproduction at three different points and name each barrier from the precise failure."],
'U7-L47':[
"The **Behavioral–Mechanical–Gametic Gates** are arranged in three stages. On your **left**, lineage A performs one courtship display while lineage B responds only to a different signal. Directly **ahead**, the mechanical gate compares reproductive structures and transfer fit. On your **right**, compatible mating has already occurred but gametes meet at a recognition-and-fusion chamber. Imani keeps the zygote threshold visible beyond all three gates and leaves it off until fusion succeeds.",
"At the left gate, the lineages occupy the same place at the same time, yet the courtship signal from one lineage does not elicit the appropriate reproductive response from the other. Imani names **Behavioral isolation**. Behavioral isolation reduces mating when courtship signals or other reproductive behaviors differ between populations.",
"She resets the signal system so courtship proceeds, then stops the pair at the center gate. Their reproductive structures cannot mate successfully or transfer gametes effectively. The failure now occurs later in the sequence and for a different reason. Imani names **Mechanical isolation**. Mechanical isolation prevents successful mating or transfer of gametes when reproductive structures are incompatible.",
"Finally she permits courtship and transfer but carries the gametes to the right fusion chamber. They fail to recognize, survive, or fuse successfully across the lineages. This is **Gametic isolation**. Gametic isolation occurs when sperm and egg or other gametes fail to recognize, survive, or fuse successfully across populations.",
"The three failures remain frozen side by side. Behavior fails before successful mating. Mechanical fit blocks mating or transfer. Gametic incompatibility blocks successful fertilization even after gametes are present. Each is prezygotic because the zygote lamp never turns on, yet the exact failure point remains different.",
"The optional recall shutter hides the term labels while leaving the signal, fit, and fusion gates visible. When it rises, one experimental cross bypasses all five prezygotic barriers. Gamete fusion succeeds and the zygote lamp finally turns green. The next ward begins only after that event and will diagnose what can still fail in hybrids after fertilization."],
'U7-L48':[
"The **Postzygotic Outcome Ward** begins with one fact already established. Fertilization occurred. On your **left**, a hybrid-development bay follows zygotes that fail to develop normally or survive. Directly **ahead**, the center ward records the successful fertilization event so no later outcome can be mistaken for prezygotic isolation. On your **right**, one bay follows surviving but infertile hybrids and another follows later-generation descendants of initially viable, fertile F1 hybrids.",
"Imani places the class label **Postzygotic barrier** above the ward. A postzygotic reproductive barrier acts after fertilization by reducing hybrid viability or reproductive success. The glowing zygote record remains visible beneath the label. Timing alone separates the entire ward from the prezygotic gates behind you.",
"In the left bay, hybrid embryos develop poorly or fail to survive to reproductive age because of genetic incompatibilities. Imani names **Reduced hybrid viability**. Reduced hybrid viability occurs when genetic incompatibilities impair hybrid development or survival. The failure is survival or development after fertilization.",
"In the first right bay, hybrids survive but produce few or no functional gametes or otherwise have greatly reduced reproductive fertility. This is **Reduced hybrid fertility**. Reduced hybrid fertility occurs when hybrids survive but have low or zero reproductive fertility because of chromosomal or genic incompatibilities. Imani explicitly keeps chromosome-number differences as one possible cause, not a universal explanation for hybrid sterility.",
"In the second right bay, the F1 hybrids survive and reproduce, but their later-generation descendants show reduced viability or fertility. Imani names **Hybrid breakdown**. Hybrid breakdown occurs when first-generation hybrids are viable and fertile but later-generation descendants show reduced viability or fertility. The generation labels prevent this from collapsing into the reduced-fertility bay.",
"The recall light hides all labels while leaving the successful zygote in the center and the three later outcomes visible. When the labels return, the archipelago map expands into geological time. The next gallery will no longer classify barriers. It will compare how evolutionary change can accumulate gradually or appear in relatively rapid episodes separated by long intervals of little net morphological change."],
'U7-L49':[
"The **Evolutionary Tempo Gallery** stretches across a single geological time axis. On your **left**, one lineage changes by small accumulated steps across many intervals. Directly **ahead**, a second lineage shows long periods with little net morphological change interrupted by a comparatively short interval of rapid change. On your **right**, the long flat interval is magnified while the same time units remain visible. Imani keeps the lineages and timescale fixed so the comparison is about tempo, not different clocks.",
"She names the broad contrast **Punctuated equilibrium and gradualism**. Evolutionary change can be concentrated in relatively rapid episodes separated by stasis or can accumulate more gradually over long timescales. The word rapid remains relative to geological time. Nothing in the display implies that a complex lineage appears instantaneously in a single generation.",
"The left timeline illustrates gradual accumulation. Small changes add across long spans without requiring a sudden jump. The center timeline illustrates a punctuated pattern in which relatively rapid episodes are separated by longer periods of much less net morphological change. Imani refuses to crown either timeline the universal pattern for all lineages.",
"The right-side flat interval receives its own name **Stasis**. Stasis is a period in which a lineage shows relatively little net morphological evolutionary change in the fossil record. Stasis does not mean no mutation, no reproduction, or no genetic change of any kind. It describes little net morphological change in the fossil record over the interval being considered.",
"Imani overlays the same total time span on both timelines. That prevents a visual trick where one pattern looks faster merely because its axis was compressed. Evolutionary tempo has to be interpreted against the scale shown, just as tree branch length in the previous journey had to be interpreted only when a scale was encoded.",
"At the end of the gallery, the timelines open onto a high overlook containing many branches. Some related lineages spread into different ecological roles. Distant lineages independently acquire similar forms under similar pressures. Other branches terminate completely. The final scene will place these patterns together without confusing divergence with guaranteed speciation or convergence with shared recent ancestry."],
'U7-L50':[
"The **Divergence–Radiation–Convergence Overlook** looks across the entire archipelago. On your **left**, one ancestral branch splits into several related lineages occupying different environments. Directly **ahead**, a large scale map tracks patterns above the species level through branching, diversification, and lineage loss. On your **right**, two distantly related lineages face similar selective pressures and develop similar functional traits, while another branch ends at an extinction marker. Imani brings lineage A and lineage B from the earlier islands into the left display so the long-timescale view remains connected to the speciation story.",
"She first names **Divergent evolution**. Divergent evolution is the accumulation of differences among related lineages as they experience different environments or evolutionary histories. It can contribute to speciation when reproductive isolation develops. The last clause stays visible because divergence alone does not guarantee a new species boundary.",
"When one ancestral lineage rapidly diversifies into several descendant lineages as new ecological opportunities become available, Imani names **Adaptive radiation**. Adaptive radiation is rapid diversification of one ancestral lineage into multiple descendant lineages, often associated with newly available ecological opportunities. The combined relationship **Divergent evolution and adaptive radiation** remains on the left because adaptive radiation is a particularly extensive pattern of diversification from common ancestry.",
"On the right, distantly related lineages encounter similar selective pressures and independently evolve similar phenotypic adaptations. Imani names **Convergent evolution**. Similar selective pressures can independently favor similar phenotypic adaptations in distantly related populations or species. Similarity here does not imply that the similar trait came from a recent common ancestor.",
"The center overlook supplies the scale term **Macroevolution**. Macroevolution refers to broad evolutionary patterns above the species level, including patterns of speciation, extinction, and diversification. Imani then points to the branch that ends permanently. **Extinction** is the permanent loss of a species or lineage when no living members remain. Population decline alone does not count if living members persist.",
"The archive finally reconnects every part of the journey. Reproductive isolation established species boundaries. Allopatric and sympatric pathways differed in geography. Prezygotic barriers stopped mating or fertilization, while postzygotic barriers acted after fertilization. Over longer timescales, lineages can diverge, radiate, converge, persist through stasis, change gradually or in punctuated episodes, and go extinct. The archipelago clears its final warning because every pattern now has a causal place without turning every difference into speciation or every similarity into common ancestry."],
}
EXTRA={
'U7-L42':"Imani tests one more deceptive case. The two lineages now differ visibly in beak size and song pitch, yet the outcome panel still shows regular interbreeding and viable, fertile offspring. The species boundary light stays off. She then restores similar appearance while blocking successful gene exchange, and the boundary warning returns. The comparison makes the criterion reconstructable. Under the biological species concept, reproductive compatibility and gene exchange carry the classification, while visible similarity or difference alone does not decide species membership. The ledger therefore stores phenotype difference and reproductive isolation in separate fields so one can never silently stand in for the other.",
'U7-L43':"Imani also reverses the geography without erasing the history. The channel remains for hundreds of displayed generations while the two populations accumulate different allele frequencies and mating cues. When the barrier is finally removed, the system asks whether gene flow resumes. If the lineages mate freely again, geographic separation produced divergence without a completed species boundary. If reproductive isolation persists after contact, the allopatric pathway has produced a lasting barrier to gene exchange. The reunion test keeps the story focused on reproductive isolation instead of treating physical distance as a permanent definition of species.",
'U7-L44':"To make the overlap condition unmistakable, Imani draws one transparent boundary around both lineages. Every individual remains inside the same geographic outline while the mating network within that outline becomes increasingly partitioned. She then swaps the mechanism. A habitat preference is removed and a strong assortative mating preference is introduced. Gene flow can still fall. The scene therefore teaches the defining sympatric condition without tying it to one favorite example. Geographic overlap remains, while biological processes inside the shared area reduce gene exchange and allow reproductive isolation to evolve.",
'U7-L45':"The gate then runs three quick counterexamples. A hybrid that dies after fertilization is sent forward to the postzygotic ward because the zygote already formed. A pair that never meets is stopped before mating and stays prezygotic. A pair that mates but whose gametes never fuse also stays prezygotic because fertilization never occurs. Imani has the learner follow the same illuminated sequence each time. Encounter, courtship, mating, gamete transfer, fusion, zygote, survival, fertility. Barrier class follows the stage at which the sequence fails, which makes the later named mechanisms easier to locate.",
'U7-L46':"Imani now places the same two birds in a neutral test chamber during the same breeding hour. They mate successfully, confirming that the earlier barriers did not require behavioral dislike, mechanical mismatch, or gametic incompatibility. She then restores only the habitat difference and encounters vanish again. Next she restores only the seasonal offset and encounters vanish for a different reason. The middle encounter counter gives both mechanisms the same consequence, reduced mating, while the left and right gates preserve the diagnostic cause. The student can therefore retrieve habitat isolation from *where* the populations reproduce and temporal isolation from *when* they reproduce.",
'U7-L47':"The three gates are then run in the wrong order on purpose. Gametes cannot be tested if courtship never leads to mating, and mechanical fit cannot be diagnosed from a pair that never attempts mating. Imani resets the sequence and allows each earlier step to succeed before testing the next barrier. That procedural order keeps the terms causal. Behavioral isolation concerns reproductive signals or behavior. Mechanical isolation concerns successful mating or gamete transfer. Gametic isolation concerns recognition, survival, or fusion of gametes after they are available. All three reduce gene flow before a zygote forms.",
'U7-L48':"Imani places a mule image beside the reduced-fertility bay but refuses to let it become the definition. Chromosome-number or structural differences can contribute to meiotic problems and sterility in some hybrids, while genic incompatibilities can also reduce fertility. She then moves the image away and leaves the outcome criterion visible. Survive but reproduce poorly belongs in reduced hybrid fertility regardless of the exact molecular cause. The hybrid-breakdown bay remains separate because its F1 generation can be viable and fertile. Only later descendants reveal the reduced viability, reduced fertility, or both that define that barrier.",
'U7-L49':"The gallery adds fossil silhouettes at equal time intervals so the learner can see what the record would look like under each tempo. On the gradual track, successive forms shift incrementally across many intervals. On the punctuated track, long stretches show little net morphological difference, followed by a geologically shorter interval with greater change. Imani reminds the learner that the fossil record is incomplete, so tempo interpretations rely on evidence quality and sampling. The two models describe patterns of evolutionary change through time, not opposing laws that force every lineage into one category forever.",
'U7-L50':"Imani makes one final discrimination by placing three arrows over the overlook. The first arrow starts from a shared ancestor and spreads outward as related lineages accumulate differences. That is divergence. The second starts from one ancestral lineage and fans rapidly into many ecological roles when opportunities are available. That is adaptive radiation. The third begins from distant branches and points toward similar phenotypes under similar selective pressures. That is convergence. None of those arrows alone tells you that a new species formed. The reproductive-isolation logic from the beginning of the archipelago remains the gate for speciation, while these arrows describe broader evolutionary patterns.",
}
for lid,paragraph in EXTRA.items():
    N[lid].insert(-1,paragraph)

EXTRA2={
'U7-L43':"The gene-flow meter is also paired with a divergence meter, and the two are not allowed to substitute for one another. Divergence can increase while some migration still occurs, and migration can remain near zero before reproductive isolation is complete. The allopatric pathway is therefore remembered as a sequence. geographic separation reduces gene flow, independent change accumulates, and reproductive isolation must eventually establish the species boundary.",
'U7-L44':"The shared-area outline never disappears during the test. Imani uses it as a visual checksum. If a physical barrier is introduced, the scene has become allopatric and must be sent back to the previous island. If the outline remains shared while mating connections split into separate networks, the sympatric condition is preserved. The geography test therefore stays independent from the mechanism that reduces mating within that geography.",
'U7-L45':"A red line is drawn immediately before the zygote box. Everything that fails to the left of that line is prezygotic. Everything that fails only after the zygote box belongs to the postzygotic category. The line is deliberately simple because it will remain visible through the next three scenes, giving habitat, temporal, behavioral, mechanical, and gametic isolation one shared timing anchor without making their mechanisms identical.",
'U7-L46':"The corridor records encounter rate rather than reproductive success after contact. That distinction matters because both habitat and temporal isolation can reduce mating before the organisms ever test courtship or gamete compatibility. Imani leaves the later gates physically closed. If the lineages never encounter one another as potential mates, the causal chain stops here and no downstream failure is needed to explain the reduced gene flow.",
'U7-L47':"At the end, Imani places three small flags directly on the reproductive sequence. SIGNAL before mating, FIT at mating or transfer, FUSION at fertilization. The flags remain in that order even if the lineages are redrawn. This gives each exact name a durable location in the causal pathway and prevents gametic isolation from drifting backward into courtship or mechanical isolation from drifting forward into postzygotic development.",
'U7-L48':"The ward keeps the generation number printed on every hybrid record. F1 survival, F1 fertility, and later-generation outcomes are separate columns. Imani makes the learner point to the column that fails before naming the barrier. That simple act prevents reduced hybrid viability, reduced hybrid fertility, and hybrid breakdown from becoming three synonyms for a bad hybrid outcome. Timing and reproductive consequence remain part of the definition.",
'U7-L49':"Imani also keeps speciation barriers off this gallery. Punctuated equilibrium, gradualism, and stasis describe tempo in evolutionary history, not mechanisms of reproductive isolation. A lineage can show either tempo while speciation, selection, drift, or other processes operate underneath. The gallery therefore answers a different question from the archipelago gates. It asks how change is distributed through time, not what barrier created a species boundary.",
}
for lid,paragraph in EXTRA2.items():
    N[lid].insert(-1,paragraph)

CHECK={'U7-L43','U7-L47','U7-L48'}
def wc(ps): return len(re.findall(r"\b[\w’′'-]+\b",' '.join(ps)))
def zones(lid):
 a,b,c=Z[lid]; return [
 {'position':'left','label':a,'symbol':'LEFT','description':f'{a} remains the fixed left-side reference for this locus.'},
 {'position':'center','label':b,'symbol':'CENTER','description':f'{b} carries the science-bearing comparison or barrier in the center.'},
 {'position':'right','label':c,'symbol':'RIGHT','description':f'{c} remains the fixed right-side consequence or comparison.'}]
def cast(lid):
 return [{'name':GUIDE['name'],'kind':'guide','visual':GUIDE['visual'],'job':GUIDE['story_job']},
 {'name':'Lineage A','kind':'persistent descendant population','visual':'blue-banded descendants whose ancestry remains traceable to the original mixed population','job':'remains one of the same two tracked populations through every geography, barrier, hybrid, and macroevolution scene'},
 {'name':'Lineage B','kind':'persistent descendant population','visual':'amber-banded descendants whose ancestry remains traceable to the original mixed population','job':'remains the comparison population throughout the complete speciation route'},
 {'name':'Gene-flow meter','kind':'persistent causal instrument','visual':'a transparent meter showing relative gene exchange between lineages A and B','job':'keeps reduced gene flow visible as the central causal variable in speciation'},
 {'name':'Mating and hybrid outcome panel','kind':'persistent reproductive instrument','visual':'a causal sequence from encounter through courtship, mating, gamete fusion, zygote, hybrid survival, and fertility','job':'shows the exact stage at which each reproductive barrier acts'},
 {'name':Z[lid][0],'kind':'left spatial anchor','visual':Z[lid][0],'job':'fixed left-side reference'},
 {'name':Z[lid][1],'kind':'center spatial anchor','visual':Z[lid][1],'job':'center science-bearing mechanism'},
 {'name':Z[lid][2],'kind':'right spatial anchor','visual':Z[lid][2],'job':'fixed right-side consequence'}]
def beats(lid):
 b=B[lid]; terms={t['knowledge_id']:t for t in b['term_introductions']}; out=[]
 for kid in b['knowledge_ids']:
  t=terms[kid]; c=CANON[kid]
  out.append({'object_id':kid,'term':t['canonical_term'],'story':f"Recall {t['canonical_term']} from the visible lineage, gene-flow, geography, mating-stage, or hybrid-outcome relationship in {lid}.",'science':c['canonical_verified_statement'],'exact_name':bool(t['exact_name_recall']),'hint':f"Use the fixed left/center/right barrier layout in {lid}.",'name_support':t['name_support'],'reactivation_mode':t['reactivation_mode'],'scope_class':t['scope_class']})
 return out
scenes=[]
for i,(lid,locus) in enumerate(ROUTE):
 b=B[lid]; ps=N[lid]; cp=lid in CHECK
 scenes.append({'scene_index':i,'locus_id':lid,'locus':locus,'title':ps[0].split('**')[2] if '**' in ps[0] else locus,'scene_kicker':b['scene_problem'],'location_description':b['micro_anchor'],'scene_layout':{'orientation':b['orientation_sentence'],'zones':zones(lid)},'cast':cast(lid),'continuity_object':CONT,'story_open':ps[0],'story_paragraphs':ps,'story_close':ps[-1],'object_ids':list(b['knowledge_ids']),'story_beats':beats(lid),'prior_unit_reactivation':b['prior_unit_reactivation'],'misconception_guards':b['misconception_guards'],'checkpoint':cp,'checkpoint_object_id':b['primary_knowledge_id'] if cp else None,'checkpoint_prompt':b['quick_recall']['candidate_prompt'] if cp else '','checkpoint_answer':b['quick_recall']['answer'] if cp else '','next_locus':ROUTE[i+1][1] if i+1<len(ROUTE) else None,'f3_scene_brief_id':b['scene_brief_id'],'narrative_word_count':wc(ps)})
journey={'palace_id':'U7-J5','unit_id':'unit-7','palace_name':'Speciation Barrier Archipelago','story_title':'The Archipelago That Kept Calling Every Difference a New Species','tagline':'Follow the same two descendant lineages through geography, gene flow, mating, fertilization, hybrid outcomes, and deep time until every species boundary and evolutionary pattern has a visible cause.','guide':GUIDE,'premise':'The archipelago has begun declaring new species whenever two populations look different. Dr. Imani Vale freezes lineage A and lineage B, a gene-flow meter, and one reproductive-outcome sequence so no species claim can be accepted until reduced gene flow and reproductive isolation are actually demonstrated.','mission':'Track one ancestral population into two descendant lineages, distinguish allopatric from sympatric pathways, classify five prezygotic and three postzygotic barriers by their exact failure point, then place tempo, divergence, adaptive radiation, convergence, macroevolution, and extinction on longer timescales without confusing divergence with guaranteed speciation.','finale':'The archipelago clears when every species boundary is tied to reproductive isolation and every longer-term evolutionary pattern remains distinct from the mechanism that creates or maintains a species boundary.','estimated_minutes':32,'scene_count':9,'checkpoint_count':3,'student_release':'DEVELOPER_PREVIEW_F4E','preview_release':True,'narrative_design':'U7-F4E-NARRATIVE-1.0','learner_rule':'Keep lineage A and lineage B, the gene-flow meter, and the encounter-to-hybrid outcome sequence fixed. Identify barriers by where reproduction fails and pathways by whether geographic separation is present.','route_orientation':'Travel from the species boundary desk through allopatric and sympatric geography, then through prezygotic and postzygotic barriers, and finish on long-timescale tempo and macroevolution overlooks.','route':[{'scene_index':i,'locus':l,'short':l,'floor':'archipelago route','symbol':f'S{i+1}'} for i,(_,l) in enumerate(ROUTE)],'scenes':scenes,'source_brief_lock':'LOCKED_F3','scientific_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','frozen_prior_journey_lock':'LOCKED_F4D_J1_J4'}
(U7/'journeys/U7-J5.json').write_text(json.dumps(journey,ensure_ascii=False,indent=2)+'\n')
summary={'schema':'memory-palace-v2-unit7-f4e-journeys-1.0','unit_id':'unit-7','stage':'F4E','student_release':False,'preview_release':True,'journey_count':5,'scene_count':50,'checkpoint_count':sum(x['checkpoint_count'] for x in J)+3,'guided_journeys':[{k:x[k] for k in ['palace_id','palace_name','story_title','tagline','guide','premise','mission','finale','estimated_minutes','scene_count','checkpoint_count','student_release','narrative_design']} for x in J+[journey]]}
(U7/'journeys-f4e.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
status={'unit_id':'unit-7','number':7,'title':'Natural Selection','status':'F4E_JOURNEYS1_5_POLISHED_DEVELOPER_PREVIEW','pipeline_stage':'F4E_JOURNEY5_NARRATIVE','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','narrative_lock':'LOCKED_F4E_J1_J5','student_release':False,'preview_release':True,'journey_count':5,'scene_count':50,'memory_objects':0,'application_challenges':0,'canonical_records':215,'architecture_journeys':6,'architecture_bundles':23,'architecture_loci':55,'scene_briefs':55,'palace_managed_records':174,'challenge_lab_records':16,'scope_guard_records':25,'exact_name_review_targets':94,'confusable_sets':33,'optional_first_exposure_recalls':18,'f4e_journey':'U7-J5','f4e_scene_count':9,'f4e_knowledge_records':25,'f4e_exact_name_targets':23,'f4e_optional_recalls':3,'next_required_output':'F4F polished narrative for Journey 6 only after Journeys 1 through 5 remain frozen and all F1-F4E gates continue to pass.'}
(U7/'status-f4e.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n'); (U7/'status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n')
course=read(ROOT/'content/ap-biology/course.json'); u=next(x for x in course['units'] if x['unit_id']=='unit-7'); u.update({'status':status['status'],'journey_count':5,'scene_count':50,'student_release':False,'preview_release':True,'source_status':'AUDITED_F1_ARCHITECTURE_F2_BRIEFS_F3_NARRATIVE_F4A_F4B_F4C_F4D_F4E','narrative_lock':'LOCKED_F4E_J1_J5','narrative_journeys':5,'pipeline_stage':'F4E_JOURNEY5_NARRATIVE'}); (ROOT/'content/ap-biology/course.json').write_text(json.dumps(course,ensure_ascii=False,indent=2)+'\n')
doc=['# Unit 7 F4E · Journey 5 Narrative','','## The Archipelago That Kept Calling Every Difference a New Species','',journey['tagline'],'','### Physical route','', ' → '.join(x[1] for x in ROUTE),'']
for s in scenes:
 doc += [f"## {s['scene_index']+1}. {s['locus']}",'']+s['story_paragraphs']+['']
 if s['checkpoint']: doc += ['**Optional Quick Recall**','',s['checkpoint_prompt'],'']
(ROOT/'docs/UNIT7_F4E_JOURNEY5_STORY.md').write_text('\n'.join(doc))
# lock prior journey and release artifacts
f4d=read(U7/'content-lock-f4d.json')
prior=dict(f4d.get('f4a_f4c_prior_narrative_protection',{}))
for rel in [
 'content/ap-biology/unit-7/journeys/U7-J1.json','content/ap-biology/unit-7/journeys/U7-J2.json','content/ap-biology/unit-7/journeys/U7-J3.json','content/ap-biology/unit-7/journeys/U7-J4.json',
 'content/ap-biology/unit-7/journeys-f4d.json','content/ap-biology/unit-7/status-f4d.json','content/ap-biology/unit-7/content-lock-f4d.json','content/ap-biology/unit-7/f4d-release-manifest.json',
 'docs/UNIT7_F4D_JOURNEY4_STORY.md','docs/UNIT7_F4D_RELEASE.md','docs/UNIT7_F4D_QA.md','docs/UNIT7_F4D_PACKAGE_QA.md']:
 p=ROOT/rel
 if p.exists(): prior[rel]={'bytes':p.stat().st_size,'sha256':sha(p)}
locked=['journeys/U7-J5.json','journeys-f4e.json','status-f4e.json']; files={r:{'bytes':(U7/r).stat().st_size,'sha256':sha(U7/r)} for r in locked}
lock={'schema':'memory-palace-v2-unit7-f4e-lock-1.0','unit_id':'unit-7','lock_status':'LOCKED_F4E_J1_J5','student_release':False,'preview_release':True,'prior_narrative_protection':prior,'journey_id':'U7-J5','scene_count':9,'knowledge_record_count':25,'exact_name_target_count':23,'checkpoint_count':3,'files':files}
(U7/'content-lock-f4e.json').write_text(json.dumps(lock,ensure_ascii=False,indent=2)+'\n')
release={'schema':'memory-palace-v2-unit7-f4e-release-1.0','unit_id':'unit-7','release_status':status['status'],'student_release':False,'preview_release':True,'completed_journeys':['U7-J1','U7-J2','U7-J3','U7-J4','U7-J5'],'journeys':5,'scenes':50,'f4e_scenes':9,'f4e_knowledge_records':25,'f4e_exact_name_targets':23,'f4e_optional_first_exposure_recalls':3,'narrative_lock':'LOCKED_F4E_J1_J5','next_stage':'F4F Journey 6 polished narrative'}
(U7/'f4e-release-manifest.json').write_text(json.dumps(release,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'journey':'U7-J5','scenes':9,'records':25,'exact':23,'checkpoints':3,'words':sum(x['narrative_word_count'] for x in scenes),'counts':[x['narrative_word_count'] for x in scenes]},indent=2))
