from __future__ import annotations
import json, hashlib, re
from collections import Counter
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
U3=ROOT/'content'/'ap-biology'/'unit-3'
SRC=U3/'source'/'canonical-unit3-f1.json'
ARCH=U3/'architecture'
ARCH.mkdir(parents=True,exist_ok=True)
GENERATED_UTC='2026-09-03T02:05:00+00:00'

RAW_LOCI=[('U3-L01',
  'U3-J1',
  'U3-B01',
  'Catalyst Energy Ramp',
  'the reaction-energy track with an uncatalyzed hill beside a lower enzyme-catalyzed route',
  ['uncatalyzed activation-energy hill', 'enzyme-catalyzed lower barrier', 'product-side exit'],
  'U3-K-003',
  ['U3-K-001', 'U3-K-002', 'U3-K-003', 'U3-K-083'],
  'ENERGY_PROFILE_COMPARISON'),
 ('U3-L02',
  'U3-J1',
  'U3-B01',
  'Active-Site Dock',
  'the molecular docking bay where substrate shape and charge are tested against an enzyme pocket',
  ['free substrate approach lane', 'enzyme active-site docking pocket', 'enzyme-substrate complex display'],
  'U3-K-004',
  ['U3-K-004', 'U3-K-005', 'U3-K-084', 'U3-K-085', 'U3-K-086'],
  'MOLECULAR_DOCKING_SEQUENCE'),
 ('U3-L03',
  'U3-J1',
  'U3-B01',
  'Catalytic Turnover Bench',
  'the reusable enzyme station that releases product and returns the catalyst to service',
  ['substrate arrival', 'catalytic turnover bench', 'product release and enzyme reset'],
  'U3-K-087',
  ['U3-K-087', 'U3-K-088'],
  'CATALYTIC_CYCLE'),
 ('U3-L04',
  'U3-J2',
  'U3-B02',
  'Enzyme Stability Chamber',
  'the enzyme-shape monitor between controlled temperature and pH panels',
  ['temperature control', 'enzyme structure/function monitor', 'pH and chemical environment control'],
  'U3-K-007',
  ['U3-K-006', 'U3-K-007', 'U3-K-008', 'U3-K-009', 'U3-K-091'],
  'STRUCTURE_FUNCTION_STRESS_TEST'),
 ('U3-L05',
  'U3-J2',
  'U3-B02',
  'Collision and Saturation Track',
  'the reaction-rate conveyor where substrate concentration and temperature can be varied independently',
  ['substrate concentration feeder', 'enzyme reaction-rate track', 'temperature/collision-frequency control'],
  'U3-K-010',
  ['U3-K-010', 'U3-K-011', 'U3-K-092'],
  'RATE_VARIABLES_GRAPH_SCENE'),
 ('U3-L06',
  'U3-J2',
  'U3-B03',
  'Cofactor Assembly Station',
  'the incomplete enzyme assembly bench with removable helper components',
  ['apoenzyme/protein component', 'helper-binding assembly bench', 'active holoenzyme output'],
  'U3-K-093',
  ['U3-K-093', 'U3-K-094', 'U3-K-095'],
  'MOLECULAR_ASSEMBLY_COMPARISON'),
 ('U3-L07',
  'U3-J2',
  'U3-B03',
  'Competitive Inhibitor Gate',
  'the active-site checkpoint where substrate and competitor approach the same binding pocket',
  ['substrate lane', 'shared active-site gate', 'competitive inhibitor lane'],
  'U3-K-012',
  ['U3-K-012', 'U3-K-097'],
  'COMPETITION_MECHANISM'),
 ('U3-L08',
  'U3-J2',
  'U3-B03',
  'Allosteric Control Panel',
  'the enzyme control console with a regulatory site physically separated from the active site',
  ['active-site reaction zone', 'enzyme body', 'allosteric regulatory site'],
  'U3-K-013',
  ['U3-K-013', 'U3-K-098', 'U3-K-099', 'U3-K-100', 'U3-K-101'],
  'ALLOSTERIC_CONTROL_SCENE'),
 ('U3-L09',
  'U3-J2',
  'U3-B03',
  'Cooperative Binding Array',
  'the multi-subunit enzyme display where one ligand-binding event changes later binding behavior',
  ['first binding site', 'linked subunit array', 'later binding sites'],
  'U3-K-102',
  ['U3-K-102'],
  'COOPERATIVITY_SEQUENCE'),
 ('U3-L10',
  'U3-J2',
  'U3-B04',
  'Feedback Loop Control Room',
  'the metabolic pathway board where a downstream product feeds back to an earlier control enzyme',
  ['pathway inputs and early enzyme', 'multi-step metabolic route', 'end product feedback line'],
  'U3-K-103',
  ['U3-K-103', 'U3-K-104'],
  'PATHWAY_FEEDBACK_LOOP'),
 ('U3-L11',
  'U3-J2',
  'U3-B04',
  'Irreversible Inhibition Lockout',
  'the damaged enzyme bay where a persistent inhibitor prevents recovery after ordinary conditions are restored',
  ['functional enzyme reference', 'irreversibly inhibited enzyme', 'failed recovery test'],
  'U3-K-096',
  ['U3-K-096'],
  'DISTINCTION_STRESS_TEST'),
 ('U3-L12',
  'U3-J3',
  'U3-B05',
  'Metabolism Route Map',
  'the central pathway map splitting degradative routes from biosynthetic routes',
  ['catabolic breakdown branch', 'shared metabolic pathway map', 'anabolic synthesis branch'],
  'U3-K-055',
  ['U3-K-019', 'U3-K-020', 'U3-K-055', 'U3-K-056', 'U3-K-057', 'U3-K-058', 'U3-K-089', 'U3-K-090'],
  'SYSTEM_PATHWAY_MAP'),
 ('U3-L13',
  'U3-J3',
  'U3-B05',
  'Energy Forms Gallery',
  'the conversion gallery showing motion, heat, position, and molecular-bond energy',
  ['kinetic and thermal displays', 'energy-conversion turntable', 'potential and chemical energy displays'],
  'U3-K-059',
  ['U3-K-059', 'U3-K-060', 'U3-K-061', 'U3-K-062', 'U3-K-063'],
  'ENERGY_FORM_COMPARISON'),
 ('U3-L14',
  'U3-J3',
  'U3-B06',
  'First-Law Ledger',
  'the closed accounting wall that tracks energy entering, changing form, and leaving',
  ['energy input ledger', 'transformation/accounting panel', 'energy output ledger'],
  'U3-K-065',
  ['U3-K-015', 'U3-K-064', 'U3-K-065'],
  'THERMODYNAMIC_ACCOUNTING'),
 ('U3-L15',
  'U3-J3',
  'U3-B06',
  'Entropy and Living Order Chamber',
  'the order-maintenance room where local cellular organization is sustained while energy disperses to the surroundings',
  ['organized cellular system', 'maintenance-energy input', 'dispersed heat and environmental entropy'],
  'U3-K-066',
  ['U3-K-016', 'U3-K-018', 'U3-K-066', 'U3-K-067'],
  'THERMODYNAMIC_DIRECTION_SCENE'),
 ('U3-L16',
  'U3-J3',
  'U3-B06',
  'Free-Energy Terrain',
  'the reaction landscape with downhill exergonic and uphill endergonic paths relative to cellular equilibrium',
  ['exergonic downhill path', 'free-energy/equilibrium reference', 'endergonic uphill path'],
  'U3-K-068',
  ['U3-K-068', 'U3-K-070', 'U3-K-071', 'U3-K-072'],
  'ENERGY_LANDSCAPE'),
 ('U3-L17',
  'U3-J3',
  'U3-B07',
  'Cellular Work Dock',
  'the three-bay work station where an energy-releasing process powers chemical, transport, and mechanical work',
  ['mechanical-work bay', 'energy-coupling junction', 'transport and chemical-work bays'],
  'U3-K-017',
  ['U3-K-014', 'U3-K-017', 'U3-K-073', 'U3-K-074', 'U3-K-075'],
  'ENERGY_COUPLING_WORK_SCENE'),
 ('U3-L18',
  'U3-J3',
  'U3-B07',
  'ATP Structure Station',
  'the enlarged ATP model beside ADP and inorganic phosphate',
  ['adenine-ribose body', 'triphosphate chain', 'ADP plus Pi comparison'],
  'U3-K-076',
  ['U3-K-076', 'U3-K-077'],
  'MOLECULAR_STRUCTURE_MODEL'),
 ('U3-L19',
  'U3-J3',
  'U3-B07',
  'ATP Hydrolysis Forge',
  'the coupling forge where ATP hydrolysis changes reactant free energy through phosphorylation',
  ['ATP hydrolysis input', 'coupling/phosphorylation forge', 'altered phosphorylated target'],
  'U3-K-078',
  ['U3-K-078', 'U3-K-079', 'U3-K-080', 'U3-K-081'],
  'COUPLED_REACTION_SEQUENCE'),
 ('U3-L20',
  'U3-J3',
  'U3-B07',
  'ATP Regeneration Wheel',
  'the continuously turning ATP/ADP cycle driven by energy from catabolic processes and consumed by cellular work',
  ['ADP plus Pi return path', 'ATP regeneration wheel', 'ATP use for cellular work'],
  'U3-K-082',
  ['U3-K-082'],
  'ENERGY_CYCLE'),
 ('U3-L21',
  'U3-J3',
  'U3-B08',
  'Conserved Metabolism Archive',
  'the cross-species pathway archive showing shared core metabolic logic in diverse organisms',
  ['prokaryotic pathway record', 'conserved core reactions display', 'eukaryotic pathway record'],
  'U3-K-021',
  ['U3-K-021'],
  'EVOLUTIONARY_COMPARISON'),
 ('U3-L22',
  'U3-J4',
  'U3-B09',
  'Carbon Strategy Entrance',
  'the three-way carbon-and-energy intake gate comparing autotrophic and heterotrophic strategies',
  ['photoautotroph light-input lane', 'autotroph carbon-building center', 'heterotroph organic-carbon lane'],
  'U3-K-105',
  ['U3-K-022', 'U3-K-023', 'U3-K-105', 'U3-K-106', 'U3-K-107'],
  'NUTRITION_STRATEGY_COMPARISON'),
 ('U3-L23',
  'U3-J4',
  'U3-B09',
  'Oxygenation Timeline',
  'the evolutionary timeline from prokaryotic oxygenic photosynthesis to atmospheric oxygenation and eukaryotic photosynthesis',
  ['ancestral photosynthetic prokaryotes', 'atmospheric oxygen rise', 'eukaryotic photosynthetic lineage'],
  'U3-K-024',
  ['U3-K-024', 'U3-K-025', 'U3-K-026', 'U3-K-108'],
  'EVOLUTIONARY_TIMELINE'),
 ('U3-L24',
  'U3-J4',
  'U3-B10',
  'Leaf Gas-Exchange Balcony',
  'the leaf cross-section balcony with mesophyll tissue behind adjustable stomatal pores',
  ['stomatal pore and guard-cell opening', 'leaf/mesophyll photosynthetic tissue', 'CO2/O2/water-vapor diffusion paths'],
  'U3-K-110',
  ['U3-K-109', 'U3-K-110'],
  'STRUCTURE_FUNCTION_CUTAWAY'),
 ('U3-L25',
  'U3-J4',
  'U3-B10',
  'Chloroplast Compartment Gallery',
  'the chloroplast cutaway linking stroma, thylakoid membranes, and grana to their photosynthetic roles',
  ['chloroplast envelope and stroma', 'thylakoid membrane/granum stack', 'reaction-location labels'],
  'U3-K-027',
  ['U3-K-027', 'U3-K-028', 'U3-K-029', 'U3-K-030', 'U3-K-111'],
  'NESTED_STRUCTURE_FUNCTION_CUTAWAY'),
 ('U3-L26',
  'U3-J4',
  'U3-B10',
  'Photosynthesis Redox Board',
  'the overall photosynthesis model with water oxidation separated from carbon-dioxide reduction',
  ['water oxidation and O2 release', 'light reactions / Calvin-cycle linkage', 'CO2 reduction to carbohydrate model'],
  'U3-K-115',
  ['U3-K-113', 'U3-K-114', 'U3-K-115', 'U3-K-116'],
  'REDOX_SYSTEM_MAP'),
 ('U3-L27',
  'U3-J4',
  'U3-B11',
  'Photon and Wavelength Prism',
  'the spectrum wall where wavelength changes are tied to photon energy and pigment absorption',
  ['short-wavelength/high-energy photons', 'visible-spectrum prism', 'long-wavelength/lower-energy photons'],
  'U3-K-117',
  ['U3-K-117', 'U3-K-118', 'U3-K-119'],
  'SPECTRUM_ENERGY_VISUAL'),
 ('U3-L28',
  'U3-J4',
  'U3-B11',
  'Pigment Spectrum Bench',
  'the absorption-spectrum bench comparing chlorophyll a, chlorophyll b, carotenoids, and reflected light',
  ['chlorophyll a/b absorption panels', 'pigment excitation bench', 'carotenoid/protection panel'],
  'U3-K-112',
  ['U3-K-034', 'U3-K-112', 'U3-K-120', 'U3-K-121', 'U3-K-122'],
  'PIGMENT_COMPARISON'),
 ('U3-L29',
  'U3-J4',
  'U3-B11',
  'Photosystem Antenna Theater',
  'the thylakoid-membrane photosystem model with antenna pigments surrounding a reaction center',
  ['light-harvesting pigments', 'reaction-center chlorophyll and acceptor', 'excitation-energy transfer path'],
  'U3-K-123',
  ['U3-K-123', 'U3-K-124', 'U3-K-125', 'U3-K-131'],
  'EXCITATION_TRANSFER_SEQUENCE'),
 ('U3-L30',
  'U3-J4',
  'U3-B12',
  'Photosystem II Water Splitter',
  'the PSII reaction-center station beside the water-oxidation complex',
  ['water-splitting input', 'photosystem II reaction center', 'electron/O2/proton outputs'],
  'U3-K-126',
  ['U3-K-035', 'U3-K-126', 'U3-K-130'],
  'REDOX_REPLACEMENT_SEQUENCE'),
 ('U3-L31',
  'U3-J4',
  'U3-B12',
  'Thylakoid Electron-Transport Bridge',
  'the membrane electron-transfer bridge linking photosystem II to photosystem I while pumping protons',
  ['photosystem II electron departure', 'electron transport/proton-pumping bridge', 'photosystem I arrival'],
  'U3-K-036',
  ['U3-K-032', 'U3-K-036', 'U3-K-037'],
  'MEMBRANE_ETC_GRADIENT_SCENE'),
 ('U3-L32',
  'U3-J4',
  'U3-B12',
  'Photosystem I NADPH Station',
  'the PSI reaction center where arriving electrons are re-excited before NADP+ reduction',
  ['incoming ETC electrons', 'photosystem I / P700 reaction center', 'NADP+ to NADPH output'],
  'U3-K-127',
  ['U3-K-033', 'U3-K-127', 'U3-K-128'],
  'REDOX_OUTPUT_SEQUENCE'),
 ('U3-L33',
  'U3-J4',
  'U3-B12',
  'Photophosphorylation Turbine',
  'the thylakoid ATP synthase spanning lumen and stroma with proton flow driving ATP formation',
  ['high-H+ thylakoid lumen', 'ATP synthase turbine', 'stroma ATP output'],
  'U3-K-038',
  ['U3-K-031', 'U3-K-038', 'U3-K-132'],
  'CHEMIOSMOSIS_TURBINE'),
 ('U3-L34',
  'U3-J5',
  'U3-B13',
  'Calvin Cycle Energy Dock',
  'the stroma carbon-fixation cycle receiving ATP and NADPH from the light reactions',
  ['ATP/NADPH delivery', 'Calvin-cycle route in stroma', 'carbohydrate-building output'],
  'U3-K-039',
  ['U3-K-039', 'U3-K-133'],
  'ENERGY_INPUT_PATHWAY'),
 ('U3-L35',
  'U3-J5',
  'U3-B13',
  'Carbon Fixation Bench',
  'the rubisco station where CO2 is attached to RuBP at the start of carbon fixation',
  ['CO2 input', 'rubisco fixation station', 'RuBP carbon acceptor'],
  'U3-K-134',
  ['U3-K-134', 'U3-K-135', 'U3-K-136'],
  'CARBON_FIXATION_REACTION'),
 ('U3-L36',
  'U3-J5',
  'U3-B13',
  'G3P Output and Regeneration Loop',
  'the three-turn Calvin-cycle accounting loop with one net G3P leaving and RuBP regenerated',
  ['G3P production/output', 'ATP/NADPH accounting loop', 'RuBP regeneration return'],
  'U3-K-137',
  ['U3-K-137', 'U3-K-138'],
  'PATHWAY_ACCOUNTING_MODEL'),
 ('U3-L37',
  'U3-J5',
  'U3-B14',
  'Photorespiration Detour',
  'the rubisco branch point where O2 competes with CO2 and lowers net carbon fixation',
  ['CO2 fixation route', 'rubisco branch point', 'O2/photorespiration detour'],
  'U3-K-140',
  ['U3-K-140', 'U3-K-141'],
  'COMPETING_SUBSTRATE_PATHWAY'),
 ('U3-L38',
  'U3-J5',
  'U3-B14',
  'C4 and CAM Strategy Conservatory',
  'the split greenhouse comparing spatial and temporal CO2-concentration strategies',
  ['C4 spatial separation display', 'photorespiration-pressure reference', 'CAM temporal separation display'],
  'U3-K-142',
  ['U3-K-142', 'U3-K-143'],
  'ADAPTATION_COMPARISON'),
 ('U3-L39',
  'U3-J6',
  'U3-B15',
  'Respiration Fuel Intake',
  'the power-plant intake map connecting macromolecular fuels to the coordinated stages of aerobic respiration',
  ['carbohydrate/fat/protein fuel inputs', 'aerobic respiration stage map', 'CO2/H2O/ATP plus heat outputs'],
  'U3-K-040',
  ['U3-K-040', 'U3-K-042', 'U3-K-145', 'U3-K-146', 'U3-K-147', 'U3-K-150'],
  'SYSTEM_OVERVIEW_MAP'),
 ('U3-L40',
  'U3-J6',
  'U3-B15',
  'Glycolysis Floor',
  'the cytosolic six-carbon-to-two-three-carbon splitting line with ATP investment and payoff stations',
  ['glucose and ATP investment', 'glycolytic splitting line', 'pyruvate/NADH/net ATP outputs'],
  'U3-K-049',
  ['U3-K-049', 'U3-K-151', 'U3-K-152', 'U3-K-153'],
  'PATHWAY_OUTPUT_SEQUENCE'),
 ('U3-L41',
  'U3-J6',
  'U3-B15',
  'Electron Carrier Charging Bay',
  'the redox charging station comparing oxidized NAD+/FAD with reduced NADH/FADH2',
  ['NAD+/NADH carrier pair', 'electron-loading station', 'FAD/FADH2 carrier pair'],
  'U3-K-148',
  ['U3-K-148', 'U3-K-149'],
  'REDOX_CARRIER_COMPARISON'),
 ('U3-L42',
  'U3-J6',
  'U3-B16',
  'Pyruvate Oxidation Airlock',
  'the mitochondrial entry process where pyruvate becomes an acetyl group carried by coenzyme A',
  ['pyruvate entry', 'oxidation/decarboxylation airlock', 'acetyl-CoA/NADH/CO2 outputs'],
  'U3-K-154',
  ['U3-K-050', 'U3-K-154', 'U3-K-155'],
  'PATHWAY_TRANSITION_SEQUENCE'),
 ('U3-L43',
  'U3-J6',
  'U3-B16',
  'Citric Acid Cycle Chamber',
  'the matrix cycle where acetyl groups are oxidized and energy is transferred to ATP, NADH, and FADH2',
  ['acetyl-CoA entry', 'citric acid/Krebs cycle in matrix', 'CO2/ATP/reduced-carrier outputs'],
  'U3-K-051',
  ['U3-K-051', 'U3-K-156', 'U3-K-157'],
  'CYCLIC_PATHWAY_OUTPUT_MODEL'),
 ('U3-L44',
  'U3-J6',
  'U3-B16',
  'Mitochondrial Architecture Bay',
  'the mitochondrial cutaway showing matrix, inner membrane, cristae, and intermembrane space as respiration compartments',
  ['intermembrane space', 'cristae-rich inner membrane', 'matrix'],
  'U3-K-045',
  ['U3-K-045', 'U3-K-144'],
  'STRUCTURE_FUNCTION_CUTAWAY'),
 ('U3-L45',
  'U3-J6',
  'U3-B17',
  'Respiratory Electron-Transport Descent',
  'the inner-membrane redox chain receiving electrons from NADH and FADH2 and transferring them toward a terminal acceptor',
  ['NADH/FADH2 electron entry', 'respiratory ETC redox chain', 'terminal-acceptor end'],
  'U3-K-043',
  ['U3-K-043', 'U3-K-052', 'U3-K-159'],
  'REDOX_CHAIN'),
 ('U3-L46',
  'U3-J6',
  'U3-B17',
  'Proton Pumping Wall',
  'the inner mitochondrial membrane where electron-transfer energy pumps H+ from matrix to intermembrane space',
  ['matrix low-H+ side', 'inner-membrane proton pumps', 'intermembrane high-H+ side'],
  'U3-K-044',
  ['U3-K-044', 'U3-K-053', 'U3-K-160'],
  'GRADIENT_BUILDING_SCENE'),
 ('U3-L47',
  'U3-J6',
  'U3-B17',
  'Oxygen Terminal-Acceptor Basin',
  'the end of the aerobic ETC where oxygen receives electrons and protons to form water',
  ['incoming electrons', 'oxygen terminal-acceptor basin', 'water product'],
  'U3-K-161',
  ['U3-K-161'],
  'TERMINAL_REDOX_REACTION'),
 ('U3-L48',
  'U3-J6',
  'U3-B17',
  'Oxidative-Phosphorylation Turbine',
  'the ATP synthase complex where proton-motive force drives rotation/conformational change and ATP formation',
  ['proton gradient reservoir', 'ATP synthase/chemiosmosis turbine', 'ATP output and yield dashboard'],
  'U3-K-047',
  ['U3-K-047', 'U3-K-158', 'U3-K-162', 'U3-K-163', 'U3-K-164', 'U3-K-165'],
  'CHEMIOSMOSIS_TURBINE'),
 ('U3-L49',
  'U3-J6',
  'U3-B18',
  'Uncoupling Heat Vent',
  'the controlled proton-leak bypass where gradient energy is released as heat instead of captured efficiently as ATP',
  ['proton gradient', 'uncoupling bypass', 'heat output'],
  'U3-K-048',
  ['U3-K-048'],
  'ENERGY_PARTITION_SCENE'),
 ('U3-L50',
  'U3-J6',
  'U3-B18',
  'Prokaryotic Respiratory Membrane',
  'the prokaryotic plasma-membrane model carrying respiratory ETC and proton-translocation machinery without mitochondria',
  ['cytoplasmic side', 'prokaryotic plasma membrane ETC', 'external/periplasmic proton side'],
  'U3-K-046',
  ['U3-K-046'],
  'CROSS_DOMAIN_MEMBRANE_COMPARISON'),
 ('U3-L51',
  'U3-J7',
  'U3-B19',
  'Respiration Across Life Junction',
  'the three-route energy-harvesting junction separating aerobic respiration, anaerobic respiration, and fermentation',
  ['aerobic oxygen-terminal route', 'shared energy-harvesting junction', 'anaerobic/fermentative alternatives'],
  'U3-K-041',
  ['U3-K-041', 'U3-K-167', 'U3-K-168'],
  'PROCESS_COMPARISON'),
 ('U3-L52',
  'U3-J7',
  'U3-B19',
  'Fermentation NAD+ Recycling Gate',
  'the cytosolic redox loop where NADH transfers electrons to an organic molecule so NAD+ returns to glycolysis',
  ['glycolysis NADH output', 'fermentation redox gate', 'regenerated NAD+ return path'],
  'U3-K-054',
  ['U3-K-054', 'U3-K-169', 'U3-K-170'],
  'REDOX_RECYCLING_LOOP'),
 ('U3-L53',
  'U3-J7',
  'U3-B20',
  'Alcohol Fermentation Vat',
  'the two-step pyruvate-to-acetaldehyde-to-ethanol pathway with CO2 release and NAD+ regeneration',
  ['pyruvate decarboxylation', 'acetaldehyde intermediate', 'ethanol plus regenerated NAD+'],
  'U3-K-171',
  ['U3-K-171', 'U3-K-172'],
  'FERMENTATION_SEQUENCE'),
 ('U3-L54',
  'U3-J7',
  'U3-B20',
  'Lactate Fermentation Track',
  'the pyruvate-to-lactate route linked to NAD+ regeneration and downstream lactate transport/use',
  ['pyruvate/NADH input', 'lactate-forming reaction', 'lactate transport and reuse'],
  'U3-K-173',
  ['U3-K-173', 'U3-K-174', 'U3-K-175'],
  'FERMENTATION_SEQUENCE')]
JOURNEYS=[{'journey_id': 'U3-J1',
  'working_title': 'Enzyme Catalysis Workshop',
  'content_focus': 'Catalysts, activation energy, active-site compatibility, induced fit, and enzyme reuse',
  'setting_logic': 'A molecular workshop makes the reaction barrier, docking geometry, and catalytic turnover visible before terminology is attached.',
  'bundles': [{'bundle_id': 'U3-B01', 'title': 'Catalysis and substrate binding', 'loci': ['U3-L01', 'U3-L02', 'U3-L03']}]},
 {'journey_id': 'U3-J2',
  'working_title': 'Enzyme Regulation Control Wing',
  'content_focus': 'Environmental effects, enzyme concentration variables, helpers, inhibition, allostery, cooperativity, and pathway regulation',
  'setting_logic': 'A control wing allows one enzyme system to be stressed, supplied, blocked, activated, and regulated while preserving clear distinctions among mechanisms.',
  'bundles': [{'bundle_id': 'U3-B02', 'title': 'Environmental and concentration effects', 'loci': ['U3-L04', 'U3-L05']},
              {'bundle_id': 'U3-B03', 'title': 'Helpers and inhibitor mechanisms', 'loci': ['U3-L06', 'U3-L07', 'U3-L08', 'U3-L09']},
              {'bundle_id': 'U3-B04', 'title': 'Pathway-level regulation', 'loci': ['U3-L10', 'U3-L11']}]},
 {'journey_id': 'U3-J3',
  'working_title': 'Cellular Energy Exchange Hall',
  'content_focus': 'Metabolism, thermodynamics, free energy, cellular work, ATP structure, coupling, and regeneration',
  'setting_logic': 'An energy-accounting hall keeps forms of energy, thermodynamic constraints, work, and ATP cycling inside one causal system instead of treating them as '
                   'separate definitions.',
  'bundles': [{'bundle_id': 'U3-B05', 'title': 'Metabolism and energy forms', 'loci': ['U3-L12', 'U3-L13']},
              {'bundle_id': 'U3-B06', 'title': 'Thermodynamic constraints', 'loci': ['U3-L14', 'U3-L15', 'U3-L16']},
              {'bundle_id': 'U3-B07', 'title': 'Cellular work and ATP coupling', 'loci': ['U3-L17', 'U3-L18', 'U3-L19', 'U3-L20']},
              {'bundle_id': 'U3-B08', 'title': 'Evolutionary conservation of metabolism', 'loci': ['U3-L21']}]},
 {'journey_id': 'U3-J4',
  'working_title': 'Light Capture Conservatory',
  'content_focus': 'Photosynthetic origins, chloroplast geography, light, pigments, photosystems, electron transport, proton gradients, and photophosphorylation',
  'setting_logic': 'A light-processing conservatory follows energy from incoming photons through pigments, photosystems, electron transfer, proton-gradient formation, ATP, and '
                   'NADPH.',
  'bundles': [{'bundle_id': 'U3-B09', 'title': 'Photosynthetic context and origins', 'loci': ['U3-L22', 'U3-L23']},
              {'bundle_id': 'U3-B10', 'title': 'Leaf and chloroplast organization', 'loci': ['U3-L24', 'U3-L25', 'U3-L26']},
              {'bundle_id': 'U3-B11', 'title': 'Light and photosystem capture', 'loci': ['U3-L27', 'U3-L28', 'U3-L29']},
              {'bundle_id': 'U3-B12', 'title': 'Linear electron flow and energy products', 'loci': ['U3-L30', 'U3-L31', 'U3-L32', 'U3-L33']}]},
 {'journey_id': 'U3-J5',
  'working_title': 'Carbon Fixation Greenhouse',
  'content_focus': 'Calvin cycle, carbon fixation, Rubisco, RuBP, G3P, photorespiration, C4, and CAM',
  'setting_logic': 'A carbon greenhouse turns ATP and NADPH into visible carbon-flow work, then tests how plants reduce photorespiration under different environmental '
                   'constraints.',
  'bundles': [{'bundle_id': 'U3-B13', 'title': 'Calvin-cycle carbon flow', 'loci': ['U3-L34', 'U3-L35', 'U3-L36']},
              {'bundle_id': 'U3-B14', 'title': 'Photorespiration and carbon-concentration strategies', 'loci': ['U3-L37', 'U3-L38']}]},
 {'journey_id': 'U3-J6',
  'working_title': 'Respiration Power Plant',
  'content_focus': 'Aerobic respiration from fuel intake through glycolysis, mitochondrial oxidation, electron transport, proton gradients, ATP synthase, heat, and prokaryotic '
                   'respiration',
  'setting_logic': 'A power plant follows carbon and electrons through successive energy-harvesting stages while keeping mitochondrial compartments and chemiosmosis spatially '
                   'explicit.',
  'bundles': [{'bundle_id': 'U3-B15', 'title': 'Fuel entry and glycolysis', 'loci': ['U3-L39', 'U3-L40', 'U3-L41']},
              {'bundle_id': 'U3-B16', 'title': 'Mitochondrial carbon oxidation', 'loci': ['U3-L42', 'U3-L43', 'U3-L44']},
              {'bundle_id': 'U3-B17', 'title': 'Electron transport and oxidative phosphorylation', 'loci': ['U3-L45', 'U3-L46', 'U3-L47', 'U3-L48']},
              {'bundle_id': 'U3-B18', 'title': 'Heat and cross-domain respiration', 'loci': ['U3-L49', 'U3-L50']}]},
 {'journey_id': 'U3-J7',
  'working_title': 'Alternative Energy Annex',
  'content_focus': 'Aerobic versus anaerobic respiration, fermentation, NAD+ recycling, alcohol fermentation, and lactate metabolism',
  'setting_logic': 'A branching annex compares alternative routes from shared metabolic constraints so anaerobic respiration and fermentation cannot collapse into the same idea.',
  'bundles': [{'bundle_id': 'U3-B19', 'title': 'Alternative electron and redox routes', 'loci': ['U3-L51', 'U3-L52']},
              {'bundle_id': 'U3-B20', 'title': 'Fermentation products and physiological context', 'loci': ['U3-L53', 'U3-L54']}]}]
PRACTICE=[{'challenge_id': 'U3-CH-01', 'knowledge_id': 'U3-K-176', 'title': 'Fever and enzyme function', 'type': 'MECHANISM_FRQ', 'prerequisite_loci': ['U3-L04']},
 {'challenge_id': 'U3-CH-02', 'knowledge_id': 'U3-K-177', 'title': 'Vitamin cofactor reasoning', 'type': 'MECHANISM_FRQ', 'prerequisite_loci': ['U3-L06']},
 {'challenge_id': 'U3-CH-03', 'knowledge_id': 'U3-K-178', 'title': 'Peroxidase pH data', 'type': 'DATA_INTERPRETATION', 'prerequisite_loci': ['U3-L04', 'U3-L05']},
 {'challenge_id': 'U3-CH-04',
  'knowledge_id': 'U3-K-179',
  'title': 'Penicillin transpeptidase inhibition',
  'type': 'MECHANISM_EVALUATION',
  'prerequisite_loci': ['U3-L07', 'U3-L11']},
 {'challenge_id': 'U3-CH-05', 'knowledge_id': 'U3-K-180', 'title': 'Enzyme saturation graph', 'type': 'GRAPH_INTERPRETATION', 'prerequisite_loci': ['U3-L05']},
 {'challenge_id': 'U3-CH-06', 'knowledge_id': 'U3-K-181', 'title': 'Light-wavelength plant growth', 'type': 'DATA_FRQ', 'prerequisite_loci': ['U3-L27', 'U3-L28']},
 {'challenge_id': 'U3-CH-07', 'knowledge_id': 'U3-K-182', 'title': 'Photorespiration evidence', 'type': 'EVIDENCE_FRQ', 'prerequisite_loci': ['U3-L37', 'U3-L38']},
 {'challenge_id': 'U3-CH-08',
  'knowledge_id': 'U3-K-183',
  'title': 'Bentazon photosystem-II disruption',
  'type': 'MECHANISM_FRQ',
  'prerequisite_loci': ['U3-L30', 'U3-L31', 'U3-L32', 'U3-L33']},
 {'challenge_id': 'U3-CH-09', 'knowledge_id': 'U3-K-184', 'title': 'Yeast sugar fermentation data', 'type': 'DATA_INTERPRETATION', 'prerequisite_loci': ['U3-L52', 'U3-L53']},
 {'challenge_id': 'U3-CH-10',
  'knowledge_id': 'U3-K-185',
  'title': 'Fish oxygen deprivation',
  'type': 'MECHANISM_FRQ',
  'prerequisite_loci': ['U3-L45', 'U3-L47', 'U3-L48', 'U3-L52']},
 {'challenge_id': 'U3-CH-11', 'knowledge_id': 'U3-K-186', 'title': 'Mitochondrial pH gradient', 'type': 'MODEL_FRQ', 'prerequisite_loci': ['U3-L46', 'U3-L48']}]
CONFUSABLES=[('U3-CF-01',
  'Catalysis vocabulary',
  ['activation energy', 'enzyme', 'substrate', 'active site', 'enzyme-substrate complex'],
  ['U3-K-083', 'U3-K-002', 'U3-K-084', 'U3-K-085', 'U3-K-005']),
 ('U3-CF-02', 'Active-site models', ['active-site compatibility', 'induced fit'], ['U3-K-004', 'U3-K-086']),
 ('U3-CF-03', 'Enzyme disruption mechanisms', ['denaturation', 'reversible denaturation', 'irreversible inhibition'], ['U3-K-007', 'U3-K-009', 'U3-K-096']),
 ('U3-CF-04', 'Inhibition mechanisms', ['competitive inhibition', 'noncompetitive inhibition', 'irreversible inhibition'], ['U3-K-012', 'U3-K-013', 'U3-K-096']),
 ('U3-CF-05', 'Enzyme helpers', ['cofactor', 'coenzyme', 'holoenzyme'], ['U3-K-093', 'U3-K-094', 'U3-K-095']),
 ('U3-CF-06', 'Allosteric control', ['allosteric site', 'allosteric activator', 'allosteric inhibitor'], ['U3-K-098', 'U3-K-100', 'U3-K-101']),
 ('U3-CF-07', 'Pathway regulation', ['cooperativity', 'feedback inhibition', 'allosteric regulation'], ['U3-K-102', 'U3-K-103', 'U3-K-099']),
 ('U3-CF-08', 'Metabolic direction', ['catabolic pathway', 'anabolic pathway'], ['U3-K-057', 'U3-K-058']),
 ('U3-CF-09', 'Energy forms', ['kinetic energy', 'thermal energy', 'potential energy', 'chemical energy'], ['U3-K-060', 'U3-K-061', 'U3-K-062', 'U3-K-063']),
 ('U3-CF-10', 'Thermodynamic laws', ['first law of thermodynamics', 'second law of thermodynamics'], ['U3-K-065', 'U3-K-066']),
 ('U3-CF-11', 'Reaction energetics', ['exergonic reaction', 'endergonic reaction'], ['U3-K-070', 'U3-K-071']),
 ('U3-CF-12', 'Cellular work', ['mechanical work', 'transport work', 'chemical work'], ['U3-K-073', 'U3-K-074', 'U3-K-075']),
 ('U3-CF-13', 'ATP coupling', ['ATP hydrolysis', 'phosphorylation', 'ATP regeneration'], ['U3-K-078', 'U3-K-081', 'U3-K-082']),
 ('U3-CF-14', 'Carbon acquisition', ['autotroph', 'photoautotroph', 'heterotroph'], ['U3-K-105', 'U3-K-106', 'U3-K-107']),
 ('U3-CF-15', 'Chloroplast locations', ['stroma', 'thylakoid membrane', 'granum'], ['U3-K-028', 'U3-K-029', 'U3-K-030']),
 ('U3-CF-16', 'Photosynthetic pigments', ['chlorophyll a', 'chlorophyll b', 'carotenoids'], ['U3-K-120', 'U3-K-121', 'U3-K-122']),
 ('U3-CF-17', 'Photosystem components', ['photosystem', 'light-harvesting complex', 'reaction center'], ['U3-K-123', 'U3-K-125', 'U3-K-124']),
 ('U3-CF-18', 'Photosystems', ['photosystem II', 'photosystem I'], ['U3-K-126', 'U3-K-127']),
 ('U3-CF-19', 'Light-reaction energy products', ['ATP', 'NADPH'], ['U3-K-031', 'U3-K-033']),
 ('U3-CF-20', 'Photosynthetic phases', ['light reactions', 'Calvin cycle'], ['U3-K-116', 'U3-K-133']),
 ('U3-CF-21', 'Calvin-cycle roles', ['rubisco', 'RuBP', 'G3P'], ['U3-K-135', 'U3-K-136', 'U3-K-137']),
 ('U3-CF-22', 'Carbon-conservation strategies', ['photorespiration', 'C4 photosynthesis', 'CAM photosynthesis'], ['U3-K-140', 'U3-K-142', 'U3-K-143']),
 ('U3-CF-23', 'Respiratory electron carriers', ['NAD+ / NADH', 'FAD / FADH2'], ['U3-K-148', 'U3-K-149']),
 ('U3-CF-24', 'Phosphorylation mechanisms', ['substrate-level phosphorylation', 'oxidative phosphorylation', 'photophosphorylation'], ['U3-K-153', 'U3-K-047', 'U3-K-038']),
 ('U3-CF-25', 'Respiration stages', ['glycolysis', 'pyruvate oxidation', 'citric acid cycle', 'oxidative phosphorylation'], ['U3-K-151', 'U3-K-154', 'U3-K-156', 'U3-K-158']),
 ('U3-CF-26', 'Respiratory gradient locations', ['mitochondrial matrix', 'intermembrane space'], ['U3-K-144', 'U3-K-044']),
 ('U3-CF-27', 'Energy-harvesting alternatives', ['aerobic respiration', 'anaerobic respiration', 'fermentation'], ['U3-K-042', 'U3-K-167', 'U3-K-169']),
 ('U3-CF-28', 'Fermentation products', ['alcohol fermentation', 'lactate fermentation'], ['U3-K-171', 'U3-K-173'])]
SCOPE_IDS={'U3-K-069','U3-K-129','U3-K-139','U3-K-166'}

def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def dump(p,obj): Path(p).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+"\n",encoding='utf-8')
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

src=load(SRC)
records={r['knowledge_id']:r for r in src['canonical_catalog']}
loci=[]
for lid,jid,bid,title,anchor,zones,primary,kids,visual in RAW_LOCI:
    loci.append({
      'locus_id':lid,'journey_id':jid,'bundle_id':bid,'title':title,'micro_anchor':anchor,
      'scene_geometry':{'left':zones[0],'center':zones[1],'right':zones[2]},
      'primary_knowledge_id':primary,'knowledge_ids':kids,'embedded_knowledge_ids':[k for k in kids if k!=primary],
      'visual_mode':visual,'scientific_visual_required':True,'narrative_status':'ARCHITECTURE_ONLY_NO_STORY_PROSE_F2'
    })

loc_for={kid:l['locus_id'] for l in loci for kid in l['knowledge_ids']}
primary_set={l['primary_knowledge_id'] for l in loci}
practice_ids={x['knowledge_id'] for x in PRACTICE}
technical_pat=re.compile(r'(phosph|thermo|alloster|cooper|holoenzyme|coenzyme|cofactor|photosystem|chlorophyll|carotenoid|thylakoid|photophosph|rubisco|ribulose|glyceraldehyde|photoresp|chemiosm|oxidative|acetyl|glycolysis|pyruvate|citric|krebs|ferment|lactate|acetaldehyde|mitochond|NAD|FAD)',re.I)
classification=[]
for kid in sorted(records, key=lambda x:int(x.split('-')[-1])):
    r=records[kid]
    if kid in practice_ids:
        dest='CHALLENGE_LAB'; locus=None; role='APPLIED_TRANSFER'; visual='APPLICATION_PROMPT'; retrieval=['APPLIED_TRANSFER']
    elif kid in SCOPE_IDS:
        dest='SUPPORTING_NON_RUNTIME_SCOPE_GUARD'; locus=None; role='SCOPE_BOUNDARY'; visual='SCOPE_GUARD'; retrieval=['SCOPE_BOUNDARY_RECOGNITION']
    else:
        locus=loc_for[kid]
        dest='PALACE_PRIMARY_LOCUS' if kid in primary_set else 'PALACE_EMBEDDED'
        role='PRIMARY_ANCHOR' if kid in primary_set else 'EMBEDDED_SCIENCE'
        visual=next(l['visual_mode'] for l in loci if l['locus_id']==locus)
        retrieval=[]
        if r['exact_name_recall']: retrieval.append('EXACT_NAME_FROM_SCIENTIFIC_ROLE')
        retrieval.append('MEANING_OR_MECHANISM')
        if kid in {'U3-K-113','U3-K-138','U3-K-145','U3-K-152','U3-K-157','U3-K-161','U3-K-165'}:
            retrieval.append('MODEL_OR_STOICHIOMETRY_INTERPRETATION')
    if not r['exact_name_recall']:
        ns='NO_EXACT_NAME_GATE'
    elif technical_pat.search(r['canonical_label']) or len(r['canonical_label'].split())>=4:
        ns='SEMANTIC_PLUS_OPTIONAL_SOUND_CUE'
    else:
        ns='SEMANTIC_SCIENCE_CUE_SUFFICIENT'
    classification.append({
      'knowledge_id':kid,'canonical_label':r['canonical_label'],'topic':r['topic'],'scope_class':r['scope_class'],
      'destination':dest,'locus_id':locus,'scene_role':role,'visual_mode':visual,'exact_name_recall':r['exact_name_recall'],
      'name_support':ns,'spelling_policy':'ADAPTIVE_SUPPORT_ONLY_NO_MANDATORY_SPELLING_GATE',
      'retrieval_modes':retrieval,'canonical_lock':r['canonical_lock'],'review_flag_id':r.get('review_flag_id')
    })

confdocs=[{'set_id':sid,'title':title,'terms':terms,'knowledge_ids':kids} for sid,title,terms,kids in CONFUSABLES]
architecture={
 'schema':'memory-palace-v2-unit3-f2-architecture-1.0','generated_utc':GENERATED_UTC,
 'unit':{'unit_id':'unit-3','title':'Cellular Energetics','canonical_source_lock':'F1','student_release':False,'narrative_generation_allowed':False},
 'design_rules':{
   'student_simplicity':'The learner will eventually see guided journeys, Review, and Challenge Lab; F2 classification machinery remains hidden.',
   'locus_rule':'A permanent locus represents one coherent causal, spatial, or comparison model rather than one canonical record.',
   'embedded_rule':'Related definitions, mechanism details, and teacher enrichment are embedded in the locus whose scientific action makes them intelligible.',
   'practice_rule':'Applied-transfer records remain in Challenge Lab and do not consume permanent palace locations.',
   'scope_guard_rule':'Scope guards protect AP boundaries and remain non-runtime support metadata unless a later audit needs to surface them.',
   'process_rule':'Photosynthesis and respiration must preserve scientifically recognizable membrane, compartment, redox, gradient, and pathway geometry.',
   'narrative_gate':'No polished Unit 3 story prose may be authored until F3 scene briefs pass QA.',
   'spelling_rule':'No mandatory spelling gate. Exact-name support is adaptive and can use optional sound cues only when useful.'
 },
 'counts':{'canonical_records':len(records),'palace_managed_records':len(loc_for),'scope_guard_records':len(SCOPE_IDS),'practice_only_records':len(PRACTICE),
           'journeys':len(JOURNEYS),'bundles':sum(len(j['bundles']) for j in JOURNEYS),'permanent_loci':len(loci),'confusable_sets':len(confdocs)},
 'journeys':JOURNEYS,'loci':loci,'challenge_lab':PRACTICE,'confusable_sets':confdocs,
 'scope_guards':[{'knowledge_id':k,'canonical_label':records[k]['canonical_label'],'policy':'NON_RUNTIME_AP_SCOPE_BOUNDARY'} for k in sorted(SCOPE_IDS)]
}
classdoc={
 'schema':'memory-palace-v2-unit3-f2-classification-1.0','generated_utc':GENERATED_UTC,'unit_id':'unit-3','canonical_source_lock':'F1','counts':{},'records':classification
}
classdoc['counts']={
 'total':len(classification),'by_destination':dict(Counter(x['destination'] for x in classification)),
 'by_name_support':dict(Counter(x['name_support'] for x in classification)),
 'exact_name_targets':sum(bool(x['exact_name_recall']) and x['destination'].startswith('PALACE') for x in classification),
 'mandatory_spelling_targets':0
}
dump(ARCH/'learning-classification-f2.json',classdoc)
dump(ARCH/'palace-architecture-f2.json',architecture)

status={
 'unit_id':'unit-3','unit_number':3,'title':'Cellular Energetics','status':'LEARNING_ARCHITECTURE_LOCKED_F2_NOT_STUDENT_RELEASED',
 'pipeline_status':'LEARNING_CLASSIFICATION_AND_PALACE_ARCHITECTURE_COMPLETE','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2',
 'student_release':False,'preview_release':False,'canonical_records':186,'review_flags_resolved':30,'ced_topics':5,'ced_atoms':54,
 'journey_count':0,'scene_count':0,'memory_objects':0,'architecture_journeys':7,'architecture_bundles':20,'architecture_loci':54,
 'palace_managed_records':171,'scope_guard_records':4,'practice_only_records':11,'confusable_sets':28,
 'next_required_output':'F3 scene briefs for all 54 loci; no polished Unit 3 narrative prose before F3 brief QA'
}
dump(U3/'status-f2.json',status)
dump(U3/'status.json',status)
course=load(ROOT/'content'/'ap-biology'/'course.json')
for u in course['units']:
    if u['unit_id']=='unit-3':
        u.update({'status':status['status'],'journey_count':0,'scene_count':0,'canonical_lock':'LOCKED_F1','canonical_records':186,'review_flags_resolved':30,
                  'architecture_journeys':7,'architecture_loci':54,'architecture_lock':'LOCKED_F2','student_release':False,
                  'source_status':'AUDITED_SCIENCE_LOCKED_F1_AND_ARCHITECTURE_LOCKED_F2'})
dump(ROOT/'content'/'ap-biology'/'course.json',course)
manifest={
 'schema':'memory-palace-v2-unit3-f2-release-1.0','generated_utc':GENERATED_UTC,'unit_id':'unit-3','release':'F2_LEARNING_ARCHITECTURE_LOCK',
 'student_release':False,'canonical_records':186,'palace_managed_records':171,'scope_guard_records':4,'challenge_lab_records':11,
 'journey_blueprints':7,'bundle_blueprints':20,'permanent_locus_blueprints':54,'confusable_sets':28,
 'narrative_story_files':0,'student_runtime_memory_objects':0,
 'gate':'F2 fixes Unit 3 learning destinations and spatial architecture. F3 may specify science-bearing scene actions; polished story prose remains gated until F3 brief QA.'
}
dump(U3/'f2-release-manifest.json',manifest)
locked=[
 'content/ap-biology/unit-3/source/canonical-unit3-f1.json',
 'content/ap-biology/unit-3/source/coverage-manifest-f1.json',
 'content/ap-biology/unit-3/architecture/learning-classification-f2.json',
 'content/ap-biology/unit-3/architecture/palace-architecture-f2.json',
 'content/ap-biology/unit-3/status-f2.json',
 'content/ap-biology/unit-3/f2-release-manifest.json',
 'content/ap-biology/unit-3/audit/APBIO_Unit3_F2_Classification.xlsx',
]
lock={'schema':'memory-palace-v2-unit3-f2-lock-1.0','lock_status':'LOCKED_F2','student_release':False,'files':{}}
for rel in locked:
    p=ROOT/rel
    lock['files'][rel]={'sha256':sha(p),'bytes':p.stat().st_size}
dump(U3/'content-lock-f2.json',lock)
print('built Unit 3 F2',architecture['counts'],classdoc['counts'])
