from __future__ import annotations
import json, hashlib, re, subprocess, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
U5=ROOT/'content'/'ap-biology'/'unit-5'
subprocess.run([sys.executable,str(ROOT/'scripts'/'build_unit5_f4f.py')],check=True,stdout=subprocess.DEVNULL)
F3=json.loads((U5/'briefs'/'scene-briefs-f3.json').read_text(encoding='utf-8'))['scene_briefs']
JBRIEFS=json.loads((U5/'briefs'/'journey-briefs-f3.json').read_text(encoding='utf-8'))['journeys']
J7BRIEF=next(j for j in JBRIEFS if j['journey_id']=='U5-J7')
B={b['locus_id']:b for b in F3 if b['journey_id']=='U5-J7'}
CANON={r['knowledge_id']:r for r in json.loads((U5/'source'/'canonical-unit5-f1.json').read_text(encoding='utf-8'))['canonical_catalog']}
PREV=[json.loads((U5/'journeys'/f'U5-J{i}.json').read_text(encoding='utf-8')) for i in range(1,7)]

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

GUIDE={
 'name':'Dr. Imani Reyes','role':'inheritance-systems geneticist',
 'visual':'deep-green field coat, clear gloves, compact chromosome tablet preserving the blue and amber parental-origin chromosome identities, and the narrow gold generation ledger',
 'story_job':'Imani keeps one two-locus chromosome railcar visible from linkage through crossover, class sorting, recombination-frequency measurement, map construction, and the 50-percent ceiling.'
}
RAILCAR={
 'name':'Two-locus chromosome railcar','kind':'continuity scientific model',
 'visual':'a long blue chromosome railcar carrying two brass locus plates, A and B, with the homologous amber railcar beside it and allele tags fixed at corresponding loci',
 'job':'keeps chromosome identity, locus order, and parental allele arrangement stable while crossing over changes only the chromatid segments and allele combinations actually exchanged.'
}
METER={
 'name':'Recombination meter','kind':'continuity quantitative instrument',
 'visual':'a large mechanical percentage dial connected to parental and recombinant sorting bins, with a hard stop at fifty percent and a separate map-distance scale that activates only for interpretation',
 'job':'separates observed recombinant proportion from genetic-map interpretation and prevents the percentage from being read as literal physical DNA length.'
}
LEDGER={
 'name':'Gold mapping ledger','kind':'continuity record',
 'visual':'the same narrow gold ledger, now ruled for parental arrangement, recombinant classes, total count, recombination frequency, inferred gene order, map units, and model limits',
 'job':'forces each conclusion to retain the evidence and assumptions that support it.'
}

ZONE_COPY={
'U5-L38':[
 ('left','Nearby-loci loading siding','close loci','Two locus plates sit close together on the same chromosome railcar, with the parental allele arrangement locked visibly above them.'),
 ('center','Same-chromosome linkage platform','co-transmission','The blue and amber homolog railcars travel in parallel while the two tracked loci remain on the same chromosome and are usually carried together unless a crossover falls between them.'),
 ('right','Distant-loci comparison siding','more crossover opportunity','A second display moves two loci farther apart on the same chromosome so the longer interval offers more opportunity for a crossover to occur between them.')],
'U5-L39':[
 ('left','Parental arrangement dock','starting arrangement','The original allele combinations remain fixed on blue and amber homologous chromosomes before any exchange occurs.'),
 ('center','Nonsister crossover switch','exchange between loci','A crossover switch connects nonsister chromatids at a position between the tracked loci and swaps corresponding chromosome segments.'),
 ('right','Recombinant output track','new combinations','Altered chromatids roll out with new allele combinations while unaffected chromatids retain the original parental arrangements.')],
'U5-L40':[
 ('left','Parental-type bins','matches parents','Classes that match the original tracked parental allele combinations are sorted into blue bins.'),
 ('center','Evidence classification turntable','classify before calculating','Each offspring or gamete class is compared with the known original parental arrangement before any percentage is calculated.'),
 ('right','Recombinant-type bins','new combinations','Classes carrying new tracked allele combinations are sorted into amber bins as recombinant types.')],
'U5-L41':[
 ('left','Recombinant count hopper','recombinants over total','The counted recombinant classes enter one hopper while the total number of scored outcomes remains visible on a separate counter.'),
 ('center','Recombination-frequency dial','percentage','The meter divides recombinant outcomes by total outcomes and expresses the result as a percentage.'),
 ('right','Linkage interpretation panel','relative genetic separation','The percentage is interpreted as evidence about relative genetic linkage and separation, with a warning that it is not direct base-pair distance.')],
'U5-L42':[
 ('left','Pairwise frequency markers','evidence marks','Observed pairwise recombination frequencies hang as movable brass markers that can be placed between candidate locus positions.'),
 ('center','Gene-order map board','relative order','The loci are arranged in an order that is consistent with the set of observed genetic distances.'),
 ('right','Centimorgan ruler','genetic map units','A ruler marked in centimorgans converts short-interval recombination values into approximate genetic-map distances while keeping physical DNA length off the scale.')],
'U5-L43':[
 ('left','Increasing-separation track','farther apart','The tracked loci slide farther apart while crossover opportunities accumulate and multiple crossovers become increasingly possible.'),
 ('center','Fifty-percent ceiling gate','observable ceiling','The recombination meter rises toward fifty percent and then cannot provide a larger distinguishable two-locus recombinant fraction.'),
 ('right','Indistinguishable-outcome platform','two explanations remain','Two tracks remain open, one for genes on different chromosomes and one for very distant loci on the same chromosome, because ordinary two-locus data near fifty percent cannot distinguish them by recombination frequency alone.')]
}

STORY={
'U5-L38':{
 'title':'The Platform Where Linked Had Been Mistaken for Locked',
 'kicker':'Genetic linkage reflects genes occupying the same chromosome, often close enough to be inherited together more frequently, while crossing over can still separate their alleles.',
 'paragraphs':[
 "The doors of the **Chromosome Mapping Rail Yard** open onto a long station built around one enormous chromosome-shaped railcar. On your **left**, two brass locus plates marked A and B sit close together on the same blue railcar, with matching positions on an amber homolog beside it. Directly **ahead**, both homolog railcars rest on a shared loading platform where their allele tags can be followed from one end to the other. On your **right**, a comparison railcar carries another pair of loci much farther apart. Dr. Imani Reyes sets the **gold mapping ledger** on a waist-high stand and locks the **two-locus chromosome railcar** into place. Above the center track, a dark **recombination meter** waits at zero. Imani tells you that this journey will never replace the chromosome with a fresh diagram. The same tracked loci must survive every calculation that follows.",
 "Imani taps the two nearby locus plates on the left railcar. They are physically on the same chromosome. She names the relationship **Genetic linkage**. Genetic linkage describes genes located on the same chromosome that tend to be inherited together, especially when the loci are close enough that crossing over between them is relatively uncommon. She writes the original allele arrangement in the ledger and clips the same arrangement above the railcar. The definition is now attached to a physical reason. The loci travel together because they occupy one chromosome segment that can pass through meiosis as a connected structure.",
 "The center platform begins moving the homologs through a transparent model of meiosis. The two tracked allele tags remain together on a chromatid when no crossover occurs between their loci. Imani labels this relationship **Linked genes tend to be inherited together**. The word tend is printed in large letters on the platform. A mechanic tries to replace it with always, and the railcar immediately triggers a warning bell. Imani removes the false sign. Genes on the same chromosome can be separated by recombination when a crossover occurs at a position between their loci. Linkage changes the probability of allele combinations. It does not weld alleles together permanently.",
 "She then rolls the right comparison railcar closer. Its two loci are still on the same chromosome, yet they are separated by a much longer interval. The track between them contains many possible crossover positions. The nearby pair on the left has a shorter interval with fewer opportunities for a crossover to land between the tracked loci. Imani does not claim that chromosome distance determines an exact crossover count in every meiosis. She uses the comparison to establish the mapping logic. Relative position affects the chance that crossing over will separate the two tracked alleles, and that chance can be estimated from many scored meiotic products or offspring.",
 "The gold ledger now shows two columns. The first says same chromosome. The second says recombination can still occur. Imani asks you to read them together. A gene pair can be linked and still produce recombinant outcomes. A pair can also be so far apart on the same chromosome that ordinary two-locus data eventually make them behave as though they assort independently. The yard therefore cannot use linked as a simple yes or no label detached from recombination evidence. It needs the chromosome location, the original allele arrangement, and the observed outcome classes.",
 "A small switch house ahead lights up between the A and B plates. Imani keeps the nearby pair loaded on the blue and amber homologs and pushes both railcars forward. The next room will force a crossover to occur at a known position between the loci. Because the parental arrangement has been preserved here, you will be able to tell exactly what changed and exactly which chromatids become recombinant."
 ],
 'close':'The loading platform now defines linkage through same-chromosome position and co-transmission without turning linked into permanently inseparable. The railcar enters the crossover switch with its parental arrangement still visible.'
},
'U5-L39':{
 'title':'The Switch Where a Crossover Rebuilt the Allele Combination',
 'kicker':'Crossing over between nonsister chromatids can create genetic recombination when the exchange occurs between linked loci.',
 'paragraphs':[
 "The railcars enter the **Recombination Switch**, a narrow chamber with three fixed tracks. On your **left**, the blue and amber homologs hold the original parental allele arrangements exactly as they left the previous platform. Directly **ahead**, a mechanical crossover bridge can join two nonsister chromatids at a chosen position between loci A and B. On your **right**, four chromatid lanes wait to receive the products. Dr. Imani Reyes checks the **gold mapping ledger** before touching the switch. The parental arrangement is the reference state. Without that reference, the word recombinant would have nothing to compare against.",
 "Imani duplicates the homologs in the model so each chromosome consists of sister chromatids, then pairs the homologous chromosomes as they would be during prophase I. She highlights one blue chromatid and one amber chromatid. They are nonsister chromatids because they belong to homologous chromosomes, not to the same replicated chromosome. The crossover bridge closes at a point between the two tracked loci. Corresponding DNA segments are exchanged. The loci themselves remain the same loci in the same chromosomal order. What changes is which parental-origin segment and allele combination now occupies part of each participating chromatid.",
 "As the bridge opens, Imani names **Genetic recombination**. Genetic recombination can create new combinations of alleles relative to the parental chromosome arrangements. In this chamber, the causal event is crossing over between nonsister chromatids. The exchange lands between A and B, so the two tracked alleles can be separated from the combinations that entered the room. Imani leaves the two chromatids that did not participate in the crossover untouched. They preserve parental arrangements and provide a visual comparison with the altered chromatids.",
 "She then states the relationship that the switch was built to teach. **Crossing over can separate linked alleles** when the crossover occurs between the loci. A crossover somewhere else on the chromosome might not change the tracked A and B combination. The yard therefore does not count every crossover as a recombinant event for every pair of loci. The location of the exchange relative to the tracked loci matters. The two-locus railcar makes that geometry visible because you can point to the A plate, the crossover position, and the B plate on one continuous chromosome.",
 "The right-side lanes receive four chromatid products. Two retain the original parental combinations. Two carry new combinations produced by the exchange. Imani does not call all four products recombinant simply because crossing over happened in the cell. She classifies the tracked allele arrangement on each chromatid. This keeps recombination tied to the specific loci being studied. It also prepares the next room, where offspring or gamete classes must be sorted against the known parental reference before any percentages are calculated.",
 "A small recall lamp illuminates above the crossover bridge. If you choose to answer, Imani asks, **What event can create recombinant chromatids for linked loci?** The answer is **Crossing over between nonsister chromatids at a position between the loci.** After the lamp dims, the railcar products roll toward the sorting yard. The original parental arrangement remains clipped to the ledger, so the next classification will be based on evidence and not on which bins happen to contain the largest counts."
 ],
 'close':'The crossover switch has created new tracked allele combinations while preserving the parental reference. The next yard classifies parental and recombinant types before any frequency is calculated.'
},
'U5-L40':{
 'title':'The Sorting Yard Where the Largest Bin Could Not Name Itself',
 'kicker':'Parental and recombinant types are defined by whether tracked allele combinations match or differ from the original parental arrangements, not by bin size alone.',
 'paragraphs':[
 "The chromatid lanes empty into the **Parental–Recombinant Sorting Yard**. On your **left**, blue bins are labeled with the original parental allele combinations recorded before crossing over. Directly **ahead**, a circular classification turntable receives scored gamete or offspring classes one at a time. On your **right**, amber bins wait for combinations that differ from the original parental reference. Dr. Imani Reyes places the **gold mapping ledger** beside the turntable and locks the parental arrangement page open. The **two-locus chromosome railcar** remains visible through a glass wall behind you, so the categories cannot drift away from the chromosomes that produced them.",
 "The first class arrives with the same tracked combination that appeared on one parental homolog. Imani sends it left and names **Parental type**. A parental type matches one of the original tracked parental allele or phenotype combinations used as the reference for the cross. A second matching class follows it. The important feature is identity with the parental arrangement. The category is not defined by being common, large, or expected to dominate the dataset. Those patterns may occur in many linkage experiments, yet they are consequences that depend on the cross and recombination rate.",
 "A new class arrives carrying an A allele with the B-associated partner that originally belonged on the other homolog. Imani sends it right and names **Recombinant type**. A recombinant type contains a new combination of the tracked alleles or phenotypes relative to the parental classes. The sorter compares the class with the original arrangement before deciding where it belongs. The classification therefore depends on the known parental phase. Without the starting arrangement, a label such as recombinant cannot be assigned just from the absolute size of a group.",
 "The yard supervisor tries a shortcut. He points to the two largest bins and declares them parental. Imani stops the turntable. In many classic testcross linkage datasets, parental classes are indeed larger than recombinant classes because linked loci recombine less than half the time. That pattern can help identify the likely parental classes when the experimental design supports it. It is still not the definition. The yard must preserve the actual parental genotypes or allele arrangements and use them as the reference. Imani writes this distinction in the ledger before allowing the sorter to restart.",
 "Every class is now frozen in its correct bin. Imani counts the recombinant bins but does not yet divide by anything. The center turntable has completed one conceptual task. It has classified outcome identity. The next instrument will perform a separate quantitative task and calculate the fraction of all scored outcomes that are recombinant. Keeping those steps separate prevents a student from seeing a percentage and forgetting what observations entered its numerator.",
 "The bins lock shut and roll onto a conveyor. Blue parental bins stay on one side. Amber recombinant bins stay on the other. A large dial becomes visible through the next doorway, but its pointer is still blank. Imani carries the ledger forward with the recombinant count and total count written on separate lines. The next room can now calculate a meaningful recombination frequency because the biological categories were established first."
 ],
 'close':'The sorting yard now defines parental and recombinant types from the original arrangement before arithmetic begins. The counted recombinant classes move into the recombination-frequency meter.'
},
'U5-L41':{
 'title':'The Meter Where a Percentage Was Forbidden to Become a Ruler',
 'kicker':'Recombination frequency is the proportion of scored outcomes that are recombinant and provides evidence about relative genetic linkage, not a direct measurement of physical DNA length.',
 'paragraphs':[
 "The conveyor reaches the **Recombination Frequency Meter**. On your **left**, the amber recombinant bins empty into a count hopper while a second counter displays the total number of scored gametes or offspring. Directly **ahead**, a wide percentage dial connects the recombinant count to the total count. On your **right**, an interpretation panel shows two linked loci that can move closer together or farther apart on a genetic map. Dr. Imani Reyes clips the **gold mapping ledger** beneath the dial. The numerator and denominator remain visible so the percentage never loses its biological meaning.",
 "Imani turns the crank and names **Recombination frequency**. Recombination frequency is calculated as the number of recombinant outcomes divided by the total number of scored outcomes, multiplied by one hundred to express a percentage. The meter does not care which bin looked visually large. It uses the classified evidence from the previous yard. If twelve of one hundred scored outcomes are recombinant for the tracked loci, the dial reads twelve percent. That percentage describes the observed proportion of recombinant outcomes for this genetic interval under the study conditions.",
 "The right panel responds to the dial. Lower recombination frequencies are consistent with tighter linkage because a crossover is less often observed between the loci. Higher frequencies, up to the observable ceiling, are consistent with greater relative genetic separation or effective independence. Imani keeps the wording relative and genetic. The panel is not a tape measure laid along DNA. A value of twelve percent does not mean the loci are separated by twelve percent of a chromosome, twelve base pairs, or any fixed physical number of nucleotides.",
 "A technician tries to engrave physical distance onto the meter. Imani stops him. Recombination frequency is shaped by meiotic crossover behavior and by whether crossover events produce detectable recombinant outcomes for the tracked markers. For relatively short intervals, the percentage becomes useful for estimating genetic map distance. For larger intervals, multiple crossovers can occur between the loci. Some of those crossover combinations can restore parental marker arrangements and therefore hide exchanges from simple two-locus scoring. The observed percentage can then underestimate the total number of crossover events across the interval.",
 "Imani turns the railcar model so you can see why the warning matters. One crossover between A and B can produce recombinant chromatids. Two crossovers within the interval can sometimes return the outside marker relationship to a parental arrangement. A simple two-locus count sees the final marker combinations, not a complete film of every crossover that occurred. The meter therefore measures recombinant outcomes, and the map interpretation depends on a genetic model. This is why the same percentage can serve as evidence about genetic distance without being identical to physical chromosome length.",
 "The percentage dial sends its value to a large mapping board in the next room. Imani leaves the recombinant and total counts attached to the ledger, then marks the current percentage as evidence. The next board will combine such evidence across pairs of genes to infer relative order and distance. The meter has done its job only when the learner can reconstruct where the numerator came from, what the denominator represents, and what the resulting percentage can and cannot claim."
 ],
 'close':'The meter now links recombinant proportion to relative genetic separation while refusing direct physical-distance interpretation. Its pairwise evidence moves to the linkage map board.'
},
'U5-L42':{
 'title':'The Map Board Where Centimorgans Refused to Become Centimeters',
 'kicker':'A linkage map orders genes by recombination-based genetic distance, and for short intervals about one percent recombination corresponds to approximately one centimorgan.',
 'paragraphs':[
 "The percentage signal enters the **Linkage Map Board**, a room built around a long horizontal chromosome map. On your **left**, brass markers hold pairwise recombination frequencies collected for different gene pairs. Directly **ahead**, movable locus plates can slide along a gene-order track until their arrangement fits the evidence. On your **right**, a ruler is marked in cM and not in centimeters. Dr. Imani Reyes places the **two-locus chromosome railcar** beneath the board and opens the **gold mapping ledger** to a page for gene order and genetic distance. The physical chromosome model remains visible, but the ruler is deliberately labeled as a genetic mapping tool.",
 "Imani places three hypothetical locus plates on the center board and compares their pairwise recombination evidence. She names the resulting representation a **Linkage map**. A linkage map is a genetic map that uses recombination data to infer the relative order and genetic distances among loci on a chromosome. The map is built from patterns in inheritance across many meiotic products or offspring. It does not directly sequence the DNA or count base pairs. The board therefore places genes in relative positions that are consistent with the recombination relationships.",
 "She then points to the right-side ruler and names the **Map unit (centimorgan)**. For relatively short intervals, about one percent recombination corresponds to approximately one map unit, also called one centimorgan or 1 cM. Imani aligns a one-percent marker with one cM on the short-interval portion of the ruler. The correspondence is approximate and genetic. The unit reflects recombination behavior under the mapping model. It is not one centimeter of chromosome, one million base pairs, or a universal fixed physical length.",
 "The board extends to a longer interval. Imani adds a second crossover marker and then a third. The simple one-percent-to-one-cM relationship becomes less reliable as the interval grows because multiple crossovers can occur between the loci. Some multiple-crossover outcomes are not detected as recombinant by a simple two-marker score. The observed recombination frequency can therefore underestimate the true genetic map distance over longer intervals. More sophisticated mapping functions or additional markers can improve estimates, but the basic AP Biology relationship is safest for relatively short intervals.",
 "A student assistant tries to place gene C by looking at only one pairwise value. Imani requires all available pairwise evidence to stay on the left wall. A good gene order must be consistent across the relationships. If A to B is a short interval, B to C is another interval, and A to C is larger, the arrangement should reflect those relative distances within the limits of the data. The map is an inference built from recombination evidence, not a decorative line whose spacing can be chosen freely.",
 "The optional recall lamp now lights beside the cM ruler. Imani asks, **For a short interval, about 1% recombination corresponds to approximately what genetic-map distance?** The answer is **About 1 centimorgan (1 cM).** When the lamp dims, she slides the loci farther apart. The recombination meter rises, but the map board begins flashing a ceiling warning. The final gate will explain why two-locus recombination data stop becoming more informative after the observed recombinant fraction approaches one half."
 ],
 'close':'The linkage map board now uses recombination evidence to infer relative gene order and short-interval genetic distance in centimorgans. The loci move toward the fifty-percent ceiling gate.'
},
'U5-L43':{
 'title':'The Gate Where Fifty Percent Hid Two Different Chromosome Arrangements',
 'kicker':'Observed two-locus recombination frequency approaches a maximum of about fifty percent, so a value near that ceiling cannot distinguish unlinked genes from very distant loci on the same chromosome.',
 'paragraphs':[
 "The map track reaches the **Fifty-Percent Ceiling Gate**. On your **left**, the two tracked loci slide farther and farther apart along the same chromosome model. Directly **ahead**, the **recombination meter** rises toward a massive gate labeled 50%. On your **right**, the track divides into two platforms. One platform shows genes on different chromosomes. The other shows loci very far apart on the same chromosome. Dr. Imani Reyes anchors the **gold mapping ledger** between the platforms and keeps the original blue and amber chromosome identities visible. The final problem is no longer how to calculate a percentage. It is how to interpret the limit of what that percentage can reveal.",
 "As locus separation increases, more crossover configurations can occur between the markers. Recombination frequency rises because recombinant marker combinations become more common. Yet the meter does not continue toward one hundred percent. In ordinary two-locus scoring, the observable recombinant fraction approaches a maximum of about one half. Imani names this the **Fifty-percent recombination ceiling**. At that point, parental and recombinant marker combinations occur in proportions that make the loci behave as though they assort independently in the two-locus dataset.",
 "Imani opens the same-chromosome platform on the right. The two loci are extremely far apart, and multiple crossovers can occur within the long interval. Some exchanges generate recombinant outside-marker combinations. Other combinations of exchanges restore parental outside-marker relationships. As distance grows, the simple final-marker score loses information about how many crossover events actually occurred. The recombinant fraction therefore approaches fifty percent and stops giving a simple linear measure of additional genetic separation.",
 "She then opens the different-chromosome platform. Genes on different chromosomes can assort independently during meiosis, producing the same effective fifty-percent recombinant relationship under a standard two-locus analysis. The meter cannot look at a value near fifty percent and tell which of these two chromosome arrangements generated it. Imani leaves both platform lights on. A fifty-percent recombination value alone cannot distinguish genes on different chromosomes from very distant loci on the same chromosome.",
 "The gold ledger now contains the entire mapping chain. Same-chromosome position can create linkage. A crossover between tracked loci can create recombinant chromatids. Parental and recombinant outcome classes must be identified from the original arrangement. Recombinant outcomes divided by total outcomes produce recombination frequency. Short-interval frequencies can support linkage-map distances in centimorgans. Longer intervals are complicated by multiple crossovers. Near the fifty-percent ceiling, ordinary two-locus recombination data lose the power to distinguish effective independence from very distant same-chromosome linkage.",
 "Imani closes the gate and asks you to look back down the rail yard. Every room used the same two-locus chromosome railcar. No percentage appeared before the biological classes were defined, and no map unit was allowed to become a physical ruler. The final platform therefore preserves the most important limitation of the method. Recombination mapping is an inference from inheritance outcomes. Its measurements are useful because their assumptions and boundaries remain attached to them.",
 "Beyond the gate, the rail line ends at a laboratory door marked inheritance evidence. The next journey will leave chromosome mapping and examine non-nuclear inheritance, organelle transmission, illustrative genetic cases, and chi-square goodness-of-fit reasoning. Imani closes the mapping ledger page and carries the evidence forward."
 ],
 'close':'The ceiling gate now explains why recombination frequency tops out near fifty percent and why that value cannot identify chromosome arrangement by itself. The mapping rail yard is complete.'
}
}

EXTRA={
'U5-L39':"Imani pauses the machinery and asks you to reconstruct the exchange without using the word recombination. You point first to the blue and amber homologs, then to one nonsister chromatid from each homolog, then to the crossover position between A and B, and finally to the swapped distal segments. Only after that sequence is visible does the label return. This replay matters because a recombinant type is not created by moving an allele tag by hand. It is produced when chromosome segments exchange during meiosis and the tracked loci end up in a new combination. The chromosome railcar preserves that causal chain from structure to outcome.",
'U5-L40':"To test the sorter, Imani deliberately changes the number of items in the bins without changing their identities. A small parental class remains parental if it matches the original arrangement, and a large recombinant class would still be recombinant if it carried a new tracked combination. The exercise strips frequency away from category. Only after the identities are fixed does count become useful. This is the logic students will need later when a dataset is noisy, sample sizes are small, or the familiar pattern of two large parental classes and two smaller recombinant classes is less visually obvious.",
'U5-L41':"Imani covers the right interpretation panel and gives you only the counts. You must first state the measured quantity in words before the dial is allowed to move. The numerator is the number of recombinant outcomes for the tracked loci. The denominator is the total number of scored outcomes. When you uncover the panel again, the percentage can support a statement about genetic linkage only because its biological ingredients are still known. The yard is training a habit that will matter in Challenge Lab calculations. A number earns meaning from the observations and model that produced it.",
'U5-L42':"The board then tests a tempting mistake. A brass ruler marked in base pairs is brought beside the centimorgan scale, but the tick marks fail to align consistently. Imani leaves both rulers visible for comparison. Physical distance measures nucleotide separation along DNA. Genetic distance reflects recombination behavior and is influenced by how often crossovers are recovered between loci. The two quantities can be related in real genomes, yet the relationship is not a universal conversion factor. For this palace, the cM ruler therefore remains attached to inheritance evidence while physical DNA length stays on a separate instrument.",
'U5-L43':"Before leaving, Imani lowers the meter from fifty percent to a smaller value and then raises it again. Below the ceiling, changing recombination frequency can still provide useful relative mapping information within the model. At the ceiling, that simple two-locus information saturates. The loss is informational, not a claim that crossovers have stopped occurring. Very distant loci can experience many crossover events even while the final marker classes approach the same fifty-fifty relationship seen for effectively unlinked genes. The gate marks the limit of the measurement, not the limit of chromosome motion."
}
for _lid,_para in EXTRA.items():
    STORY[_lid]['paragraphs'].insert(-1,_para)

route=[
 {'scene_index':0,'locus':'Linked-Gene Platform','short':'Linked genes','floor':'South loading platform','symbol':'same chromosome'},
 {'scene_index':1,'locus':'Recombination Switch','short':'Recombination','floor':'Crossover switch house','symbol':'nonsister exchange'},
 {'scene_index':2,'locus':'Parental–Recombinant Sorting Yard','short':'Sort classes','floor':'Central sorting yard','symbol':'parental recombinant'},
 {'scene_index':3,'locus':'Recombination Frequency Meter','short':'Frequency','floor':'North meter hall','symbol':'recombinants over total'},
 {'scene_index':4,'locus':'Linkage Map Board','short':'Map','floor':'East mapping board','symbol':'cM'},
 {'scene_index':5,'locus':'Fifty-Percent Ceiling Gate','short':'50% ceiling','floor':'Far-east ceiling gate','symbol':'50%'}]

scenes=[]
briefs=[b for b in F3 if b['journey_id']=='U5-J7']
for idx,b in enumerate(briefs):
    z=ZONE_COPY[b['locus_id']]
    checkpoint=bool(b['quick_recall']['enabled'])
    object_ids=b['knowledge_ids']
    beats=[]
    for t in b['term_introductions']:
        beats.append({'object_id':t['knowledge_id'],'term':t['canonical_term'],'story':f"{b['scene_title']} makes {t['canonical_term']} visible through the continuous chromosome railcar and mapping evidence before the exact name is attached.",'science':CANON[t['knowledge_id']]['canonical_verified_statement'],'exact_name':bool(t['exact_name_recall']),'hint':b['micro_anchor'],'name_support':t['name_support']})
    cast=[GUIDE,RAILCAR,METER,LEDGER]+[{'name':name,'kind':'scientific zone','visual':desc,'job':f'occupies the {pos} zone and preserves the fixed scientific role of {anchor}.'} for pos,name,anchor,desc in z]
    prose=STORY[b['locus_id']]['paragraphs']
    scenes.append({
      'scene_index':idx,'locus_id':b['locus_id'],'locus':b['scene_title'],'title':STORY[b['locus_id']]['title'],'scene_kicker':STORY[b['locus_id']]['kicker'],
      'location_description':b['micro_anchor'],
      'scene_layout':{'orientation':b['orientation_sentence'],'zones':[{'position':pos,'name':name,'memory_anchor':anchor,'description':desc} for pos,name,anchor,desc in z]},
      'cast':cast,'continuity_object':J7BRIEF['continuity_object'],'story_open':prose[0],'story_paragraphs':prose,'story_close':STORY[b['locus_id']]['close'],
      'object_ids':object_ids,'story_beats':beats,'memory_snapshot':[{'term':t['canonical_term'],'meaning':t['canonical_science'],'image':b['micro_anchor']} for t in b['term_introductions']],
      'misconception_guards':b['misconception_guards'],'exit_memory':b['exit_memory'],
      'checkpoint':checkpoint,'checkpoint_object_id':object_ids[0] if checkpoint else None,'checkpoint_prompt':b['quick_recall'].get('candidate_prompt','') if checkpoint else '',
      'checkpoint_answer':b['quick_recall'].get('answer','') if checkpoint else '',
      'checkpoint_hint':('Return to the fixed chromosome railcar and identify the crossover position or the genetic-map ruler before naming the answer.' if checkpoint else ''),
      'next_locus':briefs[idx+1]['scene_title'] if idx+1<len(briefs) else None,'causal_transition':b['causal_transition']['transition_logic']})

journey={
 'palace_id':'U5-J7','unit_id':'unit-5','palace_name':'Chromosome Mapping Rail Yard','story_title':'The Rail Yard That Turned a Percentage Into a Distance',
 'tagline':'Track one two-locus chromosome railcar from linkage through crossover, outcome sorting, recombination frequency, linkage mapping, and the fifty-percent ceiling without losing the distinction between genetic and physical distance.',
 'guide':GUIDE,
 'premise':'The Chromosome Mapping Rail Yard has been producing maps from percentages without preserving where those percentages came from. Parental classes, recombinant classes, map units, and physical distances have been mixed together. The yard can be repaired only if the same two-locus chromosome railcar and parental arrangement remain visible from the first linkage platform to the final ceiling gate.',
 'mission':'Follow Dr. Imani Reyes through six connected locations. Tie linkage to same-chromosome position, create recombination through a crossover between tracked loci, classify parental and recombinant outcomes from the known starting arrangement, calculate recombination frequency from those classes, infer short-interval linkage-map distances in centimorgans, and finish by explaining the fifty-percent ceiling and its interpretive limit.',
 'finale':'The rail yard now keeps evidence and inference attached. Recombination frequency describes observed recombinant outcomes, linkage maps use those outcomes to infer relative genetic distance, centimorgans remain genetic-map units, and the fifty-percent ceiling marks where ordinary two-locus data can no longer distinguish very distant same-chromosome loci from effectively unlinked genes.',
 'estimated_minutes':24,'scene_count':6,'checkpoint_count':2,'student_release':'DEVELOPER_PREVIEW_F4G',
 'learner_rule':'Keep the same two-locus chromosome railcar and original parental arrangement in view. Classify biological outcomes before calculating a percentage, and interpret a percentage only after recalling what it measured. Optional Quick Recall appears only twice.',
 'route_orientation':'This is one continuous south-to-east rail-yard route. Begin at the south linked-gene loading platform, pass through the crossover switch, cross the central parental-recombinant sorting yard, enter the north recombination-frequency meter hall, continue to the east linkage map board, and finish at the far-east fifty-percent ceiling gate. The same chromosome railcar, recombination meter, and gold mapping ledger persist throughout.',
 'route':route,'scenes':scenes,'narrative_design':'U5-F4G-NARRATIVE-1.0'}
(U5/'journeys'/'U5-J7.json').write_text(json.dumps(journey,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
allj=PREV+[journey]
registry={'schema':'memory-palace-v2-unit5-f4g-journeys-1.0','unit_id':'unit-5','stage':'F4G','student_release':False,'preview_release':True,'journey_count':7,'scene_count':43,'checkpoint_count':15,'guided_journeys':[{k:j[k] for k in ['palace_id','palace_name','story_title','tagline','guide','premise','mission','finale','estimated_minutes','scene_count','checkpoint_count','student_release','narrative_design']} for j in allj]}
(U5/'journeys-f4g.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
status={'unit_id':'unit-5','unit_number':5,'title':'Heredity','status':'F4G_JOURNEYS1_7_POLISHED_DEVELOPER_PREVIEW','pipeline_status':'POLISHED_NARRATIVE_J1_J2_J3_J4_J5_J6_J7_F4G','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','student_release':False,'preview_release':True,'canonical_records':152,'review_flags_resolved':37,'teacher_ppt_slides':112,'ced_topics':5,'ced_atoms':34,'architecture_journeys':8,'architecture_loci':50,'scene_briefs':50,'preview_journeys':7,'preview_scenes':43,'preview_checkpoints':15,'journey_1_records':20,'journey_2_records':18,'journey_3_records':8,'journey_4_records':25,'journey_5_records':7,'journey_6_records':24,'journey_7_records':10,'next_gate':'F4H_JOURNEY8_ONLY_AFTER_F4G_PROSE_QA'}
(U5/'status-f4g.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(U5/'status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
words=sum(len(re.findall(r"\b[\w’'-]+\b",' '.join(s['story_paragraphs']))) for s in scenes)
manifest={'schema':'memory-palace-v2-unit5-f4g-release-manifest-1.0','unit_id':'unit-5','stage':'F4G','student_release':False,'preview_release':True,'journey_count':7,'scene_count':43,'checkpoint_count':15,'journey_7_records':10,'journey_7_narrative_words':words,'f1_canonical_records':152,'f2_permanent_loci':50,'f3_scene_briefs':50,'next_gate':'F4H'}
(U5/'f4g-release-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
course_path=ROOT/'content'/'ap-biology'/'course.json'; course=json.loads(course_path.read_text(encoding='utf-8')); cu5=next(u for u in course['units'] if u['unit_id']=='unit-5')
cu5.update({'status':'F4G_JOURNEYS1_7_POLISHED_DEVELOPER_PREVIEW','journey_count':7,'scene_count':43,'canonical_lock':'LOCKED_F1','source_status':'AUDITED_SCIENCE_LOCKED_F1_ARCHITECTURE_F2_SCENE_BRIEFS_F3_NARRATIVE_J1_F4A_J2_F4B_J3_F4C_J4_F4D_J5_F4E_J6_F4F_J7_F4G','canonical_records':152,'review_flags_resolved':37,'ced_atoms':34,'teacher_ppt_slides':112,'student_release':False,'preview_release':True,'pipeline_stage':'UNIT5_JOURNEYS1_7_POLISHED_DEVELOPER_PREVIEW_F4G'})
course_path.write_text(json.dumps(course,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
backend=ROOT/'backend'/'content.py'; text=backend.read_text(encoding='utf-8')
old='    if unit_id == "unit-5":\n        path=UNIT5_DIR / "journeys-f4f.json"'
new='    if unit_id == "unit-5":\n        path=UNIT5_DIR / "journeys-f4g.json"\n        if not path.exists(): path=UNIT5_DIR / "journeys-f4f.json"'
if old in text: text=text.replace(old,new)
elif 'path=UNIT5_DIR / "journeys-f4g.json"' not in text: raise RuntimeError('Could not patch Unit 5 preview registry to F4G')
backend.write_text(text,encoding='utf-8')
lock_files=['journeys/U5-J7.json','journeys-f4g.json','status-f4g.json','f4g-release-manifest.json']
lock={'schema':'memory-palace-v2-unit5-content-lock-f4g-1.0','unit_id':'unit-5','stage':'F4G','lock_status':'LOCKED_F4G_J7','student_release':False,'preview_release':True,'files':{}}
for rel in lock_files:
    p=U5/rel; lock['files'][rel]={'bytes':p.stat().st_size,'sha256':sha(p)}
(U5/'content-lock-f4g.json').write_text(json.dumps(lock,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Unit 5 F4G · Journey 7 Narrative','',f'## {journey["story_title"]}','',journey['tagline'],'','**Palace**  Chromosome Mapping Rail Yard  ','**Guide**  Dr. Imani Reyes  ','**Route**  '+' → '.join(x['locus'] for x in route),'']
for s in scenes: lines += [f"## {s['scene_index']+1}. {s['locus']} — {s['title']}",'',f"*{s['scene_kicker']}*",'']+s['story_paragraphs']+['']
(ROOT/'docs'/'UNIT5_F4G_JOURNEY7_STORY.md').write_text('\n'.join(lines),encoding='utf-8')
release=['# Unit 5 F4G Release','','Unit 5 F4G authors and locks Journey 7 only while preserving Journeys 1–6 against their earlier narrative locks. Unit 5 remains a developer preview and is not student released.','','## Accounting','','- Journeys 1–6 preserved: **37 scenes / 102 records / 13 optional recalls**','- Journey 7 authored: **6 scenes / 10 records / 2 optional recalls**',f'- Journey 7 narrative words: **{words}**','- Total Unit 5 preview: **7 journeys / 43 scenes / 15 optional recalls**','','## Scientific continuity','','- Genetic linkage remains same-chromosome inheritance tendency, not a permanent bond.','- Crossing over between nonsister chromatids creates recombinant marker combinations only when the exchange changes the tracked interval.','- Parental and recombinant types are classified against the known starting arrangement before frequency arithmetic.','- Recombination frequency remains recombinant outcomes divided by total scored outcomes and is interpreted as genetic evidence.','- For relatively short intervals, about 1 percent recombination corresponds to about 1 cM.','- Centimorgans remain genetic-map units and are not direct physical base-pair distances.','- Multiple crossovers can make observed recombination frequency underestimate longer genetic distances.','- The observed two-locus recombination fraction approaches a 50 percent ceiling and cannot by itself distinguish different chromosomes from very distant loci on the same chromosome.','','## Release boundary','','No Unit 5 Memory Objects, Review runtime, Challenge Lab runtime, or student-facing Unit 5 release is created in F4G. Journey 8 remains at the F3 scene-brief stage.','']
(ROOT/'docs'/'UNIT5_F4G_RELEASE.md').write_text('\n'.join(release),encoding='utf-8')
print(json.dumps({'journey':'U5-J7','scenes':6,'records':10,'checkpoints':2,'narrative_words':words,'student_release':False,'preview_release':True},indent=2))
