from __future__ import annotations
import json, hashlib, re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
U6=ROOT/'content'/'ap-biology'/'unit-6'
BRIEFS=json.loads((U6/'briefs'/'scene-briefs-f3.json').read_text(encoding='utf-8'))['scene_briefs']
JBRIEFS=json.loads((U6/'briefs'/'journey-briefs-f3.json').read_text(encoding='utf-8'))['journeys']
J2=next(j for j in JBRIEFS if j['journey_id']=='U6-J2')
B={b['locus_id']:b for b in BRIEFS if b['journey_id']=='U6-J2'}
CANON={r['knowledge_id']:r for r in json.loads((U6/'source'/'canonical-unit6-f1.json').read_text(encoding='utf-8'))['canonical_catalog']}

GUIDE={
 'name':'Dr. Sora Han','role':'molecular-information systems director',
 'visual':'dark-cobalt lab coat, clear gloves, transparent 5′→3′ compass tablet, and a narrow copper information ledger',
 'story_job':'Sora keeps the same tagged gene, violet template strand, promoter marker, and growing RNA transcript visible from the first RNA desk through transcription and RNA processing. She points to real molecules, changes only the feature needed for the mechanism, and names terms after their defining action is visible.'
}

ROUTE=[
 {'scene_index':0,'locus':'RNA Function Desk','short':'RNA roles','floor':'Workshop intake','symbol':'RNA'},
 {'scene_index':1,'locus':'tRNA Courier Bay','short':'tRNA','floor':'Courier bay','symbol':'tRNA'},
 {'scene_index':2,'locus':'Gene Expression Junction','short':'Expression','floor':'Junction','symbol':'DNA→RNA→P'},
 {'scene_index':3,'locus':'Template–Promoter Entry Gate','short':'Template','floor':'Entry gate','symbol':'PROM'},
 {'scene_index':4,'locus':'Transcription Direction Rail','short':'Transcribe','floor':'Direction rail','symbol':'5′→3′'},
 {'scene_index':5,'locus':'Prokaryotic Transcript Exit','short':'Prokaryote','floor':'Open exit','symbol':'↔'},
 {'scene_index':6,'locus':'Pre-mRNA Processing Counter','short':'Process','floor':'Nuclear counter','symbol':'CAP—Aₙ'},
 {'scene_index':7,'locus':'Splice and Isoform Chamber','short':'Splice','floor':'Export chamber','symbol':'✂RNA'},
]

ZONES={
'U6-L13':[
 ('left','mRNA message lane','mRNA','A clean RNA ribbon runs leftward toward a message rack labeled for ribosome delivery. It remains physically separate from the structural RNA models elsewhere in the room.'),
 ('center','RNA sequence/structure function desk','RNA↺','A broad center desk holds three RNA molecules whose different nucleotide sequences and folded shapes can be compared before their jobs are assigned.'),
 ('right','rRNA ribosome-component lane','rRNA','A ribosomal RNA model occupies the right lane and folds into a ribosome-shaped structural/catalytic display rather than carrying a message.')],
'U6-L14':[
 ('left','amino-acid attachment side','AA','Amino acids wait on individual attachment pads on the left, each pad aligned with a matching tRNA identity.'),
 ('center','tRNA anticodon courier','tRNA','A cloverleaf tRNA model stands at center with its amino-acid attachment end high and its three-base anticodon exposed low on the molecule.'),
 ('right','mRNA pairing / recruitment side','codon','A horizontal mRNA ribbon enters from the right so a complementary anticodon can pair antiparallel with one codon before the tRNA moves toward a ribosome marker.')],
'U6-L15':[
 ('left','transcription DNA→RNA lane','DNA→RNA','A tagged gene and a growing RNA ribbon occupy the left lane, showing information copied from DNA into RNA.'),
 ('center','gene-expression junction','GENE','A circular junction at center receives information from the gene and routes it either to a functional RNA destination or onward toward a protein-coding route.'),
 ('right','translation RNA→polypeptide lane','RNA→protein','A ribosome and growing amino-acid chain occupy the right lane, physically separated from the DNA-to-RNA process on the left.')],
'U6-L16':[
 ('left','template-strand selection side','template','The same tagged gene is opened just enough to expose both DNA strands; the violet strand is marked as the strand that will be read.'),
 ('center','promoter entry gate','PROM','A promoter region sits before the transcribed region at center, where transcription machinery can assemble without being confused with the RNA-coding region itself.'),
 ('right','TATA-box contextual panel','TATA','A small TATA sequence panel is mounted on the right as one possible promoter element in some eukaryotic genes, visibly smaller than the larger promoter gate.')],
'U6-L17':[
 ('left','initiation station','START','RNA polymerase waits at the left initiation station beside the selected promoter and the violet template strand.'),
 ('center','template 3′→5′ / RNA 5′→3′ rail','⇄','A long center rail carries the violet DNA template in the 3′→5′ reading direction while the red RNA ribbon grows alongside it 5′→3′.'),
 ('right','elongation and termination stations','END','The rail passes through elongation markers and ends at a termination station where the completed RNA transcript can be released.')],
'U6-L18':[
 ('left','DNA transcription area','DNA','A bacterial chromosome region remains exposed on the left in the same open cellular space as the new transcript.'),
 ('center','usable prokaryotic transcript exit','RNA','The newly synthesized bacterial mRNA exits directly through the center without passing through a nucleus-based cap, poly-A-tail, and splice counter.'),
 ('right','ribosome-access side','RIBO','Ribosomes stand immediately on the right, close enough that a transcript can be engaged for translation while transcription is still occurring.')],
'U6-L19':[
 ('left','5′ cap / recognition side','CAP','The 5′ end of a eukaryotic pre-mRNA enters from the left beside a cap station that can add a modified guanine nucleotide.'),
 ('center','pre-mRNA processing counter','pre-mRNA','A long pre-mRNA ribbon lies across the center counter with its 5′ and 3′ ends kept visible and its internal intron/exon pattern still intact.'),
 ('right','poly-A tail / stability side','Aₙ','At the right end, a transcribed polyadenylation signal precedes cleavage and the addition of a long poly-A tail.')],
'U6-L20':[
 ('left','intron excision side','INTRON','Dark intron segments are lifted from the left side of the same pre-mRNA, leaving clean boundaries that show exactly what was removed.'),
 ('center','exon-splicing / alternative-splicing chamber','EXONS','Retained exon segments are joined in the center; a second pass can select a different exon combination while the underlying gene DNA remains unchanged.'),
 ('right','mature-mRNA exit','mRNA✓','A finished, directionally intact mature mRNA exits on the right with cap, poly-A tail, and one resolved exon arrangement ready for export and translation.')],
}

NARR={
'U6-L13':{
 'title':'Three RNA Ribbons Arrive With the Same Name and Different Jobs',
 'kicker':'The workshop cannot route an RNA molecule by the word RNA alone; sequence and folded structure determine what each molecule can do.',
 'paragraphs':[
  "The **RNA Transcript Workshop** begins in a low, rectangular intake room where three RNA molecules have been delivered to the wrong desk. On your **left**, an **mRNA message lane** ends at a rack shaped for a long, readable RNA ribbon. Directly **ahead**, the center **RNA sequence/structure function desk** holds three transparent RNA models under adjustable folding frames. On your **right**, an **rRNA ribosome-component lane** ends at a half-built ribosome shell. Dr. Sora Han places her copper ledger on the center desk. Behind her, a tagged gene waits inside a glass carrier: one DNA strand is violet, the opposite strand gold, and a small promoter marker sits just before the region that will eventually be transcribed. A red RNA ribbon is clipped to the carrier but is still only a short stub. The workshop doors remain shut because every incoming RNA has been stamped simply RNA, as though that label alone explained its function.",
  "Sora lifts the first RNA model and changes nothing except its nucleotide sequence and the places where the strand can base-pair with itself. The molecule bends into a new three-dimensional shape. She then does the same with the second model, producing a different fold and a different interaction surface. Only after the physical difference is visible does she write **RNA sequence and structure determine function**. RNA is not one generic cable. Its base sequence helps determine how the molecule folds and what other molecules it can recognize or become part of, so sequence and structure together constrain function. That principle will matter throughout the workshop because the RNA transcript you follow will change in length and processing state while retaining an identifiable nucleotide sequence.",
  "She slides one long RNA ribbon to the lane on your left. Its job is informational rather than structural. The ribbon carries a nucleotide sequence copied from DNA toward a ribosome, where that sequence can later guide translation. Sora labels this **mRNA function**: messenger RNA carries genetic information from DNA to ribosomes for translation. The label belongs to the molecule because of what it carries and where that information is used. She does not send the mRNA into the ribosome as a structural brick; it remains a readable message that the ribosome will move along.",
  "On the right, the second RNA model folds into the waiting ribosomal shell. It does not leave as a message. The RNA itself becomes part of the ribosome’s structure and catalytic machinery. Sora names this **rRNA as ribosome component**: ribosomal RNA is a functional building block of ribosomes and participates in protein synthesis. A small size chart appears beside the display, but Sora keeps it secondary. The bacterial ribosome is built from 30S and 50S subunits, while a eukaryotic cytosolic ribosome has 40S and 60S subunits. Those numbers describe ribosome types; they do not change the central relationship that rRNA is a working part of the ribosome.",
  "The third RNA model remains on the center desk. It is compact, folded, and carries a small docking site at one end and a three-base reading region at the other. Sora does not name its detailed job yet. Instead, she places an amino acid on the left wall and an mRNA codon on the right wall, then lets the third RNA hang between them like a courier waiting for two addresses. The intake problem is now clear. mRNA, rRNA, and the waiting courier are all RNA, yet their sequences, structures, and molecular partners give them different roles. The center desk unlocks a narrow door marked COURIER BAY. The red transcript stub on the tagged gene remains unchanged; before the workshop can make that transcript, you first need to understand the RNA molecule that will later read its codons."
 ]},
'U6-L14':{
 'title':'The Courier Must Carry the Right Cargo and Read the Right Address',
 'kicker':'A tRNA links one specific amino acid to one complementary mRNA codon, so cargo identity and codon recognition must stay distinct.',
 'paragraphs':[
  "The door opens into the **tRNA Courier Bay**, a narrow loading room arranged around a single cloverleaf-shaped molecule. On your **left**, an **amino-acid attachment side** holds twenty small cargo pads, each displaying an amino-acid name. Directly **ahead**, a large **tRNA anticodon courier** is suspended upright at center. Its amino-acid attachment end points upward, while a three-base anticodon hangs at the bottom. On your **right**, an **mRNA pairing / recruitment side** carries a horizontal mRNA ribbon with one codon framed in light. A ribosome marker waits farther down that same right-side track. Sora brings the tagged gene carrier into the room and clips it near the door. The short red RNA transcript is still attached to the carrier, reminding you that this courier system will matter only after a message has been made.",
  "Sora begins at the left cargo pads. She tries attaching the same amino acid to several differently labeled tRNAs, and the bay rejects the mismatches. Distinct tRNA molecules are associated with specific amino acids. Only when the correct pairing is made does the attachment light turn green. Sora records **tRNA amino-acid specificity**: distinct tRNA molecules bind specific amino acids. The important image is the cargo end of the tRNA. The amino acid does not attach to the anticodon, and the anticodon does not decide by itself which amino acid is chemically attached. Cargo identity and message recognition are two features of the same tRNA molecule that must remain mentally separate.",
  "She then lowers the charged tRNA toward the mRNA track on your right. The three bases on the tRNA rotate until they face a three-base sequence on the mRNA. The two sequences align in opposite directions and pair complementarily. Sora names **tRNA anticodon pairing**: each tRNA has an anticodon that base-pairs with a complementary mRNA codon. She traces the three bases with her compass tablet. The tRNA sequence is an **anticodon**; the corresponding three-base sequence on mRNA is a **codon**. Calling both of them codons would erase the directional relationship that lets the courier recognize the message.",
  "Only after the cargo and the anticodon are both correct does the right-side track move. The tRNA slides toward the ribosome marker with its amino acid still attached. This is **tRNA recruitment during translation**: tRNA is recruited to the ribosome so the mRNA sequence can direct the primary amino-acid sequence. Sora leaves the ribosome itself unopened because the detailed translation machinery belongs to the next journey. Here the goal is to make one bridge unmistakable. A nucleotide sequence in mRNA can influence the order of amino acids only because tRNAs bring specific amino-acid cargo while recognizing codons through complementary anticodons.",
  "The bay freezes with three positions easy to reconstruct: amino-acid cargo on the left, tRNA in the center, mRNA codon and future ribosome on the right. Sora closes her ledger and points back to the tagged gene. The workshop now has three RNA roles on record, but it still has not answered the larger question of how information in that DNA becomes either a functional RNA product or a polypeptide. A circular floor junction ahead lights two arrows at once: DNA→RNA to the left, RNA→POLYPEPTIDE to the right. The courier track feeds directly into it.",
  "**Optional Quick Recall.** Without looking back, picture the tRNA suspended in the middle of the bay. What does **tRNA amino-acid specificity** mean? The answer should come from the left-side cargo test: distinct tRNA molecules bind specific amino acids."
 ]},
'U6-L15':{
 'title':'One Junction Separates Copying a Message From Reading It',
 'kicker':'Gene expression contains distinct information-transfer processes, and a protein-coding route does not begin with translation.',
 'paragraphs':[
  "You enter the **Gene Expression Junction** at the point where the workshop divides into two visibly different operations. On your **left**, the **transcription DNA→RNA lane** holds the same tagged gene and the short red RNA ribbon beside it. Directly **ahead**, a circular **gene-expression junction** has two destination gates: FUNCTIONAL RNA and PROTEIN-CODING OUTPUT. On your **right**, the **translation RNA→polypeptide lane** contains a ribosome model and a chain of amino-acid beads beginning to emerge from it. Sora stands in the center and turns off every arrow except the one from the DNA gene to the RNA ribbon. The spatial separation matters. If the left and right lanes are collapsed together, transcription and translation become a single vague event, and every directional rule that follows becomes harder to understand.",
  "Before either gate opens, Sora briefly places a folded protein model beside the right lane. You have already seen that a protein is built from one or more polypeptide chains whose amino-acid sequence contributes to higher-order structure and function. That **Protein structure prerequisite** stays exactly what it was; the workshop does not create a second mnemonic for it. Sora uses it only as the downstream reason a protein-coding gene matters. If the amino-acid sequence changes, the structure and function of the protein may change. The journey here is about how nucleotide information reaches that downstream sequence.",
  "She places the tagged gene at the center junction and opens both destination gates. Some genes produce functional RNA products that work as RNA. Protein-coding genes continue farther and ultimately produce polypeptides. Sora names the larger process **Gene expression**: gene expression is the use of information in a gene to produce a functional RNA or polypeptide product; for protein-coding genes it includes transcription and translation. This definition prevents a common shortcut. Gene expression is broader than translation, and not every gene must end as a protein to count as expressed.",
  "Sora now activates only the left lane. RNA polymerase appears beside the DNA, and the red RNA ribbon begins extending from information in one DNA strand. Only after the DNA-to-RNA direction is physically visible does she name the process. **Transcription definition**: transcription is DNA-directed synthesis of RNA by RNA polymerase. The DNA remains DNA. The RNA is a new nucleic-acid product whose sequence is directed by the DNA template. No ribosome is needed to perform this step.",
  "Then the left lane stops and the right lane activates. A mature mRNA ribbon enters a ribosome. Amino acids are added to a growing polypeptide in an order specified by the mRNA nucleotide sequence. Sora names **Translation definition**: translation is synthesis of a polypeptide using the nucleotide sequence of mRNA as information at a ribosome. The two lanes now make a clean distinction: transcription converts information from DNA into RNA; translation uses an mRNA sequence to specify a polypeptide. In a eukaryotic cell, transcription of nuclear genes occurs in the nucleus and translation occurs in the cytoplasm. Prokaryotes have no nucleus, so that spatial separation does not apply in the same way.",
  "The junction lights only the DNA→RNA lane again. The red RNA ribbon retracts to its short starting stub, because you are about to follow transcription rather than skip ahead to translation. The tagged gene moves through a gate where its two strands separate just enough to reveal that only one will be read. A large promoter marker waits before the gene, and a much smaller TATA panel hangs off to the right. The workshop cannot begin transcription until those structures are distinguished."
 ]},
'U6-L16':{
 'title':'The Gate Opens Only for the Correct Strand and the Correct Starting Region',
 'kicker':'Transcription requires one DNA template strand and a promoter, while a TATA box is only one possible promoter element in some eukaryotic genes.',
 'paragraphs':[
  "The **Template–Promoter Entry Gate** is built like a checkpoint around the same tagged gene. On your **left**, the **template-strand selection side** holds the two DNA strands apart. The violet strand faces you with 3′ and 5′ labels exposed; the gold strand remains paired beside it but is kept visibly separate. Directly **ahead**, the center **promoter entry gate** sits before the transcribed region of the gene. On your **right**, a smaller **TATA-box contextual panel** displays a short TATA-rich DNA element under a sign that says SOME EUKARYOTIC PROMOTERS. Sora places the copper ledger beneath the promoter and leaves the red RNA ribbon at zero length. Nothing is allowed to move until the workshop knows what DNA will be read and where transcription machinery assembles.",
  "Sora first tests the two DNA strands. RNA polymerase is placed against the gold strand, then the violet strand. Only one strand is designated to direct complementary RNA synthesis for this gene. Sora locks the violet strand into the reading rail and names **Transcription uses one DNA template strand**: RNA polymerase uses a single DNA template strand to direct complementary RNA synthesis; this process is transcription. The opposite DNA strand is still biologically real and still part of the gene’s double-stranded DNA; it simply is not the template read by RNA polymerase for this transcription event.",
  "She adds a permanent violet TEMPLATE label to that strand. This is **Template strand terminology**. For a transcribed gene, RNA polymerase reads one DNA template strand. Historical aliases can create confusion, so Sora keeps the physically read strand marked simply template strand. That term tells you its functional relationship to the RNA product. It does not mean the other strand is biologically useless, and it does not create a new kind of DNA molecule.",
  "The center gate still remains closed. Sora slides the gene until a regulatory DNA region before the transcribed sequence aligns with the gate sensors. Proteins representing transcription machinery gather there. Only after the assembly site is visible does she label **Promoter**: a promoter is a DNA region where transcription machinery assembles to initiate transcription of a gene. The promoter is DNA. It is not RNA polymerase, not a transcription factor, and not merely the first codon of the future mRNA. Its job in this room is to establish where the transcription machinery can assemble and initiate the transcription process.",
  "Finally she points to the small panel on your right. A TATA-rich element clicks into one example promoter and helps organize transcription machinery. Sora names **TATA box** only after showing its limited place: a TATA box is a promoter DNA element found in some eukaryotic genes and can participate in assembly of transcription machinery; it is not present in every eukaryotic promoter. The physical size of the display makes the relationship memorable: the promoter gate is the larger category, and the TATA box is one possible element within some promoter architectures. The two terms must not collapse into synonyms.",
  "The promoter gate unlocks. RNA polymerase grips the DNA at the correct starting region while the violet template strand feeds into a long direction rail beyond the door. The red RNA ribbon attaches to the polymerase but cannot yet grow because two opposing arrows are flashing above the track. One arrow marks the DNA template 3′→5′. The other marks RNA growth 5′→3′. Sora moves the same tagged gene forward without flipping it."
 ]},
'U6-L17':{
 'title':'The Transcript Can Grow in Only One Chemical Direction',
 'kicker':'RNA polymerase reads the DNA template 3′→5′ while synthesizing RNA 5′→3′, and that direction stays constant through transcription.',
 'paragraphs':[
  "The **Transcription Direction Rail** is the longest room in the workshop, and its geometry forces you to choose a direction before you can walk it. On your **left**, the **initiation station** holds RNA polymerase at the promoter of the same tagged gene. Directly **ahead**, the center **template 3′→5′ / RNA 5′→3′ rail** stretches across the floor. The violet template DNA runs along one side with its 3′ end nearest the initiation station and its 5′ end farther down the room. Beside it, the red RNA ribbon begins with its 5′ end at the left and an exposed growing 3′ end facing forward. On your **right**, the rail passes through labeled elongation markers and reaches a termination station. Sora lays her compass tablet flat between the two molecules so both directional arrows can be seen at once.",
  "RNA polymerase leaves the promoter and begins moving along the violet DNA template. Each time a template base enters the polymerase, a complementary RNA nucleotide is added to the growing RNA’s 3′ end. The red ribbon lengthens toward the right, but its chemical direction is 5′→3′. At the same time, the polymerase is reading the DNA template in the opposite direction, 3′→5′. Sora names **Transcription directionality** only after several nucleotides have been added: RNA polymerase synthesizes RNA 5′→3′ while reading the DNA template 3′→5′. The relation is not a decorative arrow rule. It follows from where new nucleotides can be added to a nucleic-acid strand.",
  "The rail is divided into three large physical sections. At the left, transcription machinery assembles and RNA synthesis begins. Across the long center span, RNA polymerase moves along the gene and the RNA transcript elongates. At the right, transcription reaches a termination process and the transcript is released. Sora labels this useful process organization **Transcription initiation, elongation, termination**. The three names describe stages of one transcription process, not three different information-transfer pathways. She keeps the detailed termination machinery out of the main display so the route does not turn into a list of factor names.",
  "Halfway down the rail, Sora opens a second starting platform behind the first RNA polymerase. A second polymerase begins transcribing the same active gene before the first has finished, then a third starts behind it. All three move along the same template orientation and all three synthesize separate RNA molecules 5′→3′. This demonstrates **Multiple RNA polymerases increase transcript output**. Several polymerases can transcribe the same gene at the same time, increasing RNA production without changing the gene sequence or the direction of RNA synthesis. More transcripts arise because more polymerases are working along the same gene, not because any one polymerase suddenly moves in the reverse chemical direction.",
  "At the far end, the first red RNA ribbon is released and carried to an exit fork. Sora leaves its 5′ end marked at the front and its 3′ end marked at the back so direction remains visible after release. One doorway on the right is completely open and has ribosomes nearby. Another doorway is surrounded by a nuclear-envelope frame and leads toward RNA-processing counters. The transcript must take different routes depending on cellular context. Before choosing, Sora pauses beside the rail.",
  "**Optional Quick Recall.** Without looking back at the arrows, state **Transcription directionality**. RNA polymerase synthesizes RNA 5′→3′ while reading the DNA template 3′→5′."
 ]},
'U6-L18':{
 'title':'One Transcript Reaches a Ribosome Before a Nuclear Processing Counter Exists',
 'kicker':'In many bacteria, transcription and translation occupy the same cellular space, so mRNA can become usable without the eukaryotic cap–tail–splicing route.',
 'paragraphs':[
  "The first branch leads to the **Prokaryotic Transcript Exit**, an open room with no nuclear envelope around the DNA. On your **left**, the **DNA transcription area** contains a bacterial chromosome region with RNA polymerase still moving along it. Directly **ahead**, the center **usable prokaryotic transcript exit** receives the growing red mRNA as it emerges from the polymerase. On your **right**, the **ribosome-access side** holds several ribosomes only a short distance away. There is no cap station, no poly-A-tail counter, and no splice chamber between the transcript and those ribosomes. Sora keeps the bacterial DNA, polymerase, transcript, and ribosome all inside the same cellular space so the consequence of lacking a nucleus is visible rather than merely stated.",
  "As the 5′ portion of the bacterial mRNA emerges, a ribosome attaches to the accessible transcript even though RNA polymerase is still extending the 3′ end farther along the gene. The two processes remain distinct—one polymerase is synthesizing RNA from DNA, while one ribosome is reading mRNA to synthesize a polypeptide—but they can occur in the same cellular compartment and can overlap in time. This is why prokaryotic gene expression can couple transcription and translation in a way that nuclear transcription and cytoplasmic translation cannot be coupled in the same physical manner in eukaryotic cells.",
  "Sora now points to the empty center exit. The absence of a eukaryotic processing counter does not mean bacterial RNA never undergoes any processing. The narrower relationship is **Prokaryotic transcript usability**: many bacterial mRNAs can be translated without the eukaryotic cap/poly-A/splicing processing sequence and can be translated while transcription continues. The phrase many bacterial mRNAs matters. It describes a common prokaryotic route without pretending that all RNA molecules in all prokaryotes experience no processing of any kind.",
  "She places a transparent outline of a eukaryotic nucleus beside the bacterial room. In that comparison, a eukaryotic nuclear transcript cannot simply reach a cytoplasmic ribosome while RNA polymerase is still transcribing the same nuclear gene; the nuclear envelope separates those locations. A primary transcript intended to become eukaryotic mRNA must first be handled inside the nucleus before export. The contrast makes the next problem unavoidable. The red ribbon in this bacterial room is already accessible to ribosomes, but the identical tagged-gene simulation in the eukaryotic route has produced a longer pre-mRNA whose ends and internal segments are still unfinished and visibly awaiting nuclear processing.",
  "Sora leaves the bacterial transcript at the open exit and carries the eukaryotic version of the red RNA ribbon into the nucleus-framed doorway. Its 5′ end is bare, its 3′ end has just passed a recognizable polyadenylation signal, and dark internal segments interrupt lighter retained regions. The next counter has three stations waiting for those features."
 ]},
'U6-L19':{
 'title':'The Eukaryotic Message Receives Protective End Marks Before Export',
 'kicker':'A eukaryotic primary transcript becomes mature mRNA only after context-appropriate processing changes its ends and internal RNA sequence.',
 'paragraphs':[
  "The nuclear doorway opens onto the **Pre-mRNA Processing Counter**. On your **left**, the **5′ cap / recognition side** holds the front end of the red transcript beneath a cap dispenser. Directly **ahead**, the center **pre-mRNA processing counter** supports the entire primary RNA transcript, with its 5′ end, internal segments, and 3′ end all visible at once. On your **right**, the **poly-A tail / stability side** displays a transcribed polyadenylation signal near the transcript’s 3′ end, followed by a cleavage marker and an empty track where a long adenine-rich tail can be added. Sora keeps the tagged DNA gene behind glass at the rear of the room. The DNA sequence is not being rewritten here; the RNA product is being processed after transcription.",
  "Sora first names the larger event **Eukaryotic pre-mRNA processing**: in eukaryotic cells, a primary RNA transcript is modified before it functions as mature mRNA. The center ribbon makes the timing visible. Transcription produced the RNA; now the RNA itself is modified. These processing steps occur in the context of eukaryotic nuclear gene expression and must not be projected backward onto every bacterial mRNA route you just saw.",
  "At the left station, a modified guanine cap is attached to the 5′ end. Sora waits until the cap is physically fixed before naming **5′ GTP cap recognition**. Addition of a 5′ GTP cap supports ribosomal recognition and also contributes to mRNA protection and handling. The cap is not a codon that will be translated into the first amino acid. It is a processing feature attached to the RNA end that helps the transcript survive, move through cellular handling steps, and be efficiently recognized for translation later.",
  "On the right, the transcribed RNA contains a sequence that helps specify where the transcript will be cleaved and where polyadenylation will occur. Sora marks **Polyadenylation signal sequence** and shows AAUAAA as a common RNA signal sequence without turning it into the tail itself. The transcript is cleaved downstream, then a long run of adenines is added to the new 3′ end. This added stretch is the poly-A tail. The distinction is visual: the signal was transcribed from DNA as part of the RNA; the long poly-A tail is added afterward.",
  "As the adenine-rich tail lengthens, Sora labels **Poly-A tail stability**: addition of a poly-A tail increases mRNA stability. She then places the cap and tail under one bracket labeled **Functions of cap and poly-A tail**. Together, the 5′ cap and poly-A tail contribute to mRNA stability, export and handling, and efficient translation initiation in eukaryotic cells. Neither feature is being treated as protein-coding sequence. They help the RNA function as a durable, properly handled message.",
  "The ends are now marked and protected, but the center of the RNA is still interrupted by dark segments. Sora tries to send the transcript toward the nuclear export door, and the door refuses it. An internal inspection light marks retained and removable RNA regions. The transcript slides into the final chamber, where the internal sequence—not the DNA gene—will be cut and rejoined."
 ]},
'U6-L20':{
 'title':'The Same Pre-mRNA Can Be Cut Into More Than One Finished Message',
 'kicker':'Splicing removes introns and joins retained exons, while alternative splicing can produce different mature mRNAs from the same underlying gene.',
 'paragraphs':[
  "The final room, the **Splice and Isoform Chamber**, is shaped around the same processed red RNA ribbon. On your **left**, the **intron excision side** holds the transcript under a scanner that marks dark internal segments for removal. Directly **ahead**, the center **exon-splicing / alternative-splicing chamber** aligns the lighter retained segments on a single 5′→3′ rail. On your **right**, the **mature-mRNA exit** leads through a nuclear-export gate toward a cytoplasmic ribosome symbol. The 5′ cap from the previous room remains fixed at the front of the ribbon, and the poly-A tail remains at the 3′ end. Sora places the unaltered tagged DNA gene above the chamber so you can compare the DNA with each RNA product without imagining that splicing changes the gene itself.",
  "The scanner first identifies introns and exons on the pre-mRNA. Sora avoids the shortcut that calls every exon an amino-acid-coding segment, because retained exons can include untranslated regions. The useful distinction is processing fate: intron regions are removed from this pre-mRNA, while exon regions are retained in the mature RNA. The dark introns lift out of the ribbon one by one. The remaining exon ends move together and are covalently joined. Sora names **Intron excision and exon splicing**: RNA processing removes introns and splices retained exons to produce mature mRNA.",
  "The chamber then resets to the same original pre-mRNA. This time, the splicing controls retain a different permitted combination of exon segments. The DNA gene above the machine never changes. The newly assembled RNA has a different exon composition from the first product. Only after the two processed RNAs are placed side by side does Sora name **Alternative splicing**: alternative splicing retains different combinations of exons, allowing one pre-mRNA to generate different mature mRNA versions. The mechanism increases possible RNA—and often protein—diversity while the **underlying gene DNA remains unchanged**; a different gene sequence is not required for every isoform.",
  "Sora returns the first processed RNA to the exit rail. It now carries a 5′ cap, a resolved exon arrangement, and a poly-A tail, and its orientation is still 5′→3′. She labels the finished molecule **Mature mRNA**: after appropriate processing, eukaryotic mature mRNA can be exported from the nucleus and used for translation in the cytoplasm. The word mature refers to the processed RNA state in this pathway. It does not mean the RNA is permanently unchanged or that every RNA molecule in a cell undergoes exactly these same processing steps.",
  "The export gate opens. The mature mRNA moves out of the nucleus and toward the cytoplasmic ribosome symbol, but Sora stops it before translation begins. Journey 2 has one job: make the message correctly. Looking backward through the open doors, you can reconstruct the entire route. RNA function depended on sequence and structure. mRNA, tRNA, and rRNA had distinct jobs. Gene expression separated transcription from translation. One DNA template strand and a promoter established transcription entry. RNA polymerase read the template 3′→5′ while synthesizing RNA 5′→3′. A bacterial transcript could become ribosome-accessible without the eukaryotic cap/poly-A/splicing sequence. A eukaryotic pre-mRNA received end modifications, then introns were removed and exons joined, with alternative splicing able to generate different mature messages from the same pre-mRNA.",
  "The mature red ribbon is clipped to Sora’s copper ledger beside the original tagged gene. The gene has not become RNA; its information has been transcribed into an RNA product. The RNA has not yet become protein; translation is still ahead. Sora points to the ribosome icon at the far end of the export corridor. The workshop has finished editing the message. The next journey will have to read it.",
  "**Optional Quick Recall.** Without looking back, picture the dark pieces leaving on the left and the retained pieces joining in the center. What is **Intron excision and exon splicing**? RNA processing removes introns and splices retained exons to produce mature mRNA."
 ]}
}

BEAT_IMAGES={
'U6-K-018':'three RNA ribbons on the center desk folding into different shapes before being routed to different jobs',
'U6-K-019':'the long mRNA ribbon moving left toward the ribosome-message rack',
'U6-K-023':'the rRNA model becoming part of the right-side ribosome shell',
'U6-K-020':'the center tRNA accepting only its matching amino-acid cargo on the left',
'U6-K-021':'the tRNA anticodon pairing antiparallel with a complementary mRNA codon on the right',
'U6-K-022':'the correctly charged, correctly paired tRNA moving toward the ribosome marker',
'U6-K-116':'the already-known folded protein model placed only at the downstream end of the gene-expression route',
'U6-K-117':'the center gene-expression junction routing gene information toward a functional RNA or polypeptide product',
'U6-K-118':'the left DNA→RNA lane where RNA polymerase makes an RNA copy from DNA information',
'U6-K-119':'the right RNA→polypeptide lane where a ribosome uses mRNA sequence to build a polypeptide',
'U6-K-024':'the violet DNA strand selected as the one RNA polymerase will read',
'U6-K-120':'the permanent TEMPLATE label placed on the violet strand',
'U6-K-123':'the large promoter gate where transcription machinery assembles before the transcribed region',
'U6-K-124':'the smaller TATA panel shown as one possible promoter element in some eukaryotic genes',
'U6-K-025':'the center rail showing DNA template read 3′→5′ while RNA grows 5′→3′',
'U6-K-122':'the initiation, elongation, and termination stations arranged in sequence on one transcription rail',
'U6-K-125':'several RNA polymerases following one another along the same active gene to make more transcripts',
'U6-K-126':'the bacterial mRNA reaching a ribosome in the same open cellular space without the eukaryotic cap-tail-splice route',
'U6-K-026':'the eukaryotic primary RNA transcript lying on the processing counter before it becomes mature mRNA',
'U6-K-027':'the long poly-A tail being added at the processed RNA 3′ end',
'U6-K-028':'the modified guanine cap attached to the processed RNA 5′ end',
'U6-K-127':'the transcribed polyadenylation signal marked before cleavage and poly-A-tail addition',
'U6-K-128':'the 5′ cap and poly-A tail bracketed together as stability, handling/export, and translation-initiation features',
'U6-K-029':'dark intron segments removed on the left while retained exons are joined in the center',
'U6-K-030':'the same pre-mRNA spliced a second time with a different exon combination while DNA remains unchanged',
'U6-K-129':'the capped, spliced, polyadenylated mature mRNA passing through the nuclear-export gate',
}

CHECKPOINTS={'U6-L14','U6-L17','U6-L20'}

def word_count(paragraphs): return len(re.findall(r"\b[\w’′'-]+\b",' '.join(paragraphs)))

def zone_objs(lid): return [{'position':p,'label':label,'symbol':sym,'description':desc} for p,label,sym,desc in ZONES[lid]]

def cast_for(lid):
    b=B[lid]; items=[{'name':'Dr. Sora Han','kind':'guide','visual':GUIDE['visual'],'job':GUIDE['story_job']}]
    for p,label,sym,desc in ZONES[lid]:
        anchor=b['spatial_layout'][p]['anchor']
        items.append({'name':label,'kind':'scientific structure, process, evidence display, or comparison','visual':desc,'job':f"Preserve the F3 {p}-side anchor ({anchor}) and perform only the scene-specific scientific role."})
    items.append({'name':'Persistent tagged gene and red RNA transcript','kind':'journey continuity object','visual':'the same tagged DNA gene with a violet template strand and promoter marker, accompanied by one red RNA transcript ribbon whose 5′ and 3′ ends remain identifiable as it is synthesized and processed','job':'keeps gene identity, template orientation, transcript direction, and processing state traceable across all eight scenes; it never substitutes for a biological term'})
    return items

def beats_for(lid):
    out=[]; terms={t['knowledge_id']:t for t in B[lid]['term_introductions']}
    for kid in B[lid]['knowledge_ids']:
        t=terms[kid]; c=CANON[kid]
        out.append({'object_id':kid,'term':t['canonical_term'],'story':BEAT_IMAGES[kid],'science':c['canonical_verified_statement'],'exact_name':bool(t['exact_name_recall']),'hint':BEAT_IMAGES[kid],'name_support':t['name_support'],'reactivation_mode':t['reactivation_mode'],'scope_class':t['scope_class']})
    return out

scenes=[]
for i,lid in enumerate(J2['route']):
    b=B[lid]; n=NARR[lid]; r=ROUTE[i]; pars=n['paragraphs']; cp=lid in CHECKPOINTS
    scenes.append({
      'scene_index':i,'locus_id':lid,'locus':r['locus'],'title':n['title'],'scene_kicker':n['kicker'],
      'location_description':b['micro_anchor'],'scene_layout':{'orientation':b['orientation_sentence'],'zones':zone_objs(lid)},
      'cast':cast_for(lid),'continuity_object':J2['continuity_object'],'story_open':pars[0],'story_paragraphs':pars,'story_close':pars[-1],
      'object_ids':list(b['knowledge_ids']),'story_beats':beats_for(lid),'prior_unit_reactivation':b['prior_unit_reactivation'],'misconception_guards':b['misconception_guards'],
      'checkpoint':cp,'checkpoint_object_id':b['primary_knowledge_id'] if cp else None,'checkpoint_prompt':b['quick_recall']['candidate_prompt'] if cp else '', 'checkpoint_answer':b['quick_recall']['answer'] if cp else '',
      'next_locus':ROUTE[i+1]['locus'] if i+1<len(ROUTE) else None,'f3_scene_brief_id':b['scene_brief_id'],'narrative_word_count':word_count(pars)
    })

journey={
 'palace_id':'U6-J2','unit_id':'unit-6','palace_name':'RNA Transcript Workshop','story_title':'The Message That Was Not Ready to Leave',
 'tagline':'One tagged gene has been cleared for expression, but the workshop cannot release its RNA until RNA roles, template choice, promoter entry, transcription direction, cellular context, end processing, and splicing all agree.',
 'guide':GUIDE,
 'premise':'A tagged gene arrives at the RNA Transcript Workshop with its violet template strand marked and a blank red transcript ribbon clipped beside it. The workshop has mixed mRNA, tRNA, and rRNA into one generic RNA category, lost the distinction between transcription and translation, and routed both bacterial and eukaryotic transcripts through the same exit. Dr. Sora Han must follow one gene and its RNA product through eight connected locations, preserving strand direction and cellular context while the message is made and, where appropriate, processed.',
 'mission':'Follow the tagged gene from RNA-role sorting through transcription entry and directional synthesis, then compare the open prokaryotic exit with the eukaryotic pre-mRNA processing route. Keep the same violet template strand and red RNA transcript identifiable while promoter, 5′→3′ synthesis, cap, poly-A tail, introns, exons, alternative splicing, and mature mRNA are resolved.',
 'finale':'The workshop releases a mature eukaryotic mRNA only after the same transcript has been synthesized 5′→3′ from one DNA template, distinguished from bacterial transcript handling, capped, polyadenylated, and spliced. The tagged gene remains DNA, transcription remains distinct from translation, and the completed red RNA message exits toward the ribosome with its processing history reconstructable from the route.',
 'estimated_minutes':25,'scene_count':8,'checkpoint_count':3,'student_release':'DEVELOPER_PREVIEW_F4B','preview_release':True,'narrative_design':'U6-F4B-NARRATIVE-1.0',
 'learner_rule':'Read or listen and place yourself in the room before following the molecular action. The same tagged gene and red RNA transcript persist across all eight locations. Exact terms are attached to structures and mechanisms after their defining feature is visible. Optional Quick Recall appears only three times.',
 'route_orientation':'This is one continuous eight-location route through the RNA Transcript Workshop. Enter at the RNA Function Desk, pass the tRNA Courier Bay and Gene Expression Junction, choose the template and promoter at the entry gate, follow the transcript along the direction rail, compare the open prokaryotic exit, then finish at the eukaryotic processing counter and splice chamber. The same tagged gene, violet template strand, promoter marker, and red RNA transcript remain reconstructable throughout.',
 'route':ROUTE,'scenes':scenes,'source_brief_lock':'LOCKED_F3','scientific_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2'
}

(U6/'journeys').mkdir(exist_ok=True)
(U6/'journeys'/'U6-J2.json').write_text(json.dumps(journey,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# combined developer preview registry
j1=json.loads((U6/'journeys'/'U6-J1.json').read_text(encoding='utf-8'))
summary={'schema':'memory-palace-v2-unit6-f4b-journeys-1.0','unit_id':'unit-6','stage':'F4B','student_release':False,'preview_release':True,'journey_count':2,'scene_count':20,'checkpoint_count':j1['checkpoint_count']+journey['checkpoint_count'],'guided_journeys':[{k:j[k] for k in ['palace_id','palace_name','story_title','tagline','guide','premise','mission','finale','estimated_minutes','scene_count','checkpoint_count','student_release','narrative_design']} for j in [j1,journey]]}
(U6/'journeys-f4b.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

status={'unit_id':'unit-6','number':6,'title':'Gene Expression and Regulation','status':'F4B_JOURNEYS1_2_POLISHED_DEVELOPER_PREVIEW','pipeline_stage':'F4B_JOURNEY2_NARRATIVE','canonical_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','narrative_lock':'LOCKED_F4B_J1_J2','student_release':False,'preview_release':True,'journey_count':2,'scene_count':20,'memory_objects':0,'application_challenges':0,'canonical_records':202,'architecture_journeys':6,'architecture_loci':53,'scene_briefs':53,'palace_managed_records':161,'challenge_lab_records':16,'scope_guard_records':25,'exact_name_review_targets':134,'confusable_sets':37,'optional_first_exposure_recalls':18,'f4a_journey':'U6-J1','f4a_scene_count':12,'f4b_journey':'U6-J2','f4b_scene_count':8,'f4b_knowledge_records':26,'f4b_optional_recalls':3,'next_required_output':'F4C polished narrative for Journey 3 only after Journeys 1 and 2 remain frozen and F4A/F4B prose-quality gates continue to pass.'}
(U6/'status-f4b.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); (U6/'status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
cp=ROOT/'content'/'ap-biology'/'course.json'; course=json.loads(cp.read_text(encoding='utf-8')); u=next(x for x in course['units'] if x['unit_id']=='unit-6'); u.update({'status':'F4B_JOURNEYS1_2_POLISHED_DEVELOPER_PREVIEW','journey_count':2,'scene_count':20,'student_release':False,'preview_release':True,'source_status':'AUDITED_F1_ARCHITECTURE_F2_BRIEFS_F3_NARRATIVE_F4B','narrative_lock':'LOCKED_F4B_J1_J2','narrative_journeys':2}); cp.write_text(json.dumps(course,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

doc=['# Unit 6 F4B · Journey 2 Narrative','','## The Message That Was Not Ready to Leave','',journey['tagline'],'','### Route','', ' → '.join(x['locus'] for x in ROUTE),'']
for s in scenes:
    doc += [f"## {s['scene_index']+1}. {s['locus']} · {s['title']}",'',f"*{s['scene_kicker']}*",'']+s['story_paragraphs']+['']
    if s['checkpoint']: doc += ['**Optional Quick Recall**','',s['checkpoint_prompt'],'']
(ROOT/'docs'/'UNIT6_F4B_JOURNEY2_STORY.md').write_text('\n'.join(doc),encoding='utf-8')

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
# Freeze J1 exactly from F4A plus new J2 and F4B registry/status.
locked_rel=['journeys/U6-J1.json','journeys/U6-J2.json','journeys-f4b.json','status-f4b.json']
lock_files={rel:{'bytes':(U6/rel).stat().st_size,'sha256':sha(U6/rel)} for rel in locked_rel}
lock={'schema':'memory-palace-v2-unit6-f4b-lock-1.0','unit_id':'unit-6','lock_status':'LOCKED_F4B_J1_J2','student_release':False,'preview_release':True,'protected_prior_locks':['content-lock-f1.json','content-lock-f2.json','content-lock-f3.json','content-lock-f4a.json'],'frozen_f4a_journey_sha256':sha(U6/'journeys/U6-J1.json'),'journey_ids':['U6-J1','U6-J2'],'scene_count':20,'new_journey_scene_count':8,'new_journey_knowledge_record_count':26,'new_journey_checkpoint_count':3,'files':lock_files,'rule':'Journey 1 remains byte-frozen from F4A. Journey 2 polished prose may not change after F4B without a new explicit narrative version. F1 science, F2 classification/geometry, and F3 briefs remain authoritative boundaries.'}
(U6/'content-lock-f4b.json').write_text(json.dumps(lock,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
release={'schema':'memory-palace-v2-unit6-f4b-release-1.0','generated_utc':'2026-09-08T01:45:00+00:00','unit_id':'unit-6','release_status':'F4B_JOURNEYS1_2_POLISHED_DEVELOPER_PREVIEW','student_release':False,'preview_release':True,'journeys':2,'scenes':20,'new_journey_id':'U6-J2','new_journey_scenes':8,'new_journey_knowledge_records':26,'new_journey_optional_first_exposure_recalls':3,'canonical_records':202,'permanent_loci_architecture':53,'scene_briefs':53,'memory_objects':0,'application_challenges':0,'scientific_lock':'LOCKED_F1','architecture_lock':'LOCKED_F2','scene_brief_lock':'LOCKED_F3','narrative_lock':'LOCKED_F4B_J1_J2','next_stage':'F4C Journey 3 polished narrative after F4A/F4B regression'}
(U6/'f4b-release-manifest.json').write_text(json.dumps(release,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'journey':'U6-J2','scenes':8,'knowledge_records':26,'checkpoints':3,'words':sum(s['narrative_word_count'] for s in scenes),'min_words':min(s['narrative_word_count'] for s in scenes),'max_words':max(s['narrative_word_count'] for s in scenes)},indent=2))
