from __future__ import annotations

import argparse
import os
from pathlib import Path
import socket
import sys
import threading
import time
from urllib.error import URLError
from urllib.request import urlopen
import webbrowser


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def load_env_file(path: Path) -> None:
    if not path.exists():
        raise SystemExit(
            f"Local Content Studio environment file not found: {path}. "
            "Run scripts/setup_content_studio_local.py first."
        )
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"Invalid environment line {line_number} in {path}")
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            raise SystemExit(f"Invalid environment key on line {line_number} in {path}")
        os.environ[key] = value


def require(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required local Content Studio setting: {name}")
    return value


def ensure_loopback_port_available(port: int) -> None:
    probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        probe.bind(("127.0.0.1", port))
    except OSError as exc:
        raise SystemExit(
            f"Local port {port} is already in use. Close the other program or change "
            "MEMORY_PALACE_PORT in .env.content-studio-local."
        ) from exc
    finally:
        probe.close()


def open_browser_when_ready(url: str, *, timeout_seconds: float = 20.0) -> None:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        try:
            with urlopen(url, timeout=0.5) as response:
                if 200 <= response.status < 500:
                    webbrowser.open(url, new=2)
                    return
        except (URLError, OSError):
            time.sleep(0.2)
    print(f"Browser did not open automatically. Open {url} manually.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run The Story Method Content Studio locally with zero hosting cost."
    )
    parser.add_argument(
        "--env-file",
        default=".env.content-studio-local",
        help="Local ignored environment file generated by setup_content_studio_local.py",
    )
    parser.add_argument(
        "--open-browser",
        action="store_true",
        help="Open the local Content Studio page after the server becomes reachable",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file).expanduser().resolve()
    load_env_file(env_path)

    # Hard local-only safety locks. Values in the env file cannot widen network access
    # or enable publication during this rehearsal.
    os.environ["MEMORY_PALACE_ENV"] = "development"
    os.environ["MEMORY_PALACE_HOST"] = "127.0.0.1"
    os.environ["MEMORY_PALACE_ADMIN_ENABLED"] = "true"
    os.environ["MEMORY_PALACE_ADMIN_PUBLICATION_ENABLED"] = "false"
    os.environ["MEMORY_PALACE_GITHUB_PUBLICATION_ENABLED"] = "false"
    os.environ["MEMORY_PALACE_GITHUB_ALLOW_MERGE"] = "false"

    require("MEMORY_PALACE_ADMIN_USERNAME")
    password_hash = require("MEMORY_PALACE_ADMIN_PASSWORD_HASH")
    require("MEMORY_PALACE_ADMIN_SESSION_SECRET")
    if not password_hash.startswith("scrypt$"):
        raise SystemExit("Local owner password hash is invalid. Re-run credential setup.")

    port_raw = os.getenv("MEMORY_PALACE_PORT", "8000").strip()
    try:
        port = int(port_raw)
    except ValueError as exc:
        raise SystemExit("MEMORY_PALACE_PORT must be an integer") from exc
    if port < 1024 or port > 65535:
        raise SystemExit("MEMORY_PALACE_PORT must be between 1024 and 65535")

    ensure_loopback_port_available(port)
    (ROOT / "server_data").mkdir(parents=True, exist_ok=True)
    os.chdir(ROOT)

    import uvicorn

    url = f"http://127.0.0.1:{port}/admin"
    print("Starting local-only Content Studio")
    print(f"Open {url}")
    print("Network binding is restricted to this computer.")
    print("Publication, GitHub delivery, and merge remain disabled.")
    print("This mode requires no hosting account or paid service.")

    if args.open_browser:
        opener = threading.Thread(
            target=open_browser_when_ready,
            args=(url,),
            daemon=True,
            name="content-studio-browser-opener",
        )
        opener.start()

    uvicorn.run(
        "backend.main:app",
        host="127.0.0.1",
        port=port,
        reload=False,
        access_log=True,
    )


if __name__ == "__main__":
    main()
