from __future__ import annotations

import argparse
import os
from pathlib import Path


def load_env_file(path: Path) -> None:
    if not path.exists():
        raise SystemExit(
            f"Local Content Studio environment file not found: {path}. "
            "Run scripts/setup_content_studio_local.py first."
        )
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"Invalid environment line {line_number} in {path}")
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            raise SystemExit(f"Invalid environment key on line {line_number} in {path}")
        os.environ[key] = value


def require(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required local Content Studio setting: {name}")
    return value


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run The Story Method Content Studio locally with zero hosting cost."
    )
    parser.add_argument(
        "--env-file",
        default=".env.content-studio-local",
        help="Local ignored environment file generated by setup_content_studio_local.py",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file).expanduser().resolve()
    load_env_file(env_path)

    # Hard local-only safety locks. Values in the env file cannot widen network access
    # or enable publication during this rehearsal.
    os.environ["MEMORY_PALACE_ENV"] = "development"
    os.environ["MEMORY_PALACE_HOST"] = "127.0.0.1"
    os.environ["MEMORY_PALACE_ADMIN_ENABLED"] = "true"
    os.environ["MEMORY_PALACE_ADMIN_PUBLICATION_ENABLED"] = "false"
    os.environ["MEMORY_PALACE_GITHUB_PUBLICATION_ENABLED"] = "false"
    os.environ["MEMORY_PALACE_GITHUB_ALLOW_MERGE"] = "false"

    require("MEMORY_PALACE_ADMIN_USERNAME")
    password_hash = require("MEMORY_PALACE_ADMIN_PASSWORD_HASH")
    require("MEMORY_PALACE_ADMIN_SESSION_SECRET")
    if not password_hash.startswith("scrypt$"):
        raise SystemExit("Local owner password hash is invalid. Re-run credential setup.")

    port_raw = os.getenv("MEMORY_PALACE_PORT", "8000").strip()
    try:
        port = int(port_raw)
    except ValueError as exc:
        raise SystemExit("MEMORY_PALACE_PORT must be an integer") from exc
    if port < 1024 or port > 65535:
        raise SystemExit("MEMORY_PALACE_PORT must be between 1024 and 65535")

    Path("server_data").mkdir(parents=True, exist_ok=True)

    import uvicorn

    print("Starting local-only Content Studio")
    print(f"Open http://127.0.0.1:{port}/admin")
    print("Network binding is restricted to this computer.")
    print("Publication, GitHub delivery, and merge remain disabled.")
    print("This mode requires no hosting account or paid service.")
    uvicorn.run(
        "backend.main:app",
        host="127.0.0.1",
        port=port,
        reload=False,
        access_log=True,
    )


if __name__ == "__main__":
    main()
