function esc(v=''){return String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
export function reviewView(items,total=items.length,mixedSets=[]){
 if(!items.length)return `<main id="main-content" tabindex="-1" class="review-wrap"><section class="card review-empty"><span class="eyebrow">Review</span><h1>Nothing is due right now.</h1><p class="muted">Keep learning. Review items appear after you encounter them in a journey.</p><button class="primary" data-action="home">Back to home</button></section></main>`;
 const x=items[0];
 if(x.type==='mixed'){
   const set=mixedSets.find(s=>s.set_id===x.setId),q=set?.questions?.[Number(x.questionIndex||0)];
   if(!set||!q)return `<main id="main-content" tabindex="-1" class="review-wrap"><section class="card review-empty"><h1>This review item could not be loaded.</h1><p class="muted">Return Home and try Review again.</p><button class="primary" data-action="home">Back to home</button></section></main>`;
   return `<main id="main-content" tabindex="-1" class="review-wrap"><section class="card review-card mixed-review-card"><span class="eyebrow">Mixed discrimination · ${esc(set.title)}</span><h1>${esc(q.prompt)}</h1><p class="muted">Choose the term that best matches the scientific description. Palace location is deliberately hidden.</p><div class="choice-grid">${q.choices.map(c=>`<button class="choice-button" data-action="mixed-choice" data-set="${esc(set.set_id)}" data-choice="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="reviewFeedback" class="feedback-region" aria-live="polite"></div><button class="ghost" data-action="home">Back to home</button></section></main>`;
 }
 return `<main id="main-content" tabindex="-1" class="review-wrap"><section class="card review-card"><span class="eyebrow">${total} due · showing at most 5 this session</span><h1>${esc(x.prompt)}</h1><p class="muted">Try to retrieve the term or idea from its scientific meaning. The text box can make your thinking explicit, but the site does not automatically grade your wording.</p><label class="field-label" for="reviewInput">Optional retrieval note</label><input class="review-answer" id="reviewInput" autocomplete="off" placeholder="Type the term or idea you recalled"/><div class="row review-actions"><button class="primary" data-action="review-remembered" data-object="${esc(x.objectId)}">I remembered it</button><button class="secondary" data-action="review-hint" data-object="${esc(x.objectId)}">Need a hint</button></div><div id="reviewFeedback" class="feedback-region" aria-live="polite"></div><button class="ghost" data-action="home">Back to home</button></section></main>`;
}
